### ISSUE TITLE
Parallel coordinates page not working

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#112]
See page: https://www.mousephenotype.org/data/parallel#

Scope of work:
* Needs to be restyled according to the new IMPC look and feel
* Javascript needs to be updated to work with the new site
* Documentation needs to be migrated from old site to new WP site

**Comment by viomunoz** [comment]
See page: https://www.mousephenotype.org/data/parallel#
Only a default mean value of 0 and a default  value of 0 are shown when you remove genes from the list. For example, if you filter for ECG and ECHO and Aak1, and then remove Aak1:
![Screenshot 2019-07-26 at 14 11 46](https://user-images.githubusercontent.com/29598654/61954208-3af8ce80-afb0-11e9-87f2-a3c54fdc79fa.png)

Good when all genes are shown again.

**Comment by viomunoz** [comment]
The text needs to be updated. Please use the following:

---

The parallel coordinates viewer allows to visualize multiple mouse lines for multiple parameters for selected procedures. Only continous parameters can be visualized using this methodology. 

The values displayed are genotype effects. The measurement values are corrected to account for batch effects to represent the true genotype effect, thus allowing a side-by-side comparison.

**How to use this tool?**

Select one or several procedure(s) using the procedure filter tab. Additional optional filtering include phenotyping center or mouse gene list of interest selection. If no genes are selected, the tool will show all genes in IMPC for the selected procedure(s) and/or center selected. 

The graph is interactive and allows filtering on each axis (parameter) by selecting the region of interest. Several regions of interests can be selected one by one.

Clicking on a chosen line on the graph or on a gene name from the table will highlight the corresponding gene. For a selected gene, if any significant phenotype is associated with a parameter, the parameter name will change to bold. To remove all filters, simply reload the page.

More information can be found in the [Help pages](https://www.mousephenotype.org/help/faqs/data-visualization/parallel-coordinates-viewer/?preview_id=2796&preview_nonce=39e27aee02&preview=true).
---
