### ISSUE TITLE
The old allele details pages are unstyled and still available on the portal

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#116]
We need to redirect from these old allele detail pages to the order section on the gene page, which has assumed the functionality.

The initial question is:

The formatting is not quite right on the allele page though. But I can see the information I needed to see.

See: https://www.mousephenotype.org/data/alleles/MGI:1923661/tm1a(EUCOMM)Hmgu

**Comment by ficolo** [comment]
I think you could just reuse what I did on: https://github.com/mpi2/PhenotypeData/blob/master/web/src/main/webapp/WEB-INF/views/allelesFrag.jsp
