### ISSUE TITLE
Add histopathology section to the Gene Page

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#118]
<img width="1666" alt="Screenshot 2019-05-31 at 08 04 26" src="https://user-images.githubusercontent.com/2343039/58687849-bce6c580-837a-11e9-8695-45ff8d5ac62c.png">
<img width="1669" alt="Screenshot 2019-05-31 at 08 04 20" src="https://user-images.githubusercontent.com/2343039/58687850-bce6c580-837a-11e9-9b15-017b6d0405c8.png">

**Comment by viomunoz** [comment]
Done in IMPC Website Redesign on 31 May 2019
