### ISSUE TITLE
Link gene pages to Embryo Viewer

### ISSUE THREAD

**Issue by amccoy95** [mpi2/PhenotypeData#126]
As discussed in the Dev call, the Gene pages need to be linked to the Embryo Viewer at web.mousephenotype.org/embryoviewer this is currently getting reskinned and the HTTPS issue needs to be resolved before adding these links.

Will provide update when the IEV is ready to be linked to on this issue

**Comment by jmason-ebi** [comment]
Heard that the viewer is back online.  For instance:
https://www.mousephenotype.org/embryoviewer/?gene_symbol=cbx4

**Comment by viomunoz** [comment]
Buttons to change developmental stage on the top right corner of images not working. Has been reported to Henrik.

We have this page at the moment to link with the IEV, but it is static (based on the genes that were available in the old IMPC website):
https://www.mousephenotype.org/understand/advanced-tools/embryo-viewer/
