### ISSUE TITLE
Add filter to all data table

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#129]
When viewing all data for a gene, there could be several hundred entries (see screenshot).  It is cumbersome to page through the results to find the parameter of interest.

Requirements:
* A filter on the table that filters the results 
* The filter does not effect the chart tab
* There is a text label saying "Filter this table"
* Filter may or may not persist when navigating away from the table tab

![image](https://user-images.githubusercontent.com/1931551/59844508-f9428b80-9352-11e9-938f-5f3ba5da6dbb.png)

For gene: https://www.mousephenotype.org/data/genes/MGI:88555

**Comment by viomunoz** [comment]
Additional requirements:

- When you hover over the table, the row you hover over needs to get highlighted (similar to the way the Significant phenotypes table gets highlighted) so the user notices (hopefully!) the row is clickable.
- When you click on a row, you get to the chart page (this is ok), but when you click the back button the user would expect to be returned to the exact same table s/he was looking at, same filters and order. (However, the user is returned to the Significant Phenotypes table, table view and order is lost.)
