### ISSUE TITLE
Image comparison updates

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#131]
Received user feedback about the X-ray viewer:

1. Zygosity, and sex aren't displayed, even though you can filter for these. Controls aren't labeled as such either, although I assumed the left images were controls based on the number and experience. Sex is missing on controls as well, however.
* Sex and zygosity are available on hovering on the thumbnails, but we should make it more prominent.

2. Not clear how to return to the gene page. Clicking "back" gets you to the gene search result, which could be frustrating for users.
* Note sure how to replicate this, but when I click back from the image viewer, I got the gene page.  Adding breadcrumbs would help.

Example page here:
https://www.mousephenotype.org/data/imageComparator?&parameter_stable_id=IMPC_XRY_051_001&acc=MGI:1924076

![image](https://user-images.githubusercontent.com/1931551/60087663-5bc1d000-9735-11e9-8edd-7126a3ece271.png)

**Comment by jwgwarren** [comment]
Most of these were design decisions made although the colour background to the images that shows sex is now missing probably due to style sheet changes in the new skin. Can do these though. obviously more real estate will be taken up by each thumbnail.

**Comment by jwgwarren** [comment]
There is a breadcrumb in the page but it doesn't show...hmmmm...

**Comment by jwgwarren** [comment]
zygosity and sex have been added as text to the thumbnails and WT and Mutant have been added to the headers of the main images.
