### ISSUE TITLE
Embryo Development landing page "See All" button not working

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#137]
In the 3D section of the landing page, clicking on the "See All" button returns an error (see image below): https://www.mousephenotype.org/data/embryo

One solution is that the "See All" button redirects to the IEV page:
https://www.mousephenotype.org/understand/advanced-tools/embryo-viewer/
As a long-term solution, we need to ensure the content on this page is not static.

Image appearing when clicking the "See All" button on Embryo Development LP, section on 3D imaging:
![Screenshot 2019-07-02 at 11 49 01](https://user-images.githubusercontent.com/29598654/60507145-680ed580-9cbf-11e9-8e31-2efcf7bdea41.png)

**Comment by jmason-ebi** [comment]
Implementing the link to the embryo-viewer page
