### ISSUE TITLE
Parallel coordinates in Cardiovascular page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#145]
There have been some changes as to how the parallel coordinates tool is behaving since the last time the text was updated.
Scroll down to the Parallel Coordinates chart:
https://www.mousephenotype.org/data/biological-system/cardiovascular

Requirements:

1.- Can we edit the text to have the follwing:
---
The parallel coordinates viewer allows to compare variation across parameters for a particular mouse line, as well as across lines, for continous parameters. 

The values displayed are the genotype effect. The measurement values are corrected to account for batch effects to represent the true genotype effect, thus allowing a side-by-side comparison.

Use this interactive graph and table:

- Drag your mouse pointer on any parameter axis to select a region of interest and highlight the relevant mouse lines in the chart. The associated gene/s will be automatically filtered for in the gene table below.
- You can click on a line to highlight it. The associated gene will be automatically filtered for in the gene table below.
- You can filter by procedure. You can click on the parameter name to know more about it – you get redirected to the IMPReSS pages.
- Click on any row in the gene table to highlight the corresponding values in the graph above. Clicking on the gene name will open the associated gene page. 
- When you select a gene row, the parameter name in the graph will change to bold if genotype is significant.
- Reload page to return to the default view.
---
2.- Currently clicking on the parameter name does not bring you to the IMPRESS pages. Can change this behaviour so that the relevan IMPReSS page opens or, if this takes too much time, remove the corresponding text in the bulleted list and substitute by this one "You can learn more about the parameters by searching for them in [IMPReSS](https://www.mousephenotype.org/impress)".

3.- Remove line "Genotype effect for gene: Prdm4". It is not working properly and it is not needed.

**Comment by jmason-ebi** [comment]
Agreed with Violeta to Not doing #3
