### ISSUE TITLE
Gene pages in need of SEO improvements

### ISSUE THREAD

**Issue by amccoy95** [mpi2/PhenotypeData#147]
A comment that was passed to me from the UCD visit is people are using Google and not the homepage/ search page to search for genes (e.g. cib2 gene).

After testing the search term the pages don't appear for at least 3 pages. 

I think this is also inline with the Google Analytics which have dropped since release day. They have been slowly improving but are still small in comparison to 3 - 4 months ago.

**Comment by viomunoz** [comment]
Has this been resolved?

**Comment by amccoy95** [comment]
This is a duplicate of this issue: https://github.com/mpi2/PhenotypeData/issues/216

This one can be closed.
