### ISSUE TITLE
Gene page: displaying data that is not analysed

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#155]
Currently, data that is not analysed, is not displayed in the IMPC website. We may want to think about ways in which data that has been collected, but is not analysed, is displayed in the IMPC website. One place to do so could be the All measurements table/section of the Gene page.

**Examples:**
1- Hot Plate data.  Both of the simpleParameters in the procedure (Hot plate latency and Type of response) are marked as "do not annotate" (see [Hot Plate in IMPRESS](https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=198&pipeID=7) ) and, because of this, excluded from the analysis.

 ICS_HOT_003_001 - Hot plate latency parameter

Example Link:
https://www.mousephenotype.org/data/genes/MGI:2450016

Example screenshot:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/803ee587-af5a-49f3-8c46-a8136120094c)

2- CHL data.  All parameters are timeSeries parameters, rather than simpleParameters (see [CHL in IMPRESS](https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=112&pipeID=7)). There is no derived parameter to analyse. Frequency of breathing(f), Tidal volume (TVb), and Enhanced pause (Penh) are all seriesParameters.

**Comment by jmason-ebi** [comment]
This is now available due to the fix for #234

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/2b121e55-1fbd-4fe6-9943-bfa7ae90b3be)
