### ISSUE TITLE
Incorrect statistical result section displayed

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#156]
View page:
https://dev.mousephenotype.org/data/charts?accession=MGI:2444817&allele_accession_id=MGI:5910368&zygosity=homozygote&parameter_stable_id=IMPC_CSD_011_001&pipeline_stable_id=JAX_001&phenotyping_center=JAX

![image](https://user-images.githubusercontent.com/1931551/64025937-b1e83080-cb35-11e9-9369-9ee20ba91091.png)

This is a *male only* result:
https://dev.mousephenotype.org/data/genes/MGI:2444817
![image](https://user-images.githubusercontent.com/1931551/64025995-cf1cff00-cb35-11e9-932f-24d450d28a61.png)

The Statistical result section on the chart page should reflect the actual p-value used to make the phenotype call (in this case: Male p-value: 6.15026E-6)

**Comment by viomunoz** [comment]
The p-value is no longer displayed:

![Screenshot 2020-02-05 at 15.30.27.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/becf22f3-6e26-4b43-a57e-2ddbc996632f)

**Comment by viomunoz** [comment]
Checked by two members of the team, looks good now.
