### ISSUE TITLE
Phenotype pages: derived parameter needs to be shown

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#160]
See phenotype: impaired glucose tolerance 
https://www.mousephenotype.org/data/phenotypes/MP:0005293

When clicking on a row to see the underlying data, the raw data are shown, and not the derived parameter to which the significance is associated.

**Requirement:**
Show both the underlying and the derived parameter.

---

Example of chart page: 

![Screenshot 2019-09-02 at 17 06 37](https://user-images.githubusercontent.com/29598654/64126027-14466880-cda4-11e9-817d-8ccb03edb028.png)

**Comment by jmason-ebi** [comment]
Adding all possible charts for derived data that could have lead to the call (i.e., Parameters for IPGTT curve (IMPC_IPG_002_001) include IMPC_IPG_012_001, IMPC_IPG_011_001, IMPC_IPG_010_001)
