### ISSUE TITLE
Summarize the requirements for the Ageing landing page

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#170]
As a developer, I want to be able to reference a document that summarized the requirements of the landing page.

Acceptance Criteria:
* Document exists describing the requirements

**Comment by viomunoz** [comment]
Related ticket: [#196](https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/196)

**Comment by viomunoz** [comment]
Heatmap under development: see ticket #[196](https://github.com/mpi2/PhenotypeData/issues/196)
Heatmap will be linked from the DATA menu: see ticket #[242](https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/242)

**Comment by viomunoz** [comment]
Apart from a dedicated LA data heatmap, we need to display available LA data in Gene Page:
(1) Indicate that LA data is available, with a link to the heatmap
(2) Presence of hits - do we want to have a LA displayable phenogrid?

Some mockups here:

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/2be484ba-2e6f-4292-a978-957c2b590c52)

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/00f94640-6836-4283-a5fc-df30ec2fc69d)
