### ISSUE TITLE
Track clicks on the tissue enqueriy form

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#176]
The stakeholders would like to be able to track clicks on the tissue request form.  See example from https://www.mousephenotype.org/data/genes/MGI:107448

![image](https://user-images.githubusercontent.com/1931551/65435739-e7bcc400-de18-11e9-80ca-6d6b08989d2c.png)

The suggestion from the Histopath WG call is to use Google Analytics custom event code attached to this button, which, normally, is a mailto link.

**Comment by amccoy95** [comment]
The best way to track events on a page is by using Google Tag Manager. I've created a test tag on the dev site and it's tracking the clicks instantly (I did try just an onClick function for GA but they were not being tracked properly).

Do we want to track all clicks on all tissue enquiry buttons for all genes? This will be the easiest way. I just need an identifiable class on these buttons e.g. class="tissue-enquiry" then I can target the click events. 

You will also have to add the Google Tag Manager HTML tags to the top of the head and body of the gene pages. 

Side note: I noticed the two buttons have different subject lines, maybe change the text into the button to reflect this as it looks like they're just duplicated
