### ISSUE TITLE
Problems with viability display: discrepancy between primary and secondary viability

### ISSUE THREAD

**Issue by hughbedo** [mpi2/PhenotypeData#184]
**Display of primary viability in "Measurements chart": **
- If the line is subviable or lethal: p-value = 0 (the line is abnormal) and the icon on the all measurements chart is at the right. This is OK.
Example: Anapc1 https://www.mousephenotype.org/data/genes/MGI:103097

![Screenshot 2020-03-09 at 17.34.54.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/5c527ba8-a15c-41e6-9754-db84f4f5d894)

- If the line is viable: p-value = 1 and then it is not displayed on the chart tab. Example: Cib2 https://www.mousephenotype.org/data/genes/MGI:1929293
 
![Screenshot 2020-03-09 at 17.36.46.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/2e0d0ab2-8907-46c0-bfa8-4eee2dbaca38)

This message might be confusing to the users and could be made clearer (see Requirements below).
We need to discuss internally whether Viability Outcome is to be displayed in the "Measurements chart".

**Display of secondary viability in "Measurements chart": **
- Line [Nrxn1](https://www.mousephenotype.org/data/genes/MGI:1096391) has an E18.5 secondary screen result of viable. The numbers indicate the line is viable [(4 homs out of 27)](https://www.mousephenotype.org/data/charts?accession=MGI:1096391&parameter_stable_id=IMPC_EVP_001_001&allele_accession=MGI:5636923&zygosity=homozygote&phenotyping_center=MRC%20Harwell&bare=true).   Thus it seems wrong or confusing to show as outcome a p-value of 0 / icon shown on the right of the all measurements chart, which would seem to indicate that there is a phenodeviancy here, but viable is the normal result.  

![Screenshot 2020-03-09 at 17.51.14.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/7881b691-46a8-4f4d-b4ee-26deb22992ee)

**Requirements:**
1.- When Viability outcome is viable, p-value=1, message displayed in "Measurements chart" for "Mortality/aging" could be clearer, to indicate there is data -- current message might no be interpreted correctly by the users. Current message:
"Statistical analisys has not been perform on any of the selected systems. Check the table view to see the raw data."
could be changed to:
"This line is viable. Check the Viability results above and/or the table view to see the raw data."
Alternatively, we can choose to always display viability data in the Measurements chart.

2.- Fix results for embryo viability. Phenodeviance is indicated when result is lethal or subviable.

**Comment by viomunoz** [comment]
In addition:
1.- Similar to what happens with fertility data (see ticket [#62](https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/62)), the results in the All data table are not informative:
https://www.mousephenotype.org/data/genes/MGI:1096391

![Screenshot 2020-02-05 at 17.19.56.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c2d434a4-edaa-44f1-809e-d84fca7f137e)

2.- Primary Viability not displayed in Measurements chart. Example genes: [Nrxn1](https://www.mousephenotype.org/data/genes/MGI:1096391) and [Acan](https://www.mousephenotype.org/data/genes/MGI:99602)

---
![Screenshot 2020-02-05 at 17.28.53.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c41036e9-27d6-42df-9b50-7afdc1025dc1)

---

![Screenshot 2020-02-05 at 17.28.15.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/aa81fef0-4e3f-4cc9-99d8-76d41ee3ed93)

---
**Requirements:**
1. Can we display actual data in All data table?
2. Can we display primary viability in Measurements chart?

**Comment by viomunoz** [comment]
Note also: chart was showing only results for E18.5 and not E12.5 (however, both embryo viability outcome is "Viable"? 
(Note about the "?": E12.5 results will not load, so unable to check.)

![Screenshot 2020-04-03 at 12.46.03.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/7134bd3f-c791-467d-a847-36679db73f96)

**Comment by jwgwarren** [comment]
with regards to cib2 the viability has no p-Value when it comes back from solr. so I guess it won't be displayed. I'll check elsewhere in the code why this is.

**Comment by jwgwarren** [comment]
Anapc1 does indeed have 2 results (provided values as well) that are 0.0 for viability

**Comment by jwgwarren** [comment]
I'm pretty sure we adjusted the alldata results to come from experiment core and SR core but now I see no reference to both cores in either the table code or the char code???

**Comment by viomunoz** [comment]
Viability has no p-value becasue in the website we report the viable/subviable/lethal outcome as reported by the centers.

**Comment by viomunoz** [comment]
Anapc1
https://www.mousephenotype.org/data/charts?accession=MGI:103097&parameter_stable_id=IMPC_VIA_001_001
"Associated Phenotype" is "Homozygous - Lethal" (there are 0 hom pups), rahter than "Associated Phenotype: No significant association" as it currently says.

**Comment by viomunoz** [comment]
Problem for VIA data at the Embryo stage is that it is displayed as "Not significant" and "p-value = 0". These are screenshots from the All Data table:

![Screenshot 2020-05-18 at 15.17.18.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/34d6402d-2141-4510-87aa-42b8f3663455)

![Screenshot 2020-05-18 at 15.17.08.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3f25644d-6d2b-473f-b840-bfcc498fb91f)

Underlying data shows line is Viable:


![Screenshot 2020-05-18 at 15.20.44.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/8b6b5185-0cdb-4704-a33a-b49f925d5bb1)

Thus we expect "Not significant" and p-value = 1 (as for primary viability).

We need to understand where the discrepancy is arising.

**Comment by jwgwarren** [comment]
with cib2 the statsresults core has no p_value field at all and is labelled as supplied but also has <bool name="significant">false</bool>

**Comment by jwgwarren** [comment]
Whereas the data that displays with Anapc1 has the same accept p_value and significant = true, so two flags to say display this value and its significant
<double name="p_value">0.0</double>
<double name="effect_size">1.0</double>
<arr name="categories">
<str>Homozygous - Lethal</str>
</arr>
<long name="external_db_id">22</long>
<long name="phenotyping_center_id">6</long>
<long name="project_id">13</long>
<bool name="significant">true</bool>

**Comment by ficolo** [comment]
The class I won't be touching:

org.mousephenotype.cda.loads.annotations.OntologyAnnotationGenerator

**Comment by viomunoz** [comment]
Team met and agreed:

- Do not show the viability data / p-value on the measurement chart;
- Change messaging from: “Statistical analisys has not been perform on any of the selected systems. Check the table view to see the raw data.” to  “**Check the table view to see the raw data**.”;
- The statistical-result core indexer should not create p-values for the adult viability data.  It only significance should be based only on the outcome parameter (significant is true when it’s not viable).

**Comment by jwgwarren** [comment]
Any observation GP core has been removed from the chart if has parameter stable id like _VIA_ .

**Comment by jwgwarren** [comment]
Had to modify code to use iterators as otherwise throws a concurrent modfication exception on the hashmap list of rows being removed

**Comment by jwgwarren** [comment]
Changed messages as requested - however should we remove dropdowns that aren't applicable

**Comment by jmason-ebi** [comment]
Mostly done -- some logic to revisit.

**Comment by viomunoz** [comment]
1.-When two systems are selected, mortality/aging and another physiological sytems that is significant, the p-value message for mortality/aging doesn not show up. We need to show: "Mortality/aging does not have p-values available. Please check the All Data table tab to see all available data."

2.-This comment:
"Mouseover the data points for more information. Click and drag to zoom the chart. Click on the legends to disable/enable data. This chart shows only the most significant p-values, please check the table view to see all available data."
Change "table view" to "All data table tab" to make it easier for the users to know what we are referring to.

3.-Fix to have the same behaviour for Embryo viablity: show same messages as for primary viability. Example: https://www.mousephenotype.org/data/genes/MGI:1096391

**Comment by jmason-ebi** [comment]
Closing -- Replaced by ongoing viability discussion which will replace this ticket
