### ISSUE TITLE
Anatomy pages not formated?

### ISSUE THREAD

**Issue by hughbedo** [mpi2/PhenotypeData#190]
Googling for MGI:5548490 gave me image links to anatomy page https://www.mousephenotype.org/data/anatomy/MA:0001100

It looks like this is not properly formatted.  I guess it is a page that should not be exposed and indexed, or it could be the formatting is broken.  This also has links to the ontology browser, which may have the same issuse https://www.mousephenotype.org/data/ontologyBrowser?termId=MA:0001100

**Comment by jwgwarren** [comment]
Thanks - I’ve removed these for the next web release!
