### ISSUE TITLE
Late Adult landing page heat map implementation

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#196]
Acceptance criteria:

- [x] Remove the sorting
- [x] Gene vs. Procedure
- [x] Remove the zoom
- [x] Remove the filter by procedure
- [x] Show counts for rows update them
- [x] Fix the overlay bug
- [x] Froze the column header
- [x] Gene vs. Procedure
  - [x] Click action on the procedure view: click goes to the gene page all data table filtered by procedure name and life stage
  - [x] Click action on the parameter view: click goes to the gene page all data table filtered by parameter name and life stage

**Comment by viomunoz** [comment]
Related ticket: [#170](https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/170)

**Comment by viomunoz** [comment]
I have added the required text to the landing page. Please revise for clarity, typos, etc.

**Comment by jmason-ebi** [comment]
Is this deployed to the live WP site?

**Comment by jmason-ebi** [comment]
Found a bit of a strange issue, see gene Bdkrb1
https://wwwdev.ebi.ac.uk/mi/impc/dev/phenotype-archive/genes/MGI:88144

This gene in the heatmap shows it has significant data for the Gross Pathology procedure, but clicking through, yields the table filtered correctly, but no indication as to what parameter is significant.  And indeed on the significant phenotypes table, there is nothing significant for any anatomy.

Is this a data issue?

**Comment by jmason-ebi** [comment]
Now that I look at it, It seems that whenever there is data for the Gross Pathology procedure, it's significant.
