### ISSUE TITLE
Registration of interest style issues

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#205]
* Follow button: Add '+' icon before follow and then change stop following to unfollow and change the icon to '-'.  I think people are engaged enough with social media to make this connection plus the icons are immediately recognisable which can help with assumption of functionality (quicker than reading a word) plus toggling the icons means you won't have to add another word which makes the button wider
* Orange headers: The h2 elements for these pages can go in the orange headers to help consistency across the site
* Padding at the bottom of the container: The showing entries text is a bit cramped at the bottom
* Setting password: I think it was this page, when I was creating the account/ setting password, there was no space between the newsletter container and content container (edited)

**Comment by mrelac-ebi** [comment]
These changes are complete and committed to the master branch.
