### ISSUE TITLE
Embryo data labelled "Flow cytometry"?

### ISSUE THREAD

**Issue by hughbedo** [mpi2/PhenotypeData#208]
I am looking at gene [Ddx39](https://www.mousephenotype.org/data/genes/MGI:1915528) and it has 5 embryo results, embryo size, placenta size and placenta vasculature.  When you click on the data for these, the chart is labelled "Flow cytometry results", eg. [embryo size](https://www.mousephenotype.org/data/charts?accession=MGI:1915528&allele_accession_id=MGI:5692684&zygosity=heterozygote&parameter_stable_id=IMPC_GEP_022_001&pipeline_stable_id=BCM_001&phenotyping_center=BCM).

**Comment by jmason-ebi** [comment]
Resolve with portal release v3.2.9
