### ISSUE TITLE
Gene page SEO improvements

### ISSUE THREAD

**Issue by amccoy95** [mpi2/PhenotypeData#216]
Averaging 3rd page / 31st place on Google for plain gene name searches e.g. ‘nxn’
Key word plugging? Top result ‘nxn gene’ appears 114 times, we have 17 just for ‘nxn’

- AI: Go through gene pages and run SEO test etc. - feedback to EBI - @amccoy95 

- AI: Gene symbol to be in the URL - @jeremymason @ficolo 
    - Redirect to MGI page
    - Title e.g "NXN Gene | IMPC - International Mouse Phenotyping Consortium"

**Comment by amccoy95** [comment]
@tkonopka has brought up a good point that if you search in Google for "ABC gene" you get some results that are human-focused resources which will be harder to compete with for front page real estate. 

Instead we should target the phrase "ABC mouse" or "ABC gene mouse" etc. 

Any of the changes we made should improve our rankings for "ABC gene" but as Tomasz has mentioned it will be unrealistic to aim for the front page.

**Comment by amccoy95** [comment]
Also on a side note relating to the gene URL changes, @jeremymason mentioned that Dave Clary, or someone owns the impc.org domain name? Can we get in touch so we can gain ownership

**Comment by amccoy95** [comment]
A couple of starting points would be to look into adding a dataset schema in the form of json-ld in a script tag in either the head or body of the page. More info here: https://developers.google.com/search/docs/data-types/dataset

I've also taken an audit of a random gene page. This can be done by opening dev tools on chrome > audits tab > run audit. I've ran audits on mobile and desktop and throttled CPU. Progressive web app was disabled but could be something to look into in the future

[Gene_Page_Audit_Lighthouse.pdf](https://github.com/mpi2/PhenotypeData/files/3921121/Gene_Page_Audit_Lighthouse.pdf)

**Comment by amccoy95** [comment]
Just be looking into this again. Some things that can be quick and easy fixes:

- Add meta descriptions to the gene page. E.g. "Phenotype data for mouse gene {{gene_name}}. Discover {{gene_name}}'s significant phenotypes, expressions and more. Data for gene {{gene_name}} is all available for download." - These need to be around 100-320 characters including spaces.

- Add alt tags to images and title tags to links. These are needed for accessibility and screen readers. 

- Amend gene page title to target out key search phrases. E.g. "{{gene_name}} Mouse Gene Details | {{gene_full_name}} | IMPC ". These need to be around 60 characters including spaces

- Add canonical URLs  <link rel="canonical" href="https://www.mousephenotype.org/data/{{MGI_ID}}">. Add this to dev and beta pages too

- Add a h1 tag to the page. This should be the page title. So the text in the orange bar at the top. This may need some styles to make it fit the orange container.

- Have heirarchy of heading elements set. Section titles e.g. Expression should be a h2 element and the nested headings in the sections should be a h3. Again further styles maybe added for better layout. 
    -  Just a side note on this: the follow button and help icon shouldn't be wrapped in a h2 element. If the icon needs to be larger use the font-awesome sizing utilities. e.g. fa-3x.

**Comment by amccoy95** [comment]
The main one that is not so quick or easy is page speed. As google has be measuring in a mobile first manner due to the popularity of smart phones, they now use page load speed to determin SERP placement. 

This is going to be a big job because of the mass of data we're putting onto the page. This will need a bit of planning.

An easy thing we can do is defer non-important scripts and files on page load to eliminate render blocking.  We're using a couple of plugins for tables and graphs, but these don't appear above the fold so these and the relating custom scripts to go with them can be deferred with the `async` html attribute

**Comment by amccoy95** [comment]
After checking Google Search Console for our May stats, they've added a new feature called "Core Web Vitals". It shows what pages are "fit" for display on their SERPs and the biggest thing is page speed. 

If the URL is marked as having an error, it won't compete with other pages that are passing their tested. We have 163 pages (all gene pages) that are marked as having errors. 

The errors are LCP issue: longer than 4 s (desktop), CLS issue: more than 0.25 (desktop), and LCP issue: longer than 4 s (mobile).

To find out what the errors mean you can find out here: https://support.google.com/webmasters/answer/9205520?ref_topic=7440006#about_data

**Comment by jmason-ebi** [comment]
Made the following SEO improvements to the gene details page:
* Added bioschemas section
* Deferred loading of some JavaScript to decrease time to first paint
* Added meta tags for the description according to the advice above
* Adjusted the names of the gene pages according to the advice above
* Added canonical URLs
* Restructured the markup to be more hierarchical
* Changed markup around the help icon and the login button

The changes between live and dev according to the google audit looked better:
LIVE:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/a77c6c50-9a45-4ad0-82c0-96d7dc684e65)

DEV:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/1a4f7b0c-85ae-445f-9e2d-77ed1c32df33)

**Comment by jmason-ebi** [comment]
For any additional SEO activity, let's create a new ticket.
