### ISSUE TITLE
Missing statistical result section on the reference range plus statistics chart pages

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#225]
The chart pages should have a section under the plots showing the p-value and other information.  These sections are missing on plots where the statistics used were the RR+ method.

See: https://www.mousephenotype.org/data/charts?accession=MGI:1891704&allele_accession_id=MGI:4887599&zygosity=homozygote&parameter_stable_id=MGP_PBI_034_001&pipeline_stable_id=SLM_001

![Screenshot_2020-01-09 B cell number (MGP_PBI_034_001) chart for Hbs1l International Mouse Phenotyping Consortium](https://user-images.githubusercontent.com/1931551/72076588-a2e86a80-32ed-11ea-8e05-0e8daa3bc2d0.png)

To see an example of what it should be like, look here: https://www.mousephenotype.org/data/charts?accession=MGI:1891704&allele_accession_id=MGI:4887599&zygosity=homozygote&parameter_stable_id=IMPC_CBC_015_001&pipeline_stable_id=MGP_001&phenotyping_center=WTSI

**Comment by jwgwarren** [comment]
Parked fixing this at the moment as data issues seem to make debuging difficult. maybe after latest release is pushed things will be more consistent.
