### ISSUE TITLE
Make histopath landing page available from links/menu on website - where???

### ISSUE THREAD

**Issue by jwgwarren** [mpi2/PhenotypeData#228]

**Comment by viomunoz** [comment]
Working on this. See ticket [#242]([url](https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/242))

**Comment by jmason-ebi** [comment]
The histoath page is located here:

http://www.ebi.ac.uk/mi/impc/phenotype-archive/landing_pages/histopath

And should be linked to from the DATA menu under the "Data Focus" section

**Comment by amccoy95** [comment]
Do we have a mousephenotype version of the URL?

**Comment by jmason-ebi** [comment]
https://www.mousephenotype.org/data/landing_pages/histopath

**Comment by amccoy95** [comment]
Link has now been added to the Data menu under Data Focus. 

This submenu is currently sorted alphabetically. Any further ordering let me know. 

I think this submenu has the maximum of items we want in one dropdown. I will add a view more link.

**Comment by jmason-ebi** [comment]
Reviewed and is working!  Thanks
