### ISSUE TITLE
Fix styling on the /data pages to make them look like the ones on the CMS system

### ISSUE THREAD

**Issue by jwgwarren** [mpi2/PhenotypeData#229]
I've tried and failed to fix this. Federico maybe able to help?

**Comment by jwgwarren** [comment]
https://www.mousephenotype.org/data/embryo_heatmap

**Comment by ficolo** [comment]
All of the Landing pages have some style issues, I'll be trying to fix them all together unifying the JSP tag and applying the wordpress CSS.

**Comment by jmason-ebi** [comment]
This is finished?

**Comment by ficolo** [comment]
It is done
