### ISSUE TITLE
Add lifestage column to genotype-phenotype reports in FTP site

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#230]
Column lifestage is needed in FTP genotype-phenotype reports here: 
ftp://ftp.ebi.ac.uk/pub/databases/impc/release-10.1/csv/ 
starting from DR 11.0.

Otherwise users need to filter by procedures.

**Comment by jmason-ebi** [comment]
Added appropriate fields to the data base schema

**Comment by jmason-ebi** [comment]
This is done already -- the field used to contain the developmental stage of the specimen as reported in the XML file, but has been updated to reflect the life stage of the specimen when the procedure was performed.
