### ISSUE TITLE
Changes to and release of the new Embryo Viewer

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#241]
Here is the link to the Embryo Viewer:
https://wwwdev.ebi.ac.uk/mi/impc/beta/phenotype-archive/embryo_heatmap

Requirements:
Make some changes to the Embryo Heatmap and release to subsitute the Embryo Viewer currently under "Advanced Tools", which is static and was meant only as a temporal solution until a heatmap was in place.

Proposed changes:
1.- The title, "Embryo data for every gene tested", may be misleading. What about changing it to "Embryo data for every lethal gene"? The KO lines that enter the embryo phenotype are those that have a lethal (and subviable?) phenotype in the IMPC viability procedure, so thus not "every gene".

2.- Do we need "No data" and "Not applicable" in the legend? What does "Not applicable" mean? We may need explanations for these – or can these be removed?

3.- "Legend" rather than "Signficance score"? We are indicating image presence/absence in the heatmap.

4.- As images is quite a vague term, good to state somewhere on the page that "Images were acquired by the micro-CT and OPT procedures".

5.- Headers in table:    E9.5    E14.5-E15.5    E18.5    UMASS,

could be changed to: OPT E9.5     MicroCT E14.5-E15.5     MicroCT E18.5    UMASS
so they are more meaningful.
They could also be clickable with links to the protocols:
https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=833&pipeID=7
https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=839&pipeID=7
https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=845&pipeID=7
http://blogs.umass.edu/jmager/

**Comment by jwgwarren** [comment]
Cant change to clickable headers as they are used for sorting currently.

**Comment by jwgwarren** [comment]
I've done most of the changes suggested. If Henrik or Terry or someone wants to add more text about UMASS or the procedrues in general I'll happily add it. But I think as a first iteration of this page it's done.
