### ISSUE TITLE
Changes to the IMPC website menu, DATA section

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#242]
As we have been already discussing before, the Research Highlights section is currently a mix of statitc and dynamic pages and, from the users point of view, is difficult to understand what to expect when accessing this section. In addition, this section is getting too long.

Proposal:

- Make two sections out of "Research highligts".

- One section can be called the same, "Research Highlights", and be placed under the menu "Publications". In this section we can include landing pages with static content focusing on papers. Title for each section can be more catchy, to attract the users' attention and interest, focusing on the main message/discovery the landing page is conveying; for example, "Novel hearing loss genes" instead of "Hearing". Current landing pages that could be included in this section are: "Sexual dimorphism", "Hearing", "Metabolism" (could be titled, e.g. "Genetic basis for metabolic diseases" or "Metabolic disease genes") and "Translating to other species". May be also the "Embryo vignettes" page, if that one is going to remain statitc. This page needs an Intro and I am happy to write it and mention the Embryo paper (Nature 2016) here.

- Create a section for the landing pages with dynamic content and that offer a particular view (a subset) of the data. We need a decision as to pages and purpose. The name for this section would depend on this. In this section we may include the following pages: Embryo, Cardiovascular, Pain, Late Adult Data, Histopath heatmap. A name for this section has been proposed: "Data Focus".

A mockup is available:

![data-menu](https://user-images.githubusercontent.com/29598654/72748185-731f4980-3bae-11ea-8631-e19f98739745.jpg)

**Comment by viomunoz** [comment]
Latest decisions for the Publications section:

1. Publications menu

Have 3 items under the Publications menu:

- Latest IMPC Papers (this item will be furthest to the left)

- Data supporting IMPC papers (the static landing pages -- or any other better name)

- Papers using IMPC resources (links to our standard Publication page with the two tabs)

2. "Latest IMPC Papers" page

Based on template for https://www.mousephenotype.org/understand/publications/impc-papers/

This page will include any item from the News or Blog (that is, independent of whether it is news or posts), that mentions an IMPC paper. Post are chronologically ordered, most recent first. We can limit to 6 items per page and include pagination. Number of items to display per page can be easily changed at a later stage if we feel more items should be listed.

**Comment by jmason-ebi** [comment]
Menu order on data focus section is being looked at by Aaron.  Will auto update when the underlying menu API is changed.  Closing
