### ISSUE TITLE
Improvements to the content of the Embryo Vignettes page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#252]
As we are now revisiting landing pages styling as well as location within the homepage, the time is right to make improvements to the content.

The Embryo Vignettes page https://www.mousephenotype.org/data/embryo/vignettes has no introduction. 

Requirements:

1) Write an introductory text and provide context
2) Update Embryo Vignettes page with the new content.

**Comment by henrik-impc** [comment]
Hi Violeta,

I am updating links and getting new content from the centres. Hopefully be done in a couple of weeks. I can do the introduction too if you want?

bye,
Henrik

**Comment by jmason-ebi** [comment]
The content can be supplied directly to @amccoy95 for adding / editing the page directly.  For reference, here's the page with the content:
https://github.com/mpi2/PhenotypeData/blob/master/web/src/main/webapp/WEB-INF/views/embryo.jsp
On the master branch.

**Comment by ficolo** [comment]
Changes in #256

**Comment by viomunoz** [comment]
Henrik took care of this and changes have been made.
