### ISSUE TITLE
Data Release 11.0

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#254]
Resolve Load process errors in Jenkins job DataRelease_load.

Acceptance criteria:
This task is complete when all of the errors from the Jenkins job DataReleaseLoad have been either resolved or determined that it's OK not to load the data that failed.

**Comment by jmason-ebi** [comment]
Currently on DEV site.  The disease cores should be being generated by QMUL and when that is complete, we will push to beta and staging.
