### ISSUE TITLE
Gene Page: add "Background strain" column to All Data table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#266]
A user realised s/he could not find "Background strain" in All Data table.

**Requirement:** 
Add a column with "Background strain" to All Data table in Gene page.

**Comment by jmason-ebi** [comment]
This information will be available via the download functionality see issue #267

**Comment by viomunoz** [comment]
To be implemented as part of [Gene page: provide functionality to download all data associated with a gene ("All data" table) #173](Gene page: provide functionality to download all data associated with a gene ("All data" table))

**Comment by viomunoz** [comment]
Solution to be implemented as indicated in ticket #325. This ticket can be closed.
