### ISSUE TITLE
Gene Page: split the "Procedure / Parameter" and "Mutants" columns in All Data table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#267]
**Feedback from the group:**
Would be helpful to have the following split in 2 columns to enable sorting and filtering, also when downloaded:
1. Procedure / Parameter column: Procedure and Parameter 
2. Mutants column: Male mutants and Female mutants

Example:
https://www.mousephenotype.org/data/genes/MGI:99602#phenotypesTab

![Screenshot 2020-02-10 at 12.02.50.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/14dd6b41-91c5-4ad8-83cf-ebb6f6771951)

**Comment by jmason-ebi** [comment]
We need to be caredul about adding more columns as the table is a fixed size and the addition may require us to remove columns to maintain visual consistency.  A form of Filtering is available from the search box already, and we could/should enable a download option whixh includes more detail/columns for advanced filtering requirements.On Feb 10, 2020 12:03 PM, viomunoz <notifications@github.com> wrote:Feedback from the group:
Would be helpful to have the following split in 2 columns to enable sorting and filtering, also when downloaded:
Procedure / Parameter column: Procedure and ParameterMutants column: Male mutants and Female mutants
Example:
https://www.mousephenotype.org/data/genes/MGI:99602#phenotypesTab

**Comment by viomunoz** [comment]
That is a good idea. We can implement it in the download option. A ticket is in place to enable the download option.

**Comment by viomunoz** [comment]
[Gene page: provide functionality to download all data associated with a gene ("All data" table) #173](https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/173)

**Comment by viomunoz** [comment]
Solution to be implemented as indicated in ticket #325. This ticket can be closed.
