### ISSUE TITLE
ObservationServiceTests now failing as of DR11.0

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#270]
After installing DR11.0, 3 of the 4 ObservationServiceTests fail. @mrelac-ebi  has @Ignored the tests for the moment because the test failure blocks the build.

**To Reproduce**
1. Remove the @Ignore annotation.
2. Run the ObservationServiceTest

**Expected behavior**
All the tests should pass.

**Comment by jmason-ebi** [comment]
Issue is related to missing data, not the fault of the tests.
