### ISSUE TITLE
Report for IDG TDark genes

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#274]
As a user, I would like to get a list of genes that were TDark when the KO project started so I can show the progress toward the goal of illuminating dark genes. IDG can do this analysis but needs the human gene symbol and the start date for the KO project.

Can you:
1. Get the current set of genes with phenotype data
2. Get the earliest start dates (MI or electroporation) for those genes
3. Filter for those with 1:1 mouse human orthologs
4. Provide a report of:

* Mouse symbol
* Mouse Acc ID
* Human gene symbol
* First MI date

**Comment by viomunoz** [comment]
Orthologue list is ready to integrate with (1) and (2) as soon as those are ready.
