### ISSUE TITLE
Complete Publication navigation item integration

### ISSUE THREAD

**Issue by amccoy95** [mpi2/PhenotypeData#278]
The publications navigation and dropdown menu has been added to the WordPress site and the Data Portal is now pulling the new navigation items. 

![image](https://user-images.githubusercontent.com/46707334/74656239-a6d99900-5185-11ea-904f-55caf8db3677.png)

There are currently a couple of issues that are preventing the new nav item to display correctly:

- No menu-item ID on `<li>` tag preventing from colour border displaying. Suggestion: I've added class names as well as post ids to the menu json. These class names have been added to the CSS styles. I recommend using class names incase of page changes in furture, this can then be handle on WP and there'll be no need to change any code.
- No dropdown container html for the publication links to go into. There is how ever a news dropdown container. Just rename this as the news one is no longer being used.
- Add hover events into the buffaloZoo.js file.:

```$("#menu-main-nav .publications, #publications-menu").mouseenter(function () {
        $("#publications-menu").stop().slideDown()
        $('#menu-main-nav .publications a').addClass('active');
    });

    $("#menu-main-nav .publications, #publications-menu").mouseleave(function () {
        $("#publications-menu").stop().slideUp()
        $('#menu-main-nav .publications a').removeClass('active');
    });

    var pubOpen = false;
    $("#menu-main-nav .publications a").on('touchstart', function (e) {
        if (!pubOpen) {
            $("#publications-menu").stop().slideDown()
            $('#menu-main-nav .publications a').addClass('active');
            pubOpen = true;
        }
        else {
            $("#publications-menu").stop().slideUp()
            $('#menu-main-nav .publications a').removeClass('active');
            pubOpen = false;
        }
        e.preventDefault();
    });
```
This uses the classname suggestion from above.

**Comment by jmason-ebi** [comment]
The menu issues have been resolved on commit d02cea2a
