### ISSUE TITLE
Broken link in Embryo Vignettes page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#279]
In this page: https://www.mousephenotype.org/data/embryo/vignettes
at the end of the first paragraph, **IMPC 3D Embryo Data**, should point to:
https://www.mousephenotype.org/data/embryo_heatmap

**Comment by henrik-impc** [comment]
Ok I will fix this when I get the next set of vignettes from the centres, seems to redirect to the correct page.

thanks
