### ISSUE TITLE
Display of the late adult data on the gene page

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#280]
We will need to decide how to display the late adult data on the gene page.

**Comment by viomunoz** [comment]
Apart from a dedicated LA data heatmap, we need to display available LA data in Gene Page:
(1) Indicate that LA data is available, with a link to the heatmap
(2) Presence of hits - do we want to have a LA displayable phenogrid?

Some mockups here to get meeting started:

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/2be484ba-2e6f-4292-a978-957c2b590c52)

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/00f94640-6836-4283-a5fc-df30ec2fc69d)

**Comment by viomunoz** [comment]
**Meeting results**

**Requirements for Adult Data display in Gene Page:**

1. "Embryo Screen" will be changed to "Embryo Viewer"

2. Add a "Late Adult" entry below "Embryo Viewer", redirects to the Heatmap filtered for that gene

3. Add filters to "Signifcant Phenotypes" and "All data" tables for life stage, only when there is data for more than one life stage: All/Embryo /Early Adult/Late Adult
