### ISSUE TITLE
More broken links: IMPRESS homepage

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#290]
In this page:
https://www.mousephenotype.org/impress

1. By clicking "The IMPC (International Mouse Phenotyping Consortium) core pipeline" you get redirected to the homepage, rather than to the pipelines:

https://www.mousephenotype.org/impress/pipelines
 
2. The link to EMPReSS does not work: the page keeps trying to load.

**Comment by amccoy95** [comment]
Issue now created on Impress's github. http://phobos/DCC/DCC-Devs/Impress-Web/issues/61 

We're going to remove the link as Empress is no longer needed as the majourity of items are now loaded in Impress. The text will stay the same

**Comment by amccoy95** [comment]
For point 1, this is the correct functionality. If it was to the core pipeline the words "core pipeline" will be hyperlinked.

**Comment by viomunoz** [comment]
For point 1, do we prefer highlighting "core pipeline" and linking those, rather than the home page?

**Comment by viomunoz** [comment]
Closing this issue as it is being dealt by the DCC.
