### ISSUE TITLE
Adding the ageing pipeline (LA procedures) to the IMPRESS homepage figure

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#291]
Here https://www.mousephenotype.org/impress the figure is missing the LA procedures.

Harwell and EBI discussed internally, considering:

1.- Adding a third line / row to the figure, as it is currently incomplete. See section "IMPC Ageing" from the picture below, which will need modification (style, accuracy, completeness).

2.- Make the figure more dynamic and interactive. During the UX testing, users did not realise procedures were clickable (currently only the pointer changes when you hover over them and this is easy to miss).

3.- Update the tests colour-coded light blue, “Tests in development or under consideration”.

---

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/711032e1-c073-4061-84f0-ad41c8622cfe)

**Comment by amccoy95** [comment]
This item has an issue creating on the IMPReSS github: http://phobos/DCC/DCC-Devs/Impress-Web/issues/59

**Comment by jmason-ebi** [comment]
The DCC is tracking this internally.
