### ISSUE TITLE
Legacy images broken links bug

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#297]
Some gene detail pages indicate that there should be images associated, but the image links are broken.

The gene is:
https://www.mousephenotype.org/data/genes/MGI:1921409

See screenshot:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/32ac64cd-55b0-48d5-9496-632258918ab7)

See SOLR output for one of the missing images:
https://www.ebi.ac.uk/mi/impc/solr/images/select?q=smallThumbnailFilePath:*I20150706095507_download_tn_small.jpg*

**Comment by jmason-ebi** [comment]
Any update on these broken image links?

**Comment by jwgwarren** [comment]
These images either don't exist or the import of data from Sanger was done without an import of the images. We used to have python scripts in SVN to get the images and to move them from dev to live but they no longer exist as they were decomissioned as we were freezing this data.

**Comment by jwgwarren** [comment]
it's also odd that just for the xray section the number is wrong there are only about 24 images not 72

**Comment by jwgwarren** [comment]
Sanger images can be downloaded from urls like this https://img1.sanger.ac.uk/images/520/M00379015_00012839_download_full.jpg

**Comment by jwgwarren** [comment]
so the first image missing is this https://img1.sanger.ac.uk/images//0/I20150706095557_download_tn_large.jpg

Which does indeed exist on their system just not on ours!

**Comment by jwgwarren** [comment]
Kola is writing a script to check and download any missing images from the above formatted urls

**Comment by jmason-ebi** [comment]
Kola reports this is done
