### ISSUE TITLE
Display Life Stage in chart pages

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#300]
**Requirement:**
Life Stage needs to be added to our chart pages in a clear conspicuous way on the top of the page. 
For the team to decide where to put it.

**Comment by jmason-ebi** [comment]
This is done as part of the fixes for the charts #303 :

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/841bc17d- b089-4be8-a3fc-dc3c9f0efb9f)

**Comment by jmason-ebi** [comment]
Need to create a new story to run this periodically and report the results
