### ISSUE TITLE
Chart pages: incorrect display of eye phenotypes (duplication of results)

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#301]
Requirements:

There are a number of issues that need to be fixed.
All columns in the bar chart and raw data table have been duplicated. It looks like this caused the mislabeled columns in the bar chart.

Note none of the links to IMPReSS in the table on the top right work (see separate ticket for this #302).

https://www.mousephenotype.org/data/charts?accession=MGI:103097&allele_accession_id=MGI:5825199&zygosity=heterozygote&parameter_stable_id=JAXLA_EYE_016_001&pipeline_stable_id=JAXLA_001&phenotyping_center=JAX

![Screenshot 2020-03-09 at 15.51.47.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/59f5e5d1-4193-4356-b7c9-3595d6a9af43)

**Comment by jmason-ebi** [comment]
This was due to the pipeline core not indexing correctly the new impress schema.  This is resolved with commit 4fcbb0a: https://github.com/mpi2/PhenotypeData/commit/4fcbb0a8643e9eb7bd58f47d142139d32eebadf1

**Comment by jmason-ebi** [comment]
New page only reports expected categories:

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/67468bc8-7afd-4371-bc0a-388dad5d28f2)
