### ISSUE TITLE
Links to IMPReSS in the table on the top right work need fixing

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#302]
**Requirements:**

Links to IMPReSS in the table on the top right work need fixing.

Example: https://www.mousephenotype.org/data/charts?accession=MGI:103097&allele_accession_id=MGI:5825199&zygosity=heterozygote&parameter_stable_id=JAXLA_ECG_014_001&pipeline_stable_id=JAXLA_001&phenotyping_center=JAX

**Comment by jmason-ebi** [comment]
Fixed with release 3.4.3
