### ISSUE TITLE
Combined lifestage chart display 

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#304]
With the addition of the late adult data to the portal, it's now difficult to compare early to late results.  As a user I want to be able to see if there is any data for other life stages for the parameter I'm currently viewing.

UPDATE (20200319):
Decided to combine the charts to include both the late and early in the same plot

**Mockups**
Boxplot
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/8ea93a16-2dd0-4621-981e-3397e07fd583)
* Box plots will be ordered by 
  * Life Stage
  * Sex
  * I.e., Early Adult Female, Late Adult Female
* Within these columns the colors will indicate mutant vs control

Scatterplot
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/bad4b77d-e1ba-4b46-af0f-fe1e0262d4d6)
* Agreed to try separated scatter plots by life stage
* Stacked plots with the same x axis (and y-axis if possible)

Tables:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/a730368d-95d0-4573-bbd7-fb0895054bbe)

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/5ca502c1-8935-4d20-ac85-58885eb4779b)

Acceptance Criteria:

- [ ] Combined box plot displays
- [ ] Stacked scatter  plot  displays
- [ ] Combined tables are displayed

**Comment by jmason-ebi** [comment]
Design is to be discussed further tomorrow and/or Wednesday.

**Comment by jmason-ebi** [comment]
Made a few more example charts for the DAWG call as examples:

Early and Late adult data:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/05e429ff-6ee0-43cf-8693-8f55d4aa1ca3)

Early, Intervening and Late data:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/7235c909-5e5b-420c-af6d-3410a4096ca2)

**Comment by jmason-ebi** [comment]
Questions 
1) Should be be putting together things that have different metadata groups?
2) Life stages different.  Per life stage, how do we show
2.a) Experimental conditions
2.b) Procedure links
2.c) Statistical results

There is quite a bit of uncertainty still and so the next step is to schedule a meeting to get more requirements nailed down.

**Comment by viomunoz** [comment]
This text summarises this ticket https://docs.google.com/document/d/1RdnzbMZczxN02Ps64Ne0mgK3DApchYXYTEg-qxfObPo/edit#heading=h.lc0day8p8fds
We will have a meeting to answer remaining questions and propose AIs.
