### ISSUE TITLE
Unexpected behaviour in All data table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#306]
**Example:** https://www.mousephenotype.org/data/genes/MGI:1096391

![Screenshot 2020-03-09 at 21.14.40.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/e2527115-8453-4b93-bacb-1d7beba6ac6a)

**Requirements:**
1.- The underlying data should be shown when clicking anywhere in the table; currently, the user needs to click on the p-value and this is unexpected and easy to miss.
2.- After visiting the underlying data, user should be return to the All data table when pressing the browser's back button, with filtering options maintained; currently, the user is returned to the Significant phenotypes table or, if no significant phenotypes, to the Measurements chart, and all filtering is lost.

**Comment by jmason-ebi** [comment]
With the release of the all data table fix (see issue #234), this has also bee resolved.
1) The whole row is clickable
2) The behavior is now opening charts in a new tab so as to not lose configured filters
