### ISSUE TITLE
Documentation: decide whether to keep the Statistics to Phenotye figure 

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#307]
This figure, in the [old help pages](https://www.mousephenotype.org/data/documentation/statistics-help):

---
![Screenshot 2020-03-09 at 21.27.02.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/91246fa7-da01-4abf-b2fd-0dc20631617f) 
---

could be added to [new help pages] (https://www.mousephenotype.org/help/data-analysis/from-parameter-to-phenotype/)

**Comment by jmason-ebi** [comment]
We kept it, available here: https://www.mousephenotype.org/help/data-analysis/statistical-analysis/
