### ISSUE TITLE
Machine learning applied to mouse x-ray images paper

### ISSUE THREAD

**Issue by kbab** [mpi2/PhenotypeData#309]
Following on from the initial work on investigating sex differences with deep learning networks we want to submit a publication on this work.

Firstly, we need to discuss the remit that we will cover and agree on a publication to submit the work to.

Secondly, we need to identify and carry out any outstanding work

Thirdly, we need to re-write the paper and include a more comprehensive analysis of the results

**Comment by rwilson-ebi** [comment]
Closed as Kola has left the project
