### ISSUE TITLE
Redirect the old release page links to the new previous release pages

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#314]
The previous release page links are in the format like:

https://www.mousephenotype.org/data/release_notes/IMPC_Release_Notes_9.1.html

And need to redirect to the new release pages, with links like:

https://www.mousephenotype.org/data/previous-releases/9.1
Also filter urls with non-existent releases, and filter urls with current release like:
https://www.mousephenotype.org/data/previous-releases/11111.111
https://www.mousephenotype.org/data/previous-releases/11.0

**Comment by mrelac-ebi** [comment]
Tested and deployed to live. Redirection now works, and redirect requests to previous-requests that are either the current release or releases that don't exist now display the 'We're Sorry' page.
