### ISSUE TITLE
Batch Query design

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#317]
We agree internally that we will provide a single Batch Query functionality that also accommodates the Essential Genes requirements.

Requirements document here:
https://docs.google.com/document/d/1uveWn1H6nDv8hES0mgIOgelFVzHi2xwid3RljFvyHFE/edit#

**Comment by viomunoz** [comment]
Design proposal:

![Screenshot 2020-03-12 at 16.31.45.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3056f08a-ff49-4da1-affc-cffd492f84bc)

**Comment by jmason-ebi** [comment]
Discussion with @viomunoz and examined the output from:
https://www.gentar.org/refdata/console
To see if applicable.  We looked at a query like:
`query MyQuery {
  ortholog(limit: 10, where: {support_count: {_gt: "6"}}) {
    human_gene {
      id
      name
      symbol
    }
    support_count
    support
    mouse_gene {
      symbol
      name
      id
    }
  }
}
`
and it seemed to provide enough information the get started.

**Comment by viomunoz** [comment]
This ticket is now replaced by tickets #353 and #354.
