### ISSUE TITLE
Create state machine for Project Assignment

### ISSUE THREAD

**Issue by mauroz77** [mpi2/PhenotypeData#320]
Create state machine for Project Assignment.

- Clean the current statuses.
- Check the needed logic.
- Define the state machine.

**Comment by albags** [comment]
I prepare a document translating the transitions in iMits to GenTaR transitions:

https://docs.google.com/document/d/1-SDDD5h3SuNYAzmmWM1s8skOLhwpznvMWT3wCHUyHDY/edit
