### ISSUE TITLE
All data table: embryo data display split over many rows

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#322]
Example:
https://www.mousephenotype.org/data/genes/MGI:1096391?dataLifeStage=embryo

![Screenshot 2020-03-13 at 10.53.33.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/a58028ed-acfa-4850-9104-0c9ff9e1214c)

**Comment by jwgwarren** [comment]
So they are all different parameters so will be displayed on separate rows but there are no numbers for male or female which is odd???

**Comment by henrik-impc** [comment]
Its line level so there wouldn't by any males and females,
bye,
Henrik

Dr Henrik Westerberg, Head of Bioimage Informatics
MRC Harwell Institute, BioComputing, Harwell Campus, Oxfordshire, OX11 0RD, UK.
Tel: +44 (0)1235 841234 | www.har.mrc.ac.uk


________________________________

**Comment by viomunoz** [comment]
We need to discuss internally how to best display results using the All data table.

**Comment by viomunoz** [comment]
Solution to be implemented as indicated in ticket #325. This ticket can be closed.
