### ISSUE TITLE
Investigate why some non-daily-built cores do not build cleanly

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#323]
For some time the pipeline, experiment, and statistical-result cores have been throwing warnings regarding expected document count (i.e. the number of documents actually written) vs the number of documents that solr reports for the same cores. @jmason-ebi  and @mrelac-ebi  believe that the number of documents written is correct, so the warning doesn't indicate there is anything wrong with the data being written.
However, these warnings pollute the job results which puts us at risk of missing real warnings/errors. This ticket aims to discover and fix the source of the warnings.

**Comment by mrelac-ebi** [comment]
Started.

**Comment by jmason-ebi** [comment]
This should be enough to uniquely identify each entry as required by the pages which link to IMPReSS.  So is this ready for review now ?

**Comment by jmason-ebi** [comment]
Mike has completed this and pushed clean builds to live.
