### ISSUE TITLE
Requirements for All Data table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#325]
Start a document to discuss internally requirements for the All Data table results display.

**Comment by jwgwarren** [comment]
We should discuss this today?

**Comment by viomunoz** [comment]
**All Data table – points to get conversation going / started**

See some screenshots at the end of this document.

**How can we best communicate a significant vs a non-significant result?**

- Do we think the “P-value” column can fulfil the role of the “Status” column? (We have been discussing there are too many columns in the All Data table – do we think the “Status” column is needed?)
* That is, if a P-value is reported, it means the experiment was successful.
* Likely, we could state in this column “No statistical test for this procedure” / “Sample size insufficient” / Other categories?
- What about including an “MP term” column, stating the MP term when significant, otherwise state “No significant association”? (Might not be straightforward to interpret “P-value: 1” with “Status: Success” or "“P-value: - ” with “Status: Success”; see screenshots).
- How do we communicate the situations in which male significant and female is not and viceversa? Do we need a column (in downloadable file) “Significant sex” with option “Both sexes”, “Male only”, “Female only”?


**Statistical test conducted is relevant** 

- Show in downloadable file?


**Important for users to see sample size (make own assessment of strength of results / evidence)**

- We currently show number of mutant males and females
- When no distinction for a procedure is made between males or females, we still need to show numbers of mutants
- Show number of controls?


**Background strain is important**

- Show only in downloadable file?
- Will users think it is missing if we don’t show it /explicitly say there are additional columns in the downloadable file?


**In downloadable file, might be useful for users to have the following reported in separate columns:**

- Procedure and parameter
- Females and males
- Zygosity

---
![Screenshot 2020-03-18 at 18.46.55.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/810c904d-b120-4947-9177-70c7c689e79f)
---
![Screenshot 2020-03-18 at 18.52.34.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/5b7ff5de-b2d0-44c3-9ace-19d7453732b4)
---
![Screenshot 2020-03-18 at 18.58.20.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/23a62180-ecaa-4d69-848b-2c49e69e284c)

**Comment by viomunoz** [comment]
[Apologies for the indentation, this was the best way I could come up with...]

**Team met and agreed:**


**We should show all parameters**

**What are the columns that we should use in this table?**

1. Allele
2. Center
3. Procedure / Parameter
4. Life stage
5. Zygosity
6. Significant (Significant, Not significant, Unable to process, Supplied)
7. P-value (this is the most significant overall null test p-value)
8. Phenotype (MP term)
8.1. For (adult and embryo) viability records, when not significant, use the word “Viable”
8.2. For fertility records, when not significant, use the word “Fertile”
8.3. When different for male and female, show both comma separated


**On click - depends on data type represented in the row**

1. Images - clicking the row links to the image comparator for that image type
2. Continuous / Categorical
3. Time series
4. Line levels
4.1. Viability
4.2. Fertility
4.3. Embryo viability
4.4. Embryo gross morphology
5. Ontology
5.1. Adult Gross pathology
5.1.1. Working as expected
5.1.2. Row will either be “Not significant” or “Significant”
5.2. Adult Histopathology
5.2.1. Collapse parameters together by tissue
5.2.2. If any “significance score” is set to true for any specimen*tissue, Significant is true
5.2.3. Clicking on the row links to the histopath table filtered for that tissue


**Download link:**

1. Gene
2. Allele
3. Center
4. Pipeline
5. Procedure
6. Parameter
7. Life stage
8. Zygosity
9. Significant (Significant, Not significant, Unable to process, Supplied)
10. P-value
11. Male p-value
12. Female p-value
13. Phenotype male (MP term)
14. Phenotype female (MP term)
15. Background strain
16. Number of mutant males
17. Number of mutant females
18. Total mutant number
19. Number of control males
20. Number of control females
21. Total control number
22. Statistical test
23. Status (Success, Failed - Low N, etc.)
24. Metadata group

**Comment by hughbedo** [comment]
Adding my comments here about the Late adult heatmap -> Gene page link., a little more general than the "All Data Table".

- I think the idea of have a separate  Significant column will solve the problem as is, and will be useful more generally, as it will not require people to compare the displayed p value to the threshold to work out if a row is significant.

- Why do the significant but no p value items not some up on the Significant phenotypes tab?
  - If they did, then the orange cells could go to the Significant phenotypes tab, which may make it more clear what is going on, especially in cases where there are many parameters in a procedure, and the significant one may not be on the 1st page (Clin Chem being an example).

Just my thoughts, it looks really good.

**Comment by viomunoz** [comment]
See ticket Fertility data not visible #62.
When there is no underlying data available: it is probably clearer for the user to get a message displayed "no underlying data available; currently working to retrieve this data" rather than the user being redirected to the sideways manhattan plot / Measurements chart tab, as it currently happens for the fertility data.

**Comment by jmason-ebi** [comment]
Will discuss with NIH UX expert Thursday at 3BST.

**Comment by viomunoz** [comment]
To consider:

1. A button that filters to show **only signifciant** results will most likely be a useful additon -- currently you can filter for physiological systems with significant results, which is useful, but still a lot of data that a user looking for signficant results is not be interested in.
2. A user commented that **pagination** and the wrangling of columns is cumbersome -- consider moving the All Data table to a **new page**.
3. Also it was noticed that the table **doesn't fit horizontally** on the screen (1920x1080, chrome, firefox). A horizontal scrollbar appears, but the table header and the scrollbar are not visible at the same time, so scrolling up and down is required.

**Comment by viomunoz** [comment]
Closed and replaced by tickets #369, #370, #371, #372.
