### ISSUE TITLE
Late Adult heatmap: legend missing

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#330]
A user noted a legend is missing, here:
https://www.mousephenotype.org/understand/data-focus/late-adult-data/

Could add:

Grey: no Late Adult (LA) data
Blue: no significant difference between LA controls and LA knockouts
Orange: significant difference between LA controls and LA knockouts

Please click on a heatmap cell to get redirected to the gene page and see the underlying data.

**Comment by ficolo** [comment]
Added a loading indicator as well.

**Comment by ficolo** [comment]
Also optimised the loading time, should be 80% less than before.
