### ISSUE TITLE
Add COVID message to order section

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#333]
On the gene page, we need a message near the order section:

This service may be affected by the Covid-19 pandemic. See how

with the "See how" linking to the IMPC blog post https://www.mousephenotype.org/news/impc-covid-19-update/

**Comment by jwgwarren** [comment]
This is done and in master now
<img width="1355" alt="Screenshot 2020-04-17 at 10 55 03" src="https://user-images.githubusercontent.com/1829853/79557298-3a521c00-809a-11ea-9f33-f300d404a6d9.png">

**Comment by jmason-ebi** [comment]
Is this done?
