### ISSUE TITLE
Embryo icon in Phenogrid does not highlight, but there is Embryo data in All Data table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#336]
**Description:**
Embryo icon in Phenogrid does not highlight, indicating not tested / no data.
But All data table shows there is Embryo data.

**Example**: [Nrxn1](https://www.mousephenotype.org/data/genes/MGI:1096391)
E12.5 and E18.5 data avalaible.

**Requirements:**
Embryo icon should indicate there is data, either orange (if any data significant) or blue.
(Note there is a ticket addressing All Data Table display issues #325)

![Screenshot 2020-04-03 at 12.17.41.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/f82cd7ad-7573-4114-b871-5b7dc8bb1289)

**Comment by jwgwarren** [comment]
The grid is powered by the significant phenotypes table which uses different methods and the GP core to get it's data. The all data table now uses the experiment core as well as the Statistical Results core for data. So it's likely due to that or the way viability data is obtained and treated as in the all data table the p value is N/A????

**Comment by jwgwarren** [comment]
from observation core:

CombinedObservationKey(alleleSymbol=Nrxn1<tm1b(KOMP)Wtsi>, alleleAccessionId=MGI:5636923, geneSymbol=Nrxn1, geneAccession=MGI:1096391, parameterStableId=IMPC_EVM_018_001, parameterName=% embryos homozygous, procedureStableId=IMPC_EVM_001, procedureName=Viability E12.5 Secondary Screen, pipelineStableId=HRWL_001, pipelineName=Harwell, zygosity=homozygote, phenotypingCenter=MRC Harwell, lifeStage=E12_5, statisticalMethod=null, status=null, metadataGroup=null)=ExperimentsDataTableRow{statisticalMethod='null', status='null', femaleMutantCount=0, maleMutantCount=0, effectSize=null, metadataGroup='null'} DataTableRow [cmsBaseUrl=null, phenotypeTerm=null,gene=org.mousephenotype.cda.solr.service.dto.MarkerBean@c2037746, allele=org.mousephenotype.cda.solr.service.dto.MarkerBean@89d87374, sexes=null, zygosity=homozygote,	 lifeStageName=E12.5, lifeStageAcc=null, projectId=0, phenotypingCenter=MRC Harwell, procedure=ImpressBaseDTO [id=null, stableKey=null, stableId=IMPC_EVM_001, name=Viability E12.5 Secondary Screen],	 parameter=ImpressBaseDTO [id=null, stableKey=null, stableId=IMPC_EVM_018_001, name=% embryos homozygous], dataSourceName=null, evidenceLink=null,	 pipeline=ImpressBaseDTO [id=null, stableKey=null, stableId=HRWL_001, name=Harwell], pValue=null, gid=null, colonyId=null, topLevelPhenotypeTerms=null, topLevelMpGroups=null,
 phenotypeCallUniquePropertyBeans=[]

**Comment by jwgwarren** [comment]
So to fix this we need to check the experiment core and assign top level terms to all the observations for viability??

**Comment by jwgwarren** [comment]
This one is also a derived parameter div('IMPC_EVM_006_001', 'IMPC_EVM_023_001')

**Comment by jwgwarren** [comment]
further looking viability data seems to be discrepancies - pasted from chat - for a new ticket maybe?

Jeremy Mason11:15
https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0005380
Jeremy Mason11:30
https://www.mousephenotype.org/data/charts?accession=MGI:1096391&parameter_stable_id=IMPC_VIA_001_001&parameter_stable_id=IMPC_EVM_001_001
Jeremy Mason11:46
https://www.ebi.ac.uk/mi/impc/solr/statistical-result/select?q=parameter_stable_id:IMPC_VIA_001_001
Jeremy Mason11:55
https://www.ebi.ac.uk/mi/impc/solr/statistical-result/select?q=parameter_stable_id:IMPC_VIA_001_001%20AND%20significant:false&rows=5000&fl=marker_symbol&wt=csv
Embryo data: https://www.ebi.ac.uk/mi/impc/solr/statistical-result/select?q=parameter_stable_id:IMPC_EV*_001_001&rows=5000&fl=marker_symbol&wt=csv
Jeremy Mason12:04
https://www.mousephenotype.org/data/charts?accession=MGI:1338803&allele_accession_id=MGI:5766149&parameter_stable_id=IMPC_VIA_001_001&zygosity=homozygote&phenotyping_center=TCP&pipeline_stable_id=TCP_001
Jeremy Mason12:08
['Aire', 'Ap2a2', 'Ap4e1', 'Bbox1', 'Bscl2', 'Cacna1b', 'Cdk19', 'Clcn3', 'Cnbd1', 'Cnp', 'Dbn1', 'Dnmt3a', 'Dppa1', 'Duoxa2', 'Elmod2', 'Exoc3l2', 'Fastkd5', 'Foxj3', 'Gdpd5', 'Gfod2', 'Gna11', 'Gpr1', 'Grm1', 'Mkrn2', 'Mrpl23', 'Myo9a', 'Nr1d1', 'Nrxn1', 'Prdm15', 'Prdm4', 'Prkab1', 'Ptpn14', 'Sacs', 'Scn11a', 'Sgsh', 'Slc1a3', 'Slc7a8', 'Thsd1', 'Timp3']

**Comment by jwgwarren** [comment]
For this ticket it seems there are only 40 genes that will be like this and that the MP does not associate viability data to top level embryo MP terms as it's not really an annotomical effect on an MP it's viability at the line level.

**Comment by viomunoz** [comment]
Fed to the wrangleres:
39 genes that are "Viable" at the Early Adult stage and, in addition, have embryo viability data. In principle, this would not be expected.

['Aire', 'Ap2a2', 'Ap4e1', 'Bbox1', 'Bscl2', 'Cacna1b', 'Cdk19', 'Clcn3', 'Cnbd1', 'Cnp', 'Dbn1', 'Dnmt3a', 'Dppa1', 'Duoxa2', 'Elmod2', 'Exoc3l2', 'Fastkd5', 'Foxj3', 'Gdpd5', 'Gfod2', 'Gna11', 'Gpr1', 'Grm1', 'Mkrn2', 'Mrpl23', 'Myo9a', 'Nr1d1', 'Nrxn1', 'Prdm15', 'Prdm4', 'Prkab1', 'Ptpn14', 'Sacs', 'Scn11a', 'Sgsh', 'Slc1a3', 'Slc7a8', 'Thsd1', 'Timp3']

In particular, gene Aire https://www.mousephenotype.org/data/genes/MGI:1338803 is reported to be lethal at the embryo stage (E9.5, E12.5) but viable at the EA stage, for the same allele.

![Screenshot 2020-06-11 at 12.44.45.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/df1cb8b3-035c-4fe1-bf03-37ab4bfed854)
