### ISSUE TITLE
Help button for 'ordering mice/ES cells' section on gene pages goes to 404

### ISSUE THREAD

**Issue by elambourne** [mpi2/PhenotypeData#344]
Hi all,

Forgive me if someone has already flagged this. Currently, the help button for the order section of the gene pages goes to a 404 - I've tested this on multiple gene pages.

This looks like a simple URL link error. Help button attempts to go to: https://www.mousephenotype.org/help/gene-page/ordering-mice-or-mouse-prodcuts/

Which I assume is a misspelling of 'products' and should instead go to: https://www.mousephenotype.org/help/data-visualization/gene-pages/ordering-mice-or-mouse-products/ 
unless there is a more up-to-date help/documentation page I'm not aware of.

Kind regards,
Emma

**Comment by jmason-ebi** [comment]
This has been resolved
