### ISSUE TITLE
IMPRESS: connecting MP lists and procedure descriptions, ontology search funtionality

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#346]
**Description:**

In view of the next round of user testing , a couple of things we may probably want to improve:

1. Adding links to pages such as this one: https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#16397

so that the user would be able to click on the Procedure or Parameter ("Open Field" or "Number of center entries" etc.) and be taken to the Procedure descripton, in this case: https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=496&pipeID=7

User case:

In the chart pages, for example, this one:
https://www.mousephenotype.org/data/charts?accession=MGI:2142567&allele_accession_id=MGI:6148227&zygosity=heterozygote&parameter_stable_id=IMPC_OFD_018_001&pipeline_stable_id=HRWL_001&phenotyping_center=MRC%20Harwell

when clicking on the associated phenotype "abnormal behaviour" or "latency to center study" you get here:
https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#16397

which is fine.

However, if you want to learn more about the experiment / procedure "Open Field" or the parameters, there are no links -- the user needs to go back to the chart page and click on "Open Field" or search via the pipelines in the Impress top menu above. Either way, I think this might be too convoluted for most users.

2. When I wanted to go back to https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#16397

I thought I would do it via the Ontology search, but I could not, here: https://www.mousephenotype.org/impress/OntologySearch

When I type "strength" as suggested, select "abnormal physical strength", then click on search, nothing happens. Same behaviour for other MP terms.

I think I would like to see all the procedures that test for the MP term I am looking for.

For example, "hyperactivity" to display procedure Open Field with MP associated to it https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#16397,

but also others where "hyperactivity" is tested for. 

**Requirements:**
Avoiding dead ends, an issue that came up in the previous round of user testing.
1) Adding links to Procedures and Parameters that bring you to the corresponding Procedure descritption. 
2) Connect Onotology Search results with links to list of MP terms in Procedures and Parameters, such as this one:
https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#16397

**Comment by amccoy95** [comment]
The fixes for these have been pushed to our gitlab and we plan to release Wednesday with the IMPReSS API release

**Comment by viomunoz** [comment]
This is great, thank you!

For the results displayed from the chart page, I wonder whether we may want to have results filterd for the parameter, or have the parameter that I clicked on to be displayed first?

For example, in the chart pages:
https://www.mousephenotype.org/data/charts?accession=MGI:2142567&allele_accession_id=MGI:6148227&zygosity=heterozygote¶meter_stable_id=IMPC_OFD_018_001&pipeline_stable_id=HRWL_001&phenotyping_center=MRC%20Harwell

when I click on the associated phenotype **"abnormal behaviour"** or **"latency to center study"**, probably good when I get results filtered for "latency to center study" -- currently all parameters for Open Field are displayed; I wonder whether this is what we want. It is great that now you can click on the parameter name to see the procedure with the relevant experimental information!

**Comment by amccoy95** [comment]
So this is already, kinda of, implemented on the ontologies page. What you have to do is add the Parameter ID with a # on the end of the URL. e.g. `OntologyInfo?action=list&amp;procID=623#27192`

This will scroll to the point in the list and provide "active" styles to indicate it's the one you are viewing.

Screenshot to help visually
![image](https://user-images.githubusercontent.com/46707334/81306779-c7740980-9077-11ea-809c-43f37a7c5a41.png)

**Comment by viomunoz** [comment]
Some kind of filtering / scrolling down to the corresponding parameter will be great -- much clearer to the users! Thanks!

**Comment by amccoy95** [comment]
Scrolling down to the corresponding parameter is already implemented, the issue is the gene page is using the wrong parameter ID. See issue #355
