### ISSUE TITLE
Provide a default sort to the all data table

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#348]
When first visiting the all data table, the values come out in different orders each time the user loads the page.

Need to implement a default sort order when none is selected.

**Comment by jwgwarren** [comment]
Federico has made a new implementation using JSONtableRows to populate the chart??? this implementation seems to have a consistent sort order already??? so no action needed??? so closing.

**Comment by jwgwarren** [comment]
added default order by procedure name as seems sensible on the java side?
