### ISSUE TITLE
Port existing web app to new api project module

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#349]
### Overview
The existing PhenotypeArchive web app jsp-based implementation is moving to an angulario-based, Spring Hateos Restful one. This epic is meant to capture that work.

### Steps
1. Create a new module in the PhenotypeArchive project to hold this new work.

### Acceptance criteria
1. [x] The new maven module **api** exists at the top level and is ready for Spring Hateos development

**Comment by viomunoz** [comment]
This epic will be closed as it is superseded by more recent work.
