### ISSUE TITLE
Integration chart pages - IMPRESS

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#355]
We link from the chart page right corner (experiment and result summary) to IMPRESS. 
Example:
https://www.mousephenotype.org/data/charts?accession=MGI:2142567&allele_accession_id=MGI:6148227&zygosity=heterozygote&parameter_stable_id=IMPC_OFD_018_001&pipeline_stable_id=HRWL_001&phenotyping_center=MRC%20Harwell&errormsg=noontologydata#16397

1.- Link to measuered value should filter to the corresponding parameter (can potentially be a very long list of paramers, like in this case).
2.- Associated phenotype link points to to the same place as the measured value link, but should link to the corresponding MP page on the site.

**Comment by amccoy95** [comment]
Hi Violeta, both of these are the same issue. 

The # anchor being used in the URL is the wrong parameter ID. 

For Abnormal behaviour it's 16397 but it should be 65105 

and for Latency to center entry it's 16397 btu should be 65104

No parameters with the ID currently being used doesn't exist on the page do it doesn't scroll to the correct location on the page

E.g.
https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#65105
https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#65104

**Comment by viomunoz** [comment]
The link to the measured value was removed, so this ticket no longer applies. Closing this ticket.
