### ISSUE TITLE
Non matching MP term: chart page - IMPRESS

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#356]
In the chart pages we have a summary box listing experiment + result in the top right-hand corner:
https://www.mousephenotype.org/data/charts?accession=MGI:2142567&allele_accession_id=MGI:6148227&zygosity=heterozygote&parameter_stable_id=IMPC_OFD_018_001&pipeline_stable_id=HRWL_001&phenotyping_center=MRC%20Harwell&errormsg=noontologydata#16397

Issue: 
The MP "abnormal behaviour", reported on the chart page, does not appear among the possible MP terms listed for Open Field, here:
https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=1162

Or for latency to center entry, here:
https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=1162#1639

MP "abnormal behaviour" is a "parent" MP term. If we annotate to "abnormal behaviour", not clear why we list all those "child" terms as potential options. This needs to be revised or clarify.

**Comment by amccoy95** [comment]
Will have a discussion with wranglers about this as it seems more of a data issue than a web display issue

**Comment by viomunoz** [comment]
I wonder what happened to this ticket, seems the text describing the problem has been lost.

**Comment by jmason-ebi** [comment]
Resolved in DR 15.0
