### ISSUE TITLE
Missing EYE procedure hits

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#373]
See further discussion here:

https://docs.google.com/document/d/1jJqIpRdsphQ44vFB2p0OVzp2Z4h3FunQ27LZuFg8azY/edit

Report from user about missing Eye hits:

looks like there are a variety of issues.
Fam20a and Nadsyn1 were difficult breeders and we only sent in 6 Hom females for both of those lines. If they require 7Mx7F to do analysis, that would exclude these two lines. Awat2 is weird. The data is at the IMPC and they report on everything but the retina which is where the phenotype shows (see image below). Arap1 is odd as well. The IMPC infographic shows Arap1 as “not significant” for eye data but the measurement charts don’t list the eye parameters. So it’s unclear what they looked at to determine it was “not significant”.

It might be worth bringing these up as examples of known hits getting masked by stats analysis and bugs(?) Maybe we could ask for a secondary stats analysis with a lower confidence value where the n doesn’t meet the threshold? I can’t even address what happened to Awat2 and Arap1as it’s unclear where they dropped out.  -- Dave

Awat2  --Eye data at the EBI, retina not included in phenotype calls. (See image below) https://www.mousephenotype.org/data/genes/MGI:3045345#phenotypesTab

Arap1  --Our system shows we sent eye data and it was validated. IMPC infographic lists eye as “not significant” but doesn’t list eye data in test table. Not sure why they would have it on one place but not the other. https://www.mousephenotype.org/data/genes/MGI:1916960

Fam20a --Sent low number of Hom females (6). Our system says eye data has been validated at the EBI. IMPC states eye data not tested. https://www.mousephenotype.org/data/genes/MGI:2388266. Maybe the low number of females got this one excluded?

Nadsyn1 – Sent low number of Hom females (6). Our system says eye data has been validated at the EBI.  IMPC states eye data not tested. https://www.mousephenotype.org/data/genes/MGI:1926164  Maybe the low number of females got this one excluded as well ?

Awat2 test results
 

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/ef1fbfdb-4112-4af0-adf5-f58243377f23)

**Comment by jmason-ebi** [comment]
This will be discussed at the next DAWG.

**Comment by Hamedhm** [comment]
* Awat2 --Eye data at the EBI, retina not included in phenotype calls. https://www.mousephenotype.org/data/genes/MGI:3045345#phenotypesTab

Hamed. Testing retina (combined) IMPC_EYE_092_001, https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=267#7749 we DO NOT derive _92 parameter (is it a derived parameter?) https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/

But e.g. MRC Harwell has https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/MRC_Harwell/IMPC_EYE/IMPC_EYE_092_001/

AND UCD has IMPC_EYE_092_001 data in DR9.2  & DR10 & DR10.1. So something has changed! https://www.ebi.ac.uk/~hamedhm/windowing/DR10.1/jobs/Results_DR101_V1/UC_Davis/IMPC_EYE/IMPC_EYE_092_001/


AI: @ficolo Federico checks DR12 to make sure Retina (combined) IMPC_EYE_092_001 exists in DR12.

######################################################
* Arap1 --Our system shows we sent eye data and it was validated. IMPC infographic lists eye as “not significant” but doesn’t list eye data in test table. Not sure why they would have it on one place but not the other. https://www.mousephenotype.org/data/genes/MGI:1916960, 

Hamed. Arap1 has UCD BL2097 colony in imits https://www.mousephenotype.org/imits/open/mi_attempts?utf8=%E2%9C%93&q%5Bterms%5D=Arap1&q%5Bproduction_centre_name%5D=&q%5Bstatus_name%5D=

but we do not have any eye data for this colony:
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_001_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_007_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_008_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_016_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_017_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_020_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_022_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_023_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_024_001/
https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11V2OpenStats/UC_Davis/IMPC_EYE/IMPC_EYE_025_001/


**I do not even see this colony in DR10.1!**

###############################################
* Fam20a --Sent low number of Hom females (6). Our system says eye data has **been validated at the EBI**. IMPC states eye data not tested. https://www.mousephenotype.org/data/genes/MGI:2388266. Maybe the low number of females got this one excluded?

Hamed. This gene has colony UCD BL3181 https://www.mousephenotype.org/data/genes/MGI:2388266#order

**We do not have any eye data again here! not in DR10.1 & DR9.2.**

#################################################
* Nadsyn1 – Sent low number of Hom females (6). Our system says eye data has been validated at the EBI. IMPC states eye data not tested. https://www.mousephenotype.org/data/genes/MGI:1926164 Maybe the low number of females got this one excluded as well ?

Hamed. Nadsyn1 has UCD colony BL3101 in imits https://www.mousephenotype.org/imits/open/mi_attempts?utf8=%E2%9C%93&q%5Bterms%5D=Nadsyn1%0D%0A&q%5Bproduction_centre_name%5D=&q%5Bstatus_name%5D=  &
https://www.mousephenotype.org/data/genes/MGI:1926164#order

But no data for EYE, however, there are some bodyweights https://www.ebi.ac.uk/~hamedhm/windowing/DR11/jobs/Results_DR11PhenStat/UC_Davis/IMPC_BWT/IMPC_BWT_001_001/BL3101/
*** The threshold for the analysis of the categorical data is 0**

**Comment by jmason-ebi** [comment]
Responses from wranglers:

Awat2 - Data was released, but CDA analysis found it not to be significant. Looking at the retinal mutant vs WT data, this doesn't surprise me. There are a bunch of abnormal calls in the baseline, and a bunch of different categories included. We know that fishers exact has low power in this scenario.
 
For the other three, there are not enough procedures at the DCC to make minimum numbers for export, as defined in IMPReSS. If they submit a procedure status code for each of these, they will be released to the CDA in the next release.
 
Arap1 - 6M+7F at DCC so not released (the eye icon they see on the portal is eye data from PAT and ALZ, not the EYE procedure)
 
Fam20a - 7M+6F at DCC so not released
 
Nadsyn1 - 7M+6F at DCC so not released
