### ISSUE TITLE
Essential Genes landing page: next/final steps

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#375]
Essential Genes landing page is here: https://www.mousephenotype.org/understand/data-focus/essential-genes-portal/

Text has been updated, feedback from the team is welcomed. A figure with the data from the essential genes publication is now on the page. Content will be made dynamic when the Essential Genes Query is ready.

Next steps:

- [ ] a download button for users to directly download the data used to build the figure [1];
- [ ] build the figure feeding from the database that powers the Essential Genes Query app, when ready  [2];
- [ ] update gene counter to match the number of genes in the figure.

[1] **Data we need to extract to build the file in downloadable button:**
A text tabulated file with five columns (mouse or human first is not relevant): 
human gene HGNC id - human gene symbol - mouse gene MGI ID - mouse gene symbol - FUSIL bin

- To do:
  - if there is a fusil bin, extract from database: human gene accession id, human symbol, mouse gene accesssion id, mouse gene symbol and fusil bin (f_bin)

[2] **Data we need to build the histogram:**
Count instances of CL, DL, SV, VP, VN in database

**Comment by jmason-ebi** [comment]
When the essential genes query portal is ready (#354), change the  bottom section to be a paragraph describing the tool and what data is available and provide a large link / button which navigates the user to the standalone tool.

**Comment by viomunoz** [comment]
Icon Essential Data Portal to redirect to the stand-alone tool


![Screenshot 2021-02-10 at 08.55.10.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/70875b4e-ee1a-42ea-89ac-2f8648d4dda5)

**Comment by viomunoz** [comment]
Last section of the page, add something of this sort:
To go to the web app with a Graphical User Interface, please click here [ LINK to the Essential Genes Data portal ]

(The app and data available are described in the Essential Genes Data portal)
