### ISSUE TITLE
Implementation of the essential genes portal backend

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#378]
**Requirements document here:**
https://docs.google.com/document/d/1uveWn1H6nDv8hES0mgIOgelFVzHi2xwid3RljFvyHFE/edit#

**Example:**
Can we get Human orthologs from mouse genes?

See: https://www.gentar.org/refdata/console

**Query:**
query MyQuery { ortholog(limit: 10, where: {support_count: {_gt: "6"}}) { human_gene { id name symbol } support_count support mouse_gene { symbol name id } } }

Provides enough information the get started.

**Steps**
- [x] Write mouse, human, and ortholog data to postgres database batchdata in a docker container
- [x] Install batchdata database to a network location accessible by the hadoop cluster
        Now at jdbc:postgresql://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30965/batchdata
- [x] Write code and script to create parquet file from batchquery database, to be executed on hadoop cluster
- [x] Write code and script to read parquet file to produce a solr core using embedded solr. The solr core
        is to be schemaless, determining the solr field names and data types from the parquet file.
- [x] Determine if the mouse and human filter tables are to be included in batchquery solr core or are 
       instead written to their own core for faster, easier, and more flexible query handling. @viomunoz, @rwilson-ebi , and @mrelac-ebi are currently assigned to this task.
        Created two cores: essentialgenes and ortholog_mapping. essentialgenes has all of the mouse-ortholog-human data without the mapping filter tables. ortholog_mapping has just the humanMappingFilter-ortholog-mouseMappingFilter tables.

Acceptance Criteria:

- [x] One or more Solr cores that is loaded with the batch query data.
        These cores are called essentialgenes and ortholog_mapping and may be found at [http://ves-ebi-d0.ebi.ac.uk:8983/solr/#/](http://ves-ebi-d0.ebi.ac.uk:8983/solr/#/)

**Comment by mrelac-ebi** [comment]
I created github python project https://github.com/mpi2/batch_query_indexer.
The indexer now reads and joins all the ortholog, mouse, and human data from the batchdata postgres database.

**Comment by mrelac-ebi** [comment]
We now have two solr cores to support batchquery. The workflow needs to be automated, so that will be the subject of another ticket.
