### ISSUE TITLE
Data release 12.0

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#379]
Data to come from the DCC.

Discuss a checklist to determine the complete data release procedure.

**Comment by mrelac-ebi** [comment]
The latest Harwell xml data (resent 03-June) is now in place at /net/vnas-production3/ivol_production3/komp2/web/phenotype_data/impc/2020-06-03 (aliased to 'latest')

**Comment by mrelac-ebi** [comment]
Closing this ticket now as DR12.0 has been deployed.
