### ISSUE TITLE
Filtering all data table by system is broken

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#380]
Gene
https://www.mousephenotype.org/data/genes/MGI:103097
Click all data
click Select physiological systems to view: 
Select mortality / aging

Note the page is broken.

Makes a AJAX call to this page:
https://www.mousephenotype.org/data/experimentsTableFrag?geneAccession=MGI:103097&mpTermId=MP:0010768

**Comment by jwgwarren** [comment]
buildQuery method in GenotypePhonetypeService references static variables from StatisticalResultDTO which don't exist in the GenotypePhenotype solr indexes so first was mp_term_id_options then there is female top level mp terms etc.

+ StatisticalResultDTO.MP_TERM_ID_OPTIONS + ":(\"" + StringUtils.join(mpTermId, "\" OR \"") + "\") OR "

**Comment by jwgwarren** [comment]
Removed unusable filters from buildQuery method on genotypephenotype service that can't be applied as they don't exist in that core. All data table dropdown now works
