### ISSUE TITLE
Implement the search page template on a branch and deploy to beta for user testing

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#382]
Search page template update is complete
https://github.com/mpi2/PhenotypeData/files/4688159/search-results.txt 

CDA to implement the search page template on a branch and deploy to beta for user testing

(From ticket #217)

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/c030c9da-85a9-46a8-b66d-2f8e1b7fd10f)

**Comment by viomunoz** [comment]
https://github.com/mpi2/PhenotypeData/files/4688159/search-results.txt

**Comment by jmason-ebi** [comment]
@amccoy95 Can you please look at this file https://github.com/mpi2/PhenotypeData/files/4688159/search-results.txt -- it looks like it's been truncated.

thanks.

**Comment by amccoy95** [comment]
@jmason-ebi Notes on how to implement this are on my last comment in the other issue here: https://github.com/mpi2/PhenotypeData/issues/217 

The file just provides the changes that are needed and not the whole html document as I'm not sure what complier you guys are using and thought would be easier to transfer variable names to smaller text doc and copy and paste into the correct places

> The HTML is to replace the container with the class container single single--no-side on the 
> currently search results page

The style tag at the top will need to be added to your default.css file, the script tag below the call to for the jquery library.

**Comment by jmason-ebi** [comment]
This is now coded on the branch: new-search-results-layout.
See:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/8f6dce18-eb85-4b7d-b6ef-47be5f659b08)

**Comment by jmason-ebi** [comment]
This has been updated with respect to the latest look and feel provided by the DCC.
![image](https://user-images.githubusercontent.com/1931551/88425331-22034300-cde7-11ea-8960-a88ffe61c6b4.png)
