### ISSUE TITLE
Integrate Targ Rep data into the portal

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#384]
We have the Targ Rep data from WTSI to integrate into the portal. A graphql microservice to serve this data is available: https://www.gentar.org/htgt/console

Need to integrate this into the web portal.

**Comment by jmason-ebi** [comment]
Page needs to be able to display minimum set of data similar to the screenshot of the old system:

![High_Throughput_Gene_Targeting_Group_Informatics_-_2020-01-16_11.47.43.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/08bcb32c-5506-444f-ba92-f66e4222c43e)

**Comment by jwgwarren** [comment]
Notes from discussion:
Links from vector section of gene page.
design id in link?
picture is always the same but with different numbers? so completely static image.

**Comment by jwgwarren** [comment]
skeleton page, controller, service and dataAccess objects all set up and wired in.

**Comment by jwgwarren** [comment]
There seems to be a lot of information missing compared to the picture of the original page....?? We only have basic short oligo information and no longer sequences.

**Comment by jmason-ebi** [comment]
Link from the design id:

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/a252b676-61af-4b12-9c3c-8178b2d9a65e)

**Comment by jwgwarren** [comment]
Akt2 has ikmc links but we have no oligos in our service for them - so links just have the image and no more information????

**Comment by jmason-ebi** [comment]
Hmm.. yeah, Should only link if there is data.  I guess the gene page allele section has to check to see if any of the projects have data ...

**Comment by jmason-ebi** [comment]
Pages looks good!  Is a bit of a dead end though.  Provide a breadcrumb with the link to gene?
Also, the URL could maybe be better as /data/genes/MGI:21343214/design/<project id>  (htgt doesn't translate outside of sanger/MPI2)

**Comment by jwgwarren** [comment]
This feels wrong - like we or I am missing something - why have lots of IKMC design ids with no designs? There are some null pointers being thrown by some new code that you mentioned this am I think??
2020-07-14 14:43:55.792  INFO 92021 --- [nio-8080-exec-4] u.a.e.p.web.controller.SearchController  : rootForward(): isProxied = false. scheme = http.
java.lang.NullPointerException
	at uk.ac.ebi.phenotype.ontology.PhenotypeSummaryDAO.isSignificant(PhenotypeSummaryDAO.java:103)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)

**Comment by jmason-ebi** [comment]
There are 2 problems (not connected). 
1) The NPE is related to the code I checked in yesterday which is fixed, I just need to push it.

2) The IKMC missing design ids -- yeah that's strange.  Check with @rwilson-ebi

**Comment by jmason-ebi** [comment]
Regarding 1).  Fix now applied to master and pushed.

**Comment by rwilson-ebi** [comment]
Hi,

In relation to point 2.

Do you have any examples?

I was wondering if the IKMC missing design id are in the original CSV file that was used to build the service, which you can find here:

https://gitlab.ebi.ac.uk/mouse-informatics/htgt/-/tree/master/data

The original correspondence that came with the CSV file it pasted below. We must have requested a list of project IDs from Mark Thomas, so perhaps they were not included, or not available.

Best wishes,

Robert



From: Mark Thomas <mthomas@ebi.ac.uk> 
Sent: Wednesday, February 5, 2020 2:49 PM
To: Alba Gómez <albagomez@ebi.ac.uk>; jmason@ebi.ac.uk
Cc: 'Terry Meehan' <tmeehan@ebi.ac.uk>; David Parry-Smith <dp10@sanger.ac.uk>
Subject: Re: HTGT - oligo information
 
Hi,
 
                I’ve attached a minimum set of oligo details for the design_ids that are included in IMPC. There are however 75 design_ids that have conflicting information, which were not lifted over to the current GRCm38 assembly.  It should also be noted that some of the designs are actually in our existing LIMS2 database and not the HTGT database.
 
Thanks,
Mark
 
 
 
 
 
From: Mark Thomas <mthomas@ebi.ac.uk>
Date: Friday, 17 January 2020 at 11:01
To: Alba Gómez <albagomez@ebi.ac.uk>, <jmason@ebi.ac.uk>
Cc: Terry Meehan <tmeehan@ebi.ac.uk>
Subject: Re: HTGT - oligo information
 
Hi,
 
                We have design details for every design on your list, except for 142 designs with a design_id greater than 1000307.  It appears that all of the design_oligos (G5, G3, U5, U3, D5, D3) have mappings to GRCm38, but most of the additional features were mapped to the assembly that was current at the date of creation (NCBIm36, 37 or GRCm38). I’m free today if you would like to review the data on the oligo_design page that was provided by Sanger.
 
Thanks,
Mark
 
From: Alba Gómez <albagomez@ebi.ac.uk>
Date: Thursday, 16 January 2020 at 12:12
To: <jmason@ebi.ac.uk>, 'Mark Thomas' <mthomas@ebi.ac.uk>
Cc: Terry Meehan <tmeehan@ebi.ac.uk>
Subject: Re: HTGT - oligo information
 
Hi,

Find attached the list of project design ids.

Cheers,

Alba

On 16/01/2020 12:09, jmason@ebi.ac.uk wrote:
Excellent!! Thanks, Mark.  We’ll be in touch shortly with the list of project IDs at which time it might be a good idea to review what we need. 
 
Cheers,
Jeremy

**Comment by jwgwarren** [comment]
31126 is on the AKt2 order list with ikmc design id or at least an IKMC link with an id there. It's not an id in the csv file though.

**Comment by rwilson-ebi** [comment]
Perhaps it is one of the 75 design_ids that have conflicting information, which were not lifted over to the current GRCm38 assembly, or data in their LIMS database rather than the HTGT database (see the email from Mark Thomas), so it looks as if some missing entries are to be expected.

Best wishes,

Robert

**Comment by jwgwarren** [comment]
So possibly a dumb question - I'm assuming ES Cells with Ikmc project ids should link somewhere else? do we know where now?

**Comment by rwilson-ebi** [comment]
Hi Jonathan

Does this page help?

https://mpi2.github.io/IKMC-knowledgebase/2010/08/24/what-are-the-allele-types.html <https://mpi2.github.io/IKMC-knowledgebase/2010/08/24/what-are-the-allele-types.html>

It looks as if it is an archive about the IKMC project - it says it is maintained by MPI2, so I imagine someone knows more about it than me.

All the best,

Robert

**Comment by jwgwarren** [comment]
Gene pages order section should display links to design page if we have oligos for that ikmc_projcect_id/design id.

**Comment by jwgwarren** [comment]
looking at the design_ids they don't seem to match the ids we have in those tables? So the links will never work?

For the example above the design_id=39688
querying allele2 core with https://wwwdev.ebi.ac.uk/mi/impc/dev/solr/allele2/select?q=design_id:39688

we get:
human_gene_symbol: [
"ARID2"
],
design_id: "39688",
cassette: "L1L2_gt2",
ikmc_project: [
"26366",
"80574"
],

When we get the gene page for Arid2 we get the ikmc_project numbers as links but not the design_id. Neither ikmc_project numbers gets any oligos back????? and if we query the allele2 core for ikmc_project=39688 we get nothing back

https://wwwdev.ebi.ac.uk/mi/impc/dev/solr/allele2/select?q=ikmc_project:39688

**Comment by jwgwarren** [comment]
So the ikmc_project ids should link to the design id i.e. have a different href anchor that the project id?

**Comment by jwgwarren** [comment]
so after investigation and reinstating old code the llinks for designs looked like this for arid2:
http://www.sanger.ac.uk/htgt/htgt2/design/designedit/refresh_design?design_id=39688
for all the targeting vectors links??

**Comment by jwgwarren** [comment]
links now work.
used to have a oligo desgin column in order section? Do we want to reinstate one?

**Comment by jwgwarren** [comment]
Need to externalise the gentar graphql url into a property as at the moment it's hard coded to use https://www.gentar.org/htgt/v1/graphql

**Comment by rwilson-ebi** [comment]
Dear Jonathan,

The HTGT service exposed under the gentar domain is running on the EHK cluster, which we are hoping to shut down.

You can direct queries to the HTGT service running on the HX WP kubernetes cluster using the following URL 

(for post requests you need the /v1/graphql endpoint)

This is an internal EBI link, not exposed publicly, and to access it you need to be connected to the VPN, a SSH tunnel is not sufficient. 

The protocol is http, and the routing for this service is via the WP cluster Ingress controller, which is why you need to include the port number.


http://hx-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30395/mi-htgt/console <http://hx-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30395/mi-htgt/console>

http://hx-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30395/mi-htgt/v1/graphql <http://hx-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:30395/mi-htgt/v1/graphql>


I hope that helps.

Best wishes,

Robert

**Comment by jwgwarren** [comment]
is it possible in the future to have this link public? otherwise all developers will have to be on vpn or we will have to add this service to our docker instance??

**Comment by rwilson-ebi** [comment]
Hi Jonathan,

It would make sense to add this to the docker version of impc, but you can already run a local version using docker by cloning the project

https://gitlab.ebi.ac.uk/mouse-informatics/htgt <https://gitlab.ebi.ac.uk/mouse-informatics/htgt>

We have permission to expose WP kubernetes services internally, but it is more complex making them public. We should have a discussion with Jeremy about which services in the WP kubernetes cluster need to be exposed, and how they should be exposed if not under the gentar.org <http://gentar.org/> domain. This will need to be coordinated with Web Production and involves updating the main EBI load balancer.

All the best,

Robert
