### ISSUE TITLE
Documentation/Help pages: integrate old documentation

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#385]
We need to migrate content from the old documentation over, specifically:
https://www.mousephenotype.org/data/documentation/doc-method  
This will require updating content. Need to identify what is useful and worth keeping.

Process agreed on:
1. We will work on a shared doc document;
2. Get feedback;
3. Move to website Help site.

**Comment by jmason-ebi** [comment]
Check with Bora.

**Comment by jmason-ebi** [comment]
This is done on our side. @amccoy95  will migrate this to the website
