### ISSUE TITLE
Essential Genes database backend

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#388]
We need to setup a service to support the essential genes information to be used in both the essential genes portal and the batch query when the essential genes information is included as desired output.

The service will be a postgres database backend with a hasura graphql service serving the API.  This will be deployed to K8S and be available as a public API.  

This service will calculate the FUSIL scores as part of loading the database as well as aggregate.

**Comment by viomunoz** [comment]
Requirements document here:
https://docs.google.com/document/d/1uveWn1H6nDv8hES0mgIOgelFVzHi2xwid3RljFvyHFE/edit#

**Comment by jmason-ebi** [comment]
https://www.gentar.org/essential-genes/console

**Comment by jmason-ebi** [comment]
Adding tests to the build process and need to implement automatically downloading the files that are input to the build process.
