### ISSUE TITLE
solR cores documentation

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#389]
Produce a document that lists the IMPC solR cores and describes the data they contain.

**Comment by jmason-ebi** [comment]
The solr core fields may change slightly.  Wait until DR12.0 is out before completing this.

**Comment by jmason-ebi** [comment]
Expand these documents with the full list of fields:
https://www.mousephenotype.org/help/programmatic-data-access/

**Comment by jmason-ebi** [comment]
This document https://doc-archives.microstrategy.com/producthelp/10/WebUser/WebHelp/Lang_1033/searching_for_data_using_solr_search_syntax.htm has a very nice table showing how to query solr.  We should create a similar table on the Access patterns page: https://www.mousephenotype.org/help/programmatic-data-access/access-patterns/

**Comment by jmason-ebi** [comment]
This is internally documented here:
https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Solr
