### ISSUE TITLE
BUG: significant MP but chart says no significant association

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#390]
Contradictory result...
https://www.mousephenotype.org/data/genes/MGI:104837
MP in gene page, but chart page says not significant:

![Screenshot 2020-06-03 at 17.57.32.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/17ab570e-8e14-4f3c-9c78-2202b1058506)

![Screenshot 2020-06-03 at 17.58.42.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/b03f1374-e70f-4333-a4e0-e5ddf26cf79e)

**Comment by viomunoz** [comment]
Found another example, seems to be immune phenotypes (3i project?):
https://www.mousephenotype.org/data/genes/MGI:98912

![Screenshot 2020-06-05 at 15.19.42.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/8331a6ef-5677-4a6f-b249-c5d5ba84ed3c)

**Comment by jwgwarren** [comment]
so for the first example it' the sex issue of "both" in the gp core so this query works:
https://www.ebi.ac.uk/mi/impc/solr/genotype-phenotype/select?q=*:*&rows=2147483647&fq=marker_accession_id:%22MGI:104837%22&fq=allele_accession_id:%22MGI:4451419%22&fq=strain_accession_id:%22MGI:2159965%22&fq=parameter_stable_id:%22MGP_PBI_015_001%22&fq=zygosity:(homozygote)&fq=phenotyping_center:%22WTSI%22

Whereas the query that is being made is this with sex which is looking for male or female results not the string "both":
https://www.ebi.ac.uk/mi/impc/solr/genotype-phenotype/select?q=*:*&rows=2147483647&fq=marker_accession_id:%22MGI:104837%22&fq=allele_accession_id:%22MGI:4451419%22&fq=strain_accession_id:%22MGI:2159965%22&fq=parameter_stable_id:%22MGP_PBI_015_001%22&fq=sex:(female+OR+male)&fq=zygosity:(homozygote)&fq=phenotyping_center:%22WTSI%22

Seems we have a major issue with this as our previous hack for line level parameters isn't going to catch this one??

**Comment by jwgwarren** [comment]
We could add both to the solr query for all queries with sex male and female so fq=sex:(female+OR+male+OR+both)

**Comment by jwgwarren** [comment]
done as in comment above. pushed to master.
