### ISSUE TITLE
BUG: The chart for subviable result should show associated phenotype

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#391]
The gene Ap4e1 viability charts page should have 2 entries for BCM, one that's viable (for allele tm1b), and one that's subviable (for allele em1).

The chart for the subviable looks like:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/60f32d8b-c638-4722-86a5-e6d022e7dfef)

Note that the "Associated phenotype" says "no significant association", but it should say "preweaning lethality, incomplete penetrance"

**Comment by viomunoz** [comment]
Another gene showing the same problem: 
https://www.mousephenotype.org/data/charts?accession=MGI:99607&allele_accession_id=MGI:5548975&zygosity=homozygote&parameter_stable_id=IMPC_VIA_001_001&pipeline_stable_id=BCM_001&phenotyping_center=BCM

![Screenshot 2020-06-11 at 13.45.55.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/936a5af5-1a07-4251-b0b6-3e853ab4ca89)

**Comment by viomunoz** [comment]
Interstingly, phenotyping center is again BCM.

**Comment by viomunoz** [comment]
Yet another one: Abat
https://www.mousephenotype.org/data/charts?accession=MGI:99607&allele_accession_id=MGI:5548975&zygosity=homozygote&parameter_stable_id=IMPC_VIA_001_001&pipeline_stable_id=BCM_001&phenotyping_center=BCM

![Screenshot 2020-06-11 at 14.06.19.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/4e62dd5e-d1ef-4d50-95a2-8e580f436a96)

**Comment by viomunoz** [comment]
Same situation for all of these:

![Screenshot 2020-06-11 at 14.08.25.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/a375d877-4adb-4ed9-bf5a-0f4d6d4d81a8)

**Comment by viomunoz** [comment]
Seems to happen also in the case of preweaning lethaliy, incomplete pentrance (>> subviable)

![Screenshot 2020-06-15 at 15.37.21.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/ae0a4d95-2973-45a8-9166-fa975144a25e)


![Screenshot 2020-06-15 at 15.37.37.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/2b6850e2-0097-4b3f-b97e-c0bf8ceab1ee)

**Comment by jwgwarren** [comment]
Done for viability. Rule probably needs to be done for all line level parameters though.

**Comment by jwgwarren** [comment]
How do I get a list of line level parameters as constants???

**Comment by viomunoz** [comment]
I have found the following issue:

![Screenshot 2020-06-29 at 16.00.06.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/06a7d017-a8be-4025-bd4b-d8a1bf769beb)

**Comment by jmason-ebi** [comment]
Viable is fixed, but the    problem exists with all line level parameters.  We have a list of procedures that are "line level" .  Impress has added a tag for this, but we have not pulled this tag into the pipeline core yet.
