### ISSUE TITLE
All data table: underlying data not displayed in some cases

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#392]
**To reproduce:**
Go to Nrxn1, All Data table, filter for "litter" and click on row. The underlying data is not displayed.
https://www.mousephenotype.org/data/genes/MGI:1096391

![Screenshot 2020-06-11 at 12.23.27.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3b84ee35-7dba-49dd-9e57-08bd30e287c4)

**Requirements:**
Underlying data to be displayed

**Comment by jwgwarren** [comment]
This is a null pointer on date in ExepreimentService line 292:
//put a null pointer check here as for viability data has none and chart fails
 allBatches.add(o.getDateOfExperiment().getYear() + "-" + o.getDateOfExperiment().getMonth() + "-" + o.getDateOfExperiment().getDate());

**Comment by jmason-ebi** [comment]
Amend to display a message that this data is not available as a chart.

**Comment by jwgwarren** [comment]
seems like we shouldn't have a link to a chart for this row in the table or we have a link to pie chart? code here just handles categorical or falls back to a default of unidimensional.

**Comment by jwgwarren** [comment]
it does say it's unidimensional in the observation and it has a float value.....

**Comment by jmason-ebi** [comment]
Disable the link for the moment.

In future, we can linkto the general line level viability page and display all the line level data/metadata for the appropriate procedure in a table.

**Comment by viomunoz** [comment]
This ticket has been replaced by ticket #408. Closing this ticket.
