### ISSUE TITLE
Viability data: add embryo viability data to viability chart page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#393]
Team agreed to add embryo viability displays to the page you access via the button in the top left corner of the Gene page, "Viability".
Example: https://www.mousephenotype.org/data/genes/MGI:1924295?dataSearch=outcome

We would like to have the EA data displayed first in the chart page. This is because we decided to have the button and the phenogrid icon to display EA viability, as it currently is. Having the EA data displayed first in the chart page will prevent to confuse users when EA is lethal but embryo is viable. Therefore, the order for the displays shoud be (obvisously, data for all stages is not always available):
- primary / adult viability
- IMPC_EVP_001 (E18.5)
- IMPC_EVO_001 (E14.5-E15.5)
- IMPC_EVM_001 (E12.5)
- IMPC_EVL_001 (E9.5)

**Comment by jwgwarren** [comment]
the pie charts aren't displaying other than the main Viability one because the query to our pipeline/impress core does not return any ParameterDTOs for example "IMPC_EVL_001".

**Comment by jwgwarren** [comment]
created a single variable for url in the viablity button tag page and made call for all viability charts included above. Issue now is there is a null pointer for the main viability GeneDTO gene = geneService.getGeneById(accession[0]); as no gene for the line level param??? need to investigage why issue now.

**Comment by jwgwarren** [comment]
Got rid of a hard coded rule that I don't believe is needed anymore to display VIA_001_001 data

**Comment by jwgwarren** [comment]
need to look at ordering now.... but this is really going to be a pain??? or maybe forcing ordering of url for VIA_01 first will be ok??

**Comment by jwgwarren** [comment]
ordered so early adult viability chart if present is displayed at the top

**Comment by viomunoz** [comment]
Embryo viability data not appearing in the Viability charts. Check this gene which as embryo viability data:
https://www.mousephenotype.org/data/genes/MGI:1914552

**Comment by viomunoz** [comment]
Interest reported from a user today to have embryo viability data displayed in the Viablity chart pages.

**Comment by viomunoz** [comment]
Will close this ticket, new ones available #753, #756
