### ISSUE TITLE
Filter on Publication page not working properly

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#401]
**To reproduce:**
Go here: https://www.mousephenotype.org/data/publications

1. Typing "Spns2" in filter box returns 6 publications, but not the van der Weyden et al. 2020 paper which lists this allele.
2. Typing "Abraxas" returns no papers, while this allele is listed in the van der Weyden et al. 2020 paper.
3. Typing "TMEM35" or "Tmem35" does not return the Dhara et al. Nat Comm 2020 paper which lists this allele (why is this allele in upper case? Should be firtst upper case followed by lower case)

![Screenshot 2020-06-29 at 14.28.36.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/8fe32fba-a8ec-478e-9d93-96c124a9cfd8)

4. Typing "TMEM35" or "tmem35" returns 1 publication, but "Tmem35" returns no publications (filter should be case insensitive):

![Screenshot 2020-06-29 at 14.37.09.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/8561fe12-e19e-4d1e-956f-b8f2866c1078)

![Screenshot 2020-06-29 at 14.37.45.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/e8fb9116-54d8-4628-b518-3c1db9a2494f)

5. Typing "TMEM35a" or "tmem35a" returns no publications.

![Screenshot 2020-06-29 at 14.37.31.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/e20235f5-cb97-4f58-bbdc-4f2643d2160d)

**Comment by mrelac-ebi** [comment]
Made filter case-insensitive. Added filtering by gene symbol and allele symbol.

**Comment by viomunoz** [comment]
Thanks! Looks good!
