### ISSUE TITLE
Embryo heatmap not displaying

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#403]
https://www.mousephenotype.org/data/embryo_imaging

**Comment by jwgwarren** [comment]
Error from server at http://127.0.0.1:8984/solr/gene: Too many clauses in boolean query: encountered=1041 configured in solrconfig.xml via maxBooleanClauses=1024

**Comment by jmason-ebi** [comment]
Fix was to change the query to split the gene ids and query a set at a time.
Commit https://github.com/mpi2/PhenotypeData/commit/a4486689740e4a293ed7bc22d08e76648747bf68
