### ISSUE TITLE
Bug: gene symbol synonym issue affecting search display and gene page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#407]
Pramef20 is a synonym of Pramel5: http://www.informatics.jax.org/marker/MGI:3712553

Requirement: Pramef20 should be listed as synonym, otherwise the user may not understand, at first glance, why results from Pramel15 are returned.

![Screenshot 2020-07-14 at 13.16.31.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/833b0187-f64b-49c1-a39c-5ebb04f4ae8c)

![Screenshot 2020-07-14 at 13.18.42.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c6cba617-2fbc-4d1c-8d42-80463373c421)

**Comment by jmason-ebi** [comment]
This was fixed.
