### ISSUE TITLE
Histopath data: severity 1 annotated significant, but severity 2 and 3 are not

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#427]
Need clarification on the annotation at the top of this page.
Severity 1 annotated significant, but severity 2 and 3 are not.
Need to clarify.

Example: [histopath data for Setd2](https://www.mousephenotype.org/data/histopath/MGI:1918177)

![Screenshot 2020-08-24 at 17.13.11.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/1190139c-2eea-4ac6-a254-a33424190fc0)

**Comment by la-sts** [comment]
@viomunoz this is correct behaviour, as the significance is `0` for those instances. See the description at top [histopath data for Setd2](https://www.mousephenotype.org/data/histopath/MGI:1918177):
>Significance Score:
>
> - 0 = Not significant (histopathology finding that is interpreted by the histopathologist to be within normal limits of background strain-related findings or an incidental finding not related to genotype)
> - 1 = Significant (histopathology finding that is interpreted by the histopathologist to not be a background strain-related finding or an incidental finding)

**Comment by viomunoz** [comment]
@la-sts a user sees that a histopath "observation barely perceptible and not believed to have clinical significance" is annotated as significant, while a histopath "observation clearly visible involves a significant proportion of tissue and is likely to have some clinical manifestations generally expected to be minor"  is annotated as non-significant. Would be good to explain, particularly because there is no WT observations included with this data.

All observations annotated as non-significant in DR12.0: https://dev.mousephenotype.org/data/histopath/MGI:1918177

Example "eye with optic nerve" annotations in DR11.0:

![Screenshot 2020-08-26 at 11.29.43.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/da78fc4f-adb4-4cb0-99d8-ace54df11e61)

![Screenshot 2020-08-26 at 11.27.07.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/8c46c587-9591-4686-a2dd-8259d099e5fe)

**Comment by la-sts** [comment]
Agreed @viomunoz - we can bring this up with the WG chair, and see if we can improve the definition on the different severity scores.

**Comment by jwgwarren** [comment]
So the bug above with no significance - is this due to some new way of giving us the data or is it a bug in our ETL. The display code itself has not been modified so it won't be in the JSP page itself.

**Comment by la-sts** [comment]
@jwgwarren not a 'bug' with data or ETL, but unclear definition between 'significance' and 'severity' and how they contribute to phenotype calling. Will update after contacting Colin M.

**Comment by jwgwarren** [comment]
There were two issues here. One the lack of logic/ clarity and two the fact that no significant scores were being displayed. I've fixed issue two after assigning it to another ticket.
Issue one is just that severity is different from significance and just because something is severe the histopathologists may still think it's more a background issue and not due to the knockout itself. Due to the lack of statistical analysis on this it seems dubious to us to do things this way.... but that is the way the histopathologists work!?? and that we were told to display it.

**Comment by jwgwarren** [comment]
This can be closed now?

**Comment by jwgwarren** [comment]
As the new definitions from Colin are up.
