### ISSUE TITLE
Kdm6b: Search says phenotypic data available, but no data on gene page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#430]
Search says phenotypic data available:

https://dev.mousephenotype.org/data/search?term=Kdm6b&type=

But no data on gene page:

https://dev.mousephenotype.org/data/genes/MGI:2448492

Same issue DR11.0

jmason commented: 
Looks like another one that got accidentally set when we tried to abort the WTSI phenotype attempt registered strains.

**Comment by jmason-ebi** [comment]
Fixed
