### ISSUE TITLE
Inconsistencies IMPC_VIA_002

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#433]
Team found some inconsistencies in the s-r core thanks to the procedureCompleteness report, which seem to be related to IMPC_VIA_002.

This produces 5 docs with these problems:

http://ves-ebi-d0.ebi.ac.uk:8986/solr/statistical-result/select?fl=strain_name,zygosity,parameter_stable_id,parameter_name,life_stage_name&q=colony_id:UCD-10243A-E8-2-1%20AND%20procedure_stable_id:IMPC_VIA_002

- hemizygotes are missing life_stage_name and life_stage_acc and strain_name (but *NOT* the strain_accession_id)
- parameter_name 'Heterozygous animals viability' (IMPC_VIA_066_001) shows zygosity 'homozygote'

**Comment by mrelac-ebi** [comment]
I can no longer recreate these problems. Is this fixed?

**Comment by mrelac-ebi** [comment]
No reply to my last comment, so am closing this ticket. A new ticket can be created if needed.
