### ISSUE TITLE
IMPRESS: glossary search displays pairs of identical rows

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#435]
**Issue:**
See display of pairs of identical rows below.

------------------------
**Screenshot from Ontology Search result:**
https://www.mousephenotype.org/impress/OntologySearch?ontoTerm=MP%3A0011100

![Screenshot 2020-09-07 at 12.18.32.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/73712c15-258f-4f4c-99cd-bb71764e3f6b)

**Comment by amccoy95** [comment]
Thanks Violeta, I have created a ticket on the Impress-Web repo on our Harwell Gitlab to keep track of. Closing ticket as it will be a duplicate.
