### ISSUE TITLE
Update essential genes solr core

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#443]
Essential genes portal is returning multiple rows for human sysnonyms and mouse synonyms.  For instance, searching for a single MGI ID was resulting in 6 distinct rows.

After discussion, the conclusion is to collapse the synonym fields into single multi-valued fields (one for human and one for mouse).  This will correct the cardinality issue as well as maintain the ability to search by synonym.

**Comment by mrelac-ebi** [comment]
Mouse and Human synonyms are now collapsed into two single multiValued fields: mgs_synonyms and hgs_synonyms.
Here is a working example: http://ves-ebi-d0.ebi.ac.uk:8986/solr/essentialgenes/select?q=hgs_synonyms:SCARA4
