### ISSUE TITLE
batchData: add fields to ortholog_mapping

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#449]
The batchData ortholog_mapping solr core needs the following fields added:

- mouse symbol
- mouse gene accession id
- human symbol
- human gene accession id

**Comment by mrelac-ebi** [comment]
Done. mouse and gene accession ids and symbols are now in the ortholog_mapping cores and have been pushed to DEV, STAGING, and LIVE.

**Comment by jmason-ebi** [comment]
Confirmed fields exist
