### ISSUE TITLE
Physiological system filter not working for the All data table in the Gene Page

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#451]
**Bug description**
When you select a physiological system in the filter for the All data table, the table does not get filtered.

![Screenshot 2020-10-15 at 15 06 09](https://user-images.githubusercontent.com/2343039/96140659-12802b80-0ef8-11eb-91ba-4041038ed73e.png)

**Link**
https://www.mousephenotype.org/data/genes/MGI:1929293
 
**Screenshot(s)**
![Screenshot 2020-10-15 at 15 07 30](https://user-images.githubusercontent.com/2343039/96140733-29bf1900-0ef8-11eb-9588-2bb41043d73c.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Got to a Gene page https://www.mousephenotype.org/data/genes/MGI:1929293
2. Go to the All data tab
3. Click on one of the options in the Physiological system filter

**Expected behaviour**
The table should be filtered displaying only the entries in that table that contain a parameter related to that physiological system.

**Comment by jmason-ebi** [comment]
Fixed on dev
