### ISSUE TITLE
Valid gene selection redirects to error page

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#453]
**Description**
Through RT, a user reported that the website indicates data is available for Wdr45 but that when they click on the link they are redirected to the error page.

**Link redirecting to error page**
https://www.mousephenotype.org/data/genes/MGI:1859606
 
**To Reproduce**
1. Go to [https://www.mousephenotype.org/data/search?term=Wdr45&type=gene](https://www.mousephenotype.org/data/search?term=Wdr45&type=gene)
2. Click on Wdr45 (There is also a link, Wdr45b, that works as expected)
3. See error

**Expected behavior**
A valid gene page should be displayed

**Comment by mrelac-ebi** [comment]
I've narrowed the exception to this line:
[https://github.com/mpi2/PhenotypeData/blob/0bb9bb2d60dec1805f0b82a691734fdda2c5cecc/data-model-solr/src/main/java/org/mousephenotype/cda/solr/service/StatisticalResultService.java#L1018](https://github.com/mpi2/PhenotypeData/blob/0bb9bb2d60dec1805f0b82a691734fdda2c5cecc/data-model-solr/src/main/java/org/mousephenotype/cda/solr/service/StatisticalResultService.java#L1018)
which, for gene Wdr45, has a collection of 6 p-values, two of which are null.
The next question, then, is "Why are there two null p-values?".

**Comment by mrelac-ebi** [comment]
In an e-mail from @ficolo he verified that the null p-values were not intended to be in the list. He fixed the issue by filtering out null p-values.
The fix has been deployed to LIVE and now correctly shows the gene page.

**Comment by jmason-ebi** [comment]
Confirmed
