### ISSUE TITLE
procedureCompleteness report

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#455]
**Background information:**

The procedureCompletnesss report, here: ftp://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-12.0/results/
lists, for each allele / colony, attributes for that colony (gene, allele, center, etc.) and:

- Procedures that were successful,
- Procedures that were not processed,
- Parameters that were successful,
- Parameterts that were not processed,
- Top leve MP terms that were succesful,
- MP terms that were successful.

For each one of these categories, there are 3 columns: Name, Stable ID and Count.

**Proposed action items:**

1. - [x] MP terms that we are listing as succesful are MP hits. To reduce ambiguity, we are changing the wording "Successful" to "Significant". This affects the 3 last columns: "MP Name: Successful", "MP Accession Id: Successful", and "MP Count: Successful".
1. - [x] Top-level terms listed as sucessful reflect those procedures that were successful, rather than the MP hits. We need to add Top-level MP terms that are signifcant, i.e. encompassing the MP terms that are significant. Three new columns are needed: "Top-level MP Name: Significant", "Top-level MP Accession Id: Significant", and "Top-level MP Count: Significant".
1. - [x] For simplicity, the top-level terms listed as successful could be removed from the report (because of the nateure of the IMPC phenotyping pipeline, the more procedures succesful, the more biological systems examined that were successful), or we could decide to keep. @jmason to provide feedback, please :) 
1. - [x] Change the procedureCompleteness report name to procedureCompletenessAndPhenotypeHits report.

**Comment by mrelac-ebi** [comment]
Report updates are complete.

**Comment by jmason-ebi** [comment]
Keep the top levels.  Multiple uses for this data including things like co-occurance maps are made possible by this data.  While it is available elsewhere (API) its also nice to have it consolidated here.
