### ISSUE TITLE
Embryo Development page: fix links

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#458]
**Issue:**
This page https://www.mousephenotype.org/data/embryo, section "Accessing Embryo Phenotype Data":

- Has links that need fixing.  
- We can also improve the text in this section to help the use identify where to go.

===
**Text to look like this:**

Embryo phenotype data can be accessed in multiple ways:

- [Embryo Images: interactive heatmap](https://www.mousephenotype.org/data/embryo_imaging)
A compilation of all our Embryo Images, organised by gene and life stage, with access to the Interactive Embryo Viewer, where you can compare mutants and wild types side by side and rotate 2D and 3D images; we also provide access to our external partners' embryo images.

- [Embryo Vignettes](https://www.mousephenotype.org/data/embryo/vignettes)
Showcase of best embryo images with detailed explanations.

- From the [FTP site, latest release](ftp://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/latest/results/)
All our results. Reports need to be filtered by a dedicated column, Life Stage (E9.5, E12.5, E15.5 and E18.5). Please check the README file or see documentation [here](https://www.mousephenotype.org/help/non-programmatic-data-access/)).

- Using the REST API (see documenation [here](https://www.mousephenotype.org/help/programmatic-data-access/))

===
**To do:**
- [x] Change text in section "Accessing Embryo Phenotype Data"
- [x] Add links

**Comment by jmason-ebi** [comment]
I don't see the changes reflected in the dev site:

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/85e42ad9-c1c9-4566-bfaa-2fd23ca22bb9)

**Comment by jwgwarren** [comment]
Its on master in GitHub but the Jenkins job didn’t build because of a test failure:

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   PharosServiceTest.testGetPharosInfo:20 » UnknownContentType Could not extract ...
[INFO] 
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0

**Comment by jmason-ebi** [comment]
Fixes failing test (removed it actually).  Builds and looks great!

**Comment by viomunoz** [comment]
Sorry, need to reopen, link to ftp documentation is missing (says "here" but there is no link). There is also an extra bracket that should not be there (typo in the original suggestion).

**Comment by jmason-ebi** [comment]
Both issues resolved.
