### ISSUE TITLE
Need Jenkins job to automatically delete old batch_query input files

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#466]
The Jenkins job [IMPC_batch_query_download_reports](http://ves-ebi-d9.ebi.ac.uk:8080/jenkins/view/Batch%20Query/job/IMPC_batch_query_download_reports/) downloads new batch query text files periodically. The filesets are accumulating. We need a Jenkins job to delete old versions of these files.

Files are at /nfs/komp2/web/datafiles/batch

**Comment by mrelac-ebi** [comment]
Created Jenkins batch job http://ves-ebi-d9.ebi.ac.uk:8080/jenkins/view/Batch%20Query/job/IMPC_batch_query_clean_download/ to delete batch query download files older than 14 days.

**Comment by jmason-ebi** [comment]
Renamed to EG instead of batch_query
