### ISSUE TITLE
X-ray atlas: entry in the IMPC website Publications page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#469]
Have a link in the publications section of the  website that brings the user to a News post which describes the atlas.
News post will include link to download the atlas in PDF format.
We could have a thumbnail of the atlas cover in the Publications section to attract attention.

**Comment by jmason-ebi** [comment]
Decided to add a blog post and a home page banner to advervise this.  Will not add entry to the publications page.

Done.
