### ISSUE TITLE
X-ray atlas: link in the X-ray images page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#470]
Have a link in the X-ray image pages of the IMPC website to the News post about the atlas.

- X-ray images are accessed from the Image section of the Gene page
- X-ray images for Cib2 KOs (mutant is indicated on the top left corner): https://www.mousephenotype.org/data/imageComparator?&parameter_stable_id=IMPC_XRY_034_001&acc=MGI:1929293
- Gene page for Cib2: https://www.mousephenotype.org/data/genes/MGI:1929293

**Comment by jmason-ebi** [comment]
Won't do.
