### ISSUE TITLE
Display of Disease Models section gene page: enhance UX

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#486]
For example, Cib2:
https://www.mousephenotype.org/data/genes/MGI:1929293

**Discussion needed; some potential issues:**
- [ ] Column 1 and 2 with headers "Model" and "Genotype": consider "Mouse line" and "Description"?
-   "Mouse line" can list MGI genotype IDs and for IMPC lines we could list them as "IMPC MGI:5548707 HOM" or "IMPC MGI:5548707 HET". 
-   "Description" (or a better name?) so we can include here all information that is there currently: background strain, allele composition, zygosity and life stage.

- [ ] Column 2 fields, allele notation: use the convention?
-  For examle:
  Allele composition of a hom: Cib2<tm1b(EUCOMM)Wtsi> / <Cib2tm1b(EUCOMM)Wtsi>
  Allele composition of a het: Cib2<tm1b(EUCOMM)Wtsi> / +
- [ ] Links to MGI when not an IMPC allele, links to OMIM, ORPHANET and DECIPHER IDs; for example, OMIM:609439 to point to https://www.omim.org/entry/609439
- [ ] IMPC icon: smaller 
- [ ] Phenogrid widget: make it larger
- [ ] Phenogrid widget: on clicking the “i” icon, the information provided seems to be outdated – are we displaying the most recent version of the Phenogrid widget? https://github.com/monarch-initiative/phenogrid

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/31fa8b2b-ba55-49a8-81f6-fdc72eb49bd8)

**Comment by jmason-ebi** [comment]
No longer applicable.  Changes implemented on BETA based on UX expert feedback.
