### ISSUE TITLE
Orange icon but not significant phenotype in table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#49]
Pfn4, Smyd5, Rlbp1  --orange icons, but no table with significant phenotypes; cannot bring the data by clicking on the icons in the phenogrid:
https://www.mousephenotype.org/data/genes/MGI:1920121
https://www.mousephenotype.org/data/genes/MGI:108048
https://www.mousephenotype.org/data/genes/MGI:97930

In old website, see message "No results meet the p-value threshold" but one icon is orange. However, here you can bring the data by clicking on the icons in the phenogrid:
http://www.mousephenotype.org/data/genes/MGI:108048#section-associations

**Comment by jmason-ebi** [comment]
Updated the links to not include the mousephenotypetest.org domain

**Comment by jmason-ebi** [comment]
This is resolved in Data Release 10.1

**Comment by jmason-ebi** [comment]
Currently on DEV:
http://dev.mousephenotype.org/data/genes/MGI:1920121
http://dev.mousephenotype.org/data/genes/MGI:108048
http://dev.mousephenotype.org/data/genes/MGI:97930
