### ISSUE TITLE
Registration of Interest report

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#503]
As a production center manager, I want to see a report showcasing the community's registrations of interest in genes so that I can prioritize the genes that enter the production pipeline.

Minimum requirements for the list.  The list should:
 - [ ] NOT include any personally identifying information
 - [ ] show (at minimum) gene symbols, gene accession ids
 - [ ] show existing production status
 - [ ] aggregate counts of registrations by gene
 - [ ] be periodically updated (weekly)

This will need to aggregate information from the RI database, iMits, and GenTaR.

**Comment by viomunoz** [comment]
May be also to consider:
- report time / dates of registration in an additional column of the report – as a production manager I may be interested in knowing whether interest is recent;
- include as one of the standard GenTaR reports – as a production manager, this seems a logical place to find the report.

**Comment by mrelac-ebi** [comment]
Done. This report is called RegistrationOfInterest and is in the reports module, package org.mousephenotype.cda.reports2.
When the new Register Interest code is released to live, a jenkins job will need to be made to provide this report, to be run
on a weekly schedule and to be pushed to the ftp directory (unless others have a better idea).

**Comment by mrelac-ebi** [comment]
Register interest is now complete. The jenkins job Reports_registration_of_interest runs weekly and deposits the report into the ftp target directory /nfs/ftp/pub/databases/impc/all-data-releases/release-${CURRENT_DATA_RELEASE}/results.
${CURRENT_DATA_RELEASE} is defined in Jenkins and is set to the current data release (e.g. "14.0").
Additonally, this report has been added to the README.md and README.txt files.
