### ISSUE TITLE
All Data Table filters for physiological system not working

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#505]
**To reproduce:**

1. Go to gene page https://www.mousephenotype.org/data/genes/MGI:1933736
2. Go to All Data table: 129 pages available
3. Filter for "hearing" or "growth/size/body region": 129 pages available

**Requirements:**
Data table to show only the procedures/parameters corresponding to the physiological system selected.

**Comment by jwgwarren** [comment]
So I think the new code for the all data table gets the observations from the gene core raw data field? in these fields I'm not sure there is a top level phenotype that I can use to match the filter for each data point? How best to get the top level mp term to match for filtering?

**Comment by viomunoz** [comment]
Solved, ticket #436
