### ISSUE TITLE
Hearing landing page: the 4 charts showing ABR data are not displaying

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#506]
Hearing landing page: https://www.mousephenotype.org/data/biological-system/hearing

Charts not displaying:

![Screenshot 2021-01-14 at 20.06.01.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/e646e1a0-7b5f-46af-ae49-b7ebe165f477)

Please fix.

**Comment by jwgwarren** [comment]
3 are now showing although this was by handling a null pointer for procedureId. Recently we decided we needed the procedure Id as well as pipeline and parameter? So maybe the correct solution is to add the procedure ids to the requested URL?

**Comment by jwgwarren** [comment]
chart that is not displaying is using a pre allocated generated by us allele accession id? NULL-387FB49D6

http://localhost:8080/PhenotypeArchive_war/chart?accession=MGI:1915589&parameter_stable_id=IMPC_ABR_012_001&chart_type=UNIDIMENSIONAL_ABR_PLOT&pipeline_stable_id=UCD_001&zygosity=homozygote&phenotyping_center=UC%20Davis&strain_accession_id=MGI:2683688&allele_accession_id=NULL-387FB49D6&chart_only=true&experimentNumber=wdtc1&_=1611762016815

**Comment by jwgwarren** [comment]
3 charts fixed which needed procedure_ids added to the links as we now require this.
1 Chart has observation id coming back as null - presumably this needs to be fixed so passing this on to Federico - it does have some info and is ABR but why no observation type?
Chart url is this http://localhost:8080/PhenotypeArchive_war/chart?accession=MGI:1915589&parameter_stable_id=IMPC_ABR_012_001&procedure_stable_id=IMPC_ABR_001&chart_type=UNIDIMENSIONAL_ABR_PLOT&pipeline_stable_id=UCD_001&zygosity=homozygote&phenotyping_center=UC%20Davis&strain_accession_id=MGI:2683688&allele_accession_id=NOT-RELEASED-387fb49d62&chart_only=true&experimentNumber=wdtc1&_=1612190824723

**Comment by ficolo** [comment]
Hi fixed the last one.


https://dev.mousephenotype.org/data/biological-system/hearing

**Comment by ficolo** [comment]
The issue was that UC Davis updated the version of the procedure from ABR_001 to ABR_002 and resubmitted all the data so there was no data for that link to be resolved.

**Comment by jmason-ebi** [comment]
Thanks both.  This looks ready for review

**Comment by viomunoz** [comment]
This has now been resolved.
