### ISSUE TITLE
Histopath landing page isn't showing any significant hits

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#513]
The landing page:
https://www.mousephenotype.org/data/landing_pages/histopath

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/fb7bed4e-23ea-471f-baad-e1ca9cebdad7)

Is not showing any significant hits.  I would expect that some of the data to be significant -- specifically the Gene Lyst should have a significant histopath hit for Eye with Optic nerve

https://www.mousephenotype.org/data/genes/MGI:107448
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/64ee6f9a-e9c4-4de2-b556-edd8822056a0)

**Comment by cmckerlie** [comment]
Note that orange is significant, and I'm sure the adrenal gland does not have significan-annotated histopathology for those genes in view, and if you scroll  pretty much all of the genes.

**Comment by jwgwarren** [comment]
looks to me that at the moment values for significance are being returned as a mixture of either number Strings e.g. "0" or "Not applicable" before they were just Strings like not applicable etc.

**Comment by jwgwarren** [comment]
Values are all either 0 or the value returned in the java code for when no value using the getOrDefault method:

value=0 sig returned=0
value=0 sig returned=0
value=No value found sig returned=0

I've changed the java method to cope with number Strings or String values as words like significant. but data is always as above.

**Comment by jwgwarren** [comment]
I can confirm that on dev this request which is made returns all 0

http://ves-ebi-d0.ebi.ac.uk:8986/solr/experiment/select?q=*:*&rows=0&sort=id+asc&fq=parameter_stable_id:*HIS*&fq=parameter_name:*Significance*&facet=true&facet.pivot=gene_symbol,parameter_name,category&facet.limit=-1

{
field: "parameter_name",
value: "Thyroid - Significance score",
count: 4,
pivot: [
{
field: "category",
value: "0",
count: 4
}
]
},
{
field: "parameter_name",
value: "Tongue - Significance score",
count: 4,
pivot: [
{
field: "category",
value: "0",
count: 4
}
]
},
{
field: "parameter_name",
value: "Trachea - Significance score",
count: 4,
pivot: [
{
field: "category",
value: "0",
count: 4
}
]
},
{

**Comment by jwgwarren** [comment]
whereas on hx d1 a query like this shows strings and some are significant - so dev and live are different as comment above and show number strings of 0.

http://ves-hx-d1.ebi.ac.uk:8986/solr/experiment/select?q=*:*&rows=0&sort=id+asc&fq=parameter_stable_id:*HIS*&fq=parameter_name:*Significance*&facet=true&facet.pivot=gene_symbol,parameter_name,category&facet.limit=-1


{
field: "category",
value: "Not significant",
count: 1
},
{


field: "category",
value: "Significant",
count: 1
}
]
},

**Comment by cmckerlie** [comment]
Hi Alex. Thought you might be interested in this

Stay Well, Stay Happy
Colin

**Comment by jmason-ebi** [comment]
The query that @jwgwarren pasted above now shows the following entry for gene Lyst:

       {
              "field":"parameter_name",
              "value":"Eye with optic nerve - Significance score",
              "count":4,
              "pivot":[{
                  "field":"category",
                  "value":"Not significant",
                  "count":3},
                {
                  "field":"category",
                  "value":"Significant",
                  "count":1}]},

Which should translate into an orange cell on the heatmap.
