### ISSUE TITLE
ETL: Update gene core with Register Interest status

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#518]
## Description
Gene status changes need to be made available to Register Interest for both imits (for null and conditional alleles) and gentar (for crisper alleles and, eventually, other types of alleles). Register Interest is now being simplified and will get its gene statuses from the gene core. It will no longer consume the imits/gentar reports; rather, ETL will be the new consumer of these reports. This ticket is meant to capture the data the ETL needs from imits and gentar, the mapping that must be done, and the new fields that must be added to the gene core.

## Action Items

- [x] @albags, @rwilson-ebi - Please review the imits to register interest status mappings and correct as necessary. 
- [x] @albags, @rwilson-ebi - Please provide the gentar to register interest status mappings
- [x] @ficolo, @mrelac-ebi - Please write the code to:
    - [x] consume the imits report and map imits statuses to register interest statuses
    - [x] consume the gentar report and map gentar statuses to register interest statuses
    - [x] update each gene in the gene core with the new status values

### Existing imits report
Currently there is a single imits report named _mp2_load_gene_interest_report.tsv_ that provides assignment statuses, null and conditional allele statuses and a whole host of other data (much of it unneeded and unused) to support Register Interest. The report is identified by the property **GeneStatusChangeUrl**, which is found in any config server such as [http://ves-ebi-d9.ebi.ac.uk:8888/ri/dev](http://ves-ebi-d9.ebi.ac.uk:8888/ri/dev).

### New gentar report
Ticket #530 describes the requirements for the new gentar status report consumed by this ticket. This report is available as a `.tsv` (tab-separated values) file and may be downloaded from https://www.gentar.org/tracker-api/api/reports/gene_interest.

### History
Register Interest consumed this report and:
- mapped the many imits statuses to a short list of Register Interest statuses
- for each register interest status that changed:
    - alerted via e-mail users who registered interest in these genes with changed status

Since those times, gentar has been released, providing crispr allele status iniformation in addition to null and conditional allele status information.

### imits status report requirements
These are the fields required by ETL from the imits status report. These fields are already being provided:
- gene_marker_symbol (_Gene Symbol_)
- gene_mgi_accession_id (_Gene MGI Accession Id_)
- gene_assignment_status (_Assignment Status_)
- null_allele_production_status (_Null Allele Production Status_)
- conditional_allele_production_status (_Conditional Allele Production Status_)

#### Imits to register interest status mapping
This mapping is defined in the **ri** database in **ri.imits_status**. 
_NOTE: Phenotyping status will now be computed from the solr cores rather than provided by imits/gentar.
Thus, we can omit any imits and gentar statuses related to phenotyping._

Imits Status   |   Register Interest Status
------------   |  ------------------------
Aborted - ES Cell QC Failed             | Selected for production and phenotyping
Assigned - ES Cell QC Complete          | Selected for production and phenotyping
Assigned - ES Cell QC In Progress       | Selected for production and phenotyping
Assigned                                | Selected for production and phenotyping
Chimeras obtained                       | Started
Chimeras/Founder obtained               | Started
Conflict                                | Selected for production and phenotyping
Cre Excision Complete                   | Genotype confirmed mice
Cre Excision Started                    | Started
Founder obtained                        | Started
Genotype confirmed                      | Genotype confirmed mice
Inactive                                | Withdrawn
Inspect - Conflict                      | Selected for production and phenotyping
Inspect - GLT Mouse                     | Selected for production and phenotyping
Inspect - MI Attempt                    | Selected for production and phenotyping
Interest                                | Selected for production and phenotyping
Micro-injection aborted                 | Started
Micro-injection in progress             | Started
Withdrawn                               | Withdrawn

### gentar status report requirements
These are the fields required from the gentar status report:
- gene_symbol (_Gene Symbol_)
- gene_accession_id (_Gene MGI Accession Id_)
- gene_assignment_status (_Assignment Status_)
- null_allele_production_status (_Null Allele Production Status_)
- conditional_allele_production_status (_Conditional Allele Production Status_)
- crispr_allele_production_status (_Crispr Allele Production Status_)

#### gentar to register interest status mapping
These status values are provided by gentar:

Gentar Status   |   Register Interest Status
-------------   |  ------------------------
Abandoned                                       | Withdrawn
Attempt Aborted                                 | Withdrawn
Attempt In Progress                             | Started
Colony Aborted                                  | Withdrawn
Embryos Obtained                                | Started
Founder Obtained                                | Started
Genotype Confirmed                              | Genotype Confirmed Mice
Genotype Extinct                                | Withdrawn
Genotype In Progress                            | Started
Genotype Not Confirmed                          | Started
Inactive                                        | Withdrawn
Plan Abandoned                                  | Withdrawn
Plan Created                                    | Selected for production and phenotyping

### Register Interest status values
These status values are defined in the **ri** database in **ri.gene_status**.

#### Register Interest Status, in ascending chronological order (except for _Withdrawn_, which may appear at any stage)

- _Selected for production and phenotyping_
- _Started_
- _Genotype confirmed mice_
- _Phenotyping data available_
- _Withdrawn_

### Assignment Status
This column is meant to display the most advanced assignment status, irrespective of source
(i.e. imits or gentar). In order to determine a single assignment status:
- both the imits and gentar reports must be consumed, _and_
- a single assignment status value computed according to the Assignment Status rules below, _then_
- the correct register interest assignment status chosen from the imits or gentar status to register interest status mapping.

#### Imits and Gentar Report Column Names
Both the imits and gentar reports have a column for assignment status:
Imits Report Column Name   |   Gentar Report Column Name
---------------------------   |   ----------------------------
gene_assignment_status      | Assignment Status

#### Determining Most Advanced Status
Use the following tables to determine the most advanced status
Report | Status Name                       |   Order (ascending)
------ | -----------                       |   ------------------
Gentar  | Assigned                          |    10000
Gentar  | Inspect - Conflict                |    20000
Gentar  | Inspect - Attempt                 |    30000
Gentar  | Inspect - GLT Mouse               |    40000
Gentar  | Inactive                          |    50000
Gentar  | Abandoned                         |    60000

Report | Status Name                       |   Order (ascending)
------ | -----------                       |   ------------------
Imits | Assigned for ES Cell QC           |      007
Imits | Inspect - Phenotype Conflict      |      008
Imits | Assigned for phenotyping          |      009
Imits | Withdrawn                         |      010
Imits | Inactive                          |      020
Imits | Interest                          |      030
Imits | Conflict                          |      040
Imits | Inspect - Conflict                |      050
Imits | Inspect - MI Attempt              |      060
Imits | Inspect - GLT Mouse               |      070
Imits | Assigned                          |      080
Imits | Assigned - ES Cell QC In Progress |      090
Imits | Assigned - ES Cell QC Complete    |      100
Imits | Aborted - ES Cell QC Failed       |      110

#### Assignment Status rules
1. For a gene, if the assignment status exists in one report but not the other, use that value if not null/empty
1. If the gene exists in both reports:
    1. if the gentar value begins with **Assigned**, use that value;
    1. Else, if the gentar value starts with **Inspect**:
         1. If the imits value starts with **Assigned**, use that value;
         1. Else, mark this as a data issue.
    1. Else if the gentar value starts with **Inactive**, **Abandoned**
        1. If the imits value starts with **Assigned**, use that value;
        1. Else if the imits value starts with **Withdrawn**, **Inactive**:
            1. Use the gentar value;
        1. Else mark this as a data issue

### Imits Statuses Mapped
- [x] Aborted - ES Cell QC Failed       
- [x] Assigned - ES Cell QC Complete    
- [x] Assigned - ES Cell QC In Progress 
- [x] Assigned                              
- [x] Chimeras obtained                 
- [x] Chimeras/Founder obtained         
- [x] Conflict                          
- [x] Cre Excision Complete             
- [x] Cre Excision Started              
- [x] Founder obtained                  
- [x] Genotype confirmed                
- [x] Inactive                          
- [x] Inspect - Conflict                
- [x] Inspect - GLT Mouse               
- [x] Inspect - MI Attempt              
- [x] Interest                          
- [x] Micro-injection aborted           
- [x] Micro-injection in progress       
- [x] Withdrawn 

### Gentar Statuses Mapped
- [x] Abandoned
- [x] Attempt Aborted
- [x] Attempt In Progress                               
- [x] Colony Aborted                   
- [x] Embryos Obtained
- [x] Founder Obtained
- [x] Genotype Confirmed
- [x] Genotype Extinct
- [x] Genotype In Progress
- [x] Genotype Not Confirmed
- [x] Inactive
- [x] Plan Abandoned
- [x] Plan Created

### Required gene core fields:
- [x] assignment_status
- [x] conditional_allele_production_status
- [x] crispr_allele_production_status
- [x] es_cell_production_status
- [x] mouse_production_status
- [x] null_allele_production_status
- [x] phenotype_status
- [x] phenotyping_data_available (true if there is at least one data point; false otherwise)

**Comment by ficolo** [comment]
es_cell_production_status
mouse_production_status
phenotype_status
project_status
assignment_status
null_allele_production_status
conditional_allele_production_status
crispr_allele_production_status
phenotyping_data_available: true or false if there is one data point

**Comment by ficolo** [comment]
Imits productions tatus report link:


http://ves-ebi-d6.ebi.ac.uk:4012/imits/v2/reports/mp2_load_gene_interest_report_es_cell.tsv

**Comment by mrelac-ebi** [comment]
This is now done. Great collaborative effort! Thanks all!
