### ISSUE TITLE
Layout issue for Adult expression images

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#519]
A user reported that the layout on the gene page for Adult Expression images using the "Images" layout looks strange:

To reproduce:
1) Navigate to Gene Kif1b details page: https://www.mousephenotype.org/data/genes/MGI:108426 
2) Scroll to the expression section
3) In the embryo expression tb, click the toggle to the image view
4) Display is as follows:

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/d3db3e66-217e-483e-9859-f24fbba16a4f)

Seems to be a bad class on the parent div class="col-sm-6 col-md-3"

**Comment by rwilson-ebi** [comment]
This ticket relates to the expression for embryos - click on the images tab

**Comment by viomunoz** [comment]
Some changes in the front end being made, which will probably affect this.

**Comment by rwilson-ebi** [comment]
This ticket is no longer relevant. The layout of this section has been changed as a result of UX testing.
