### ISSUE TITLE
Significant phenotypes table: some rows have orange font and others black font

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#520]
**Issue:**
some rows have orange font and others black font
Text in some rows appears indented and in others not.

**Requirement:**
Need a consitent view across the table

**Example:** 
https://www.mousephenotype.org/data/genes/MGI:95764

![Screenshot 2021-01-22 at 15.43.16.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3ebbecfa-477f-4a47-a899-140bf8582ee9)

**Comment by jwgwarren** [comment]
Looks like anchor tags are being added for fertility but not other rows? I'll dig further.

**Comment by jwgwarren** [comment]
style is fixed but there is no chart page link. is this on purpose? Where should we link to as presumably this is a line level parameter? trying to figure out how normal table row links work.....

**Comment by jmason-ebi** [comment]
For the moment we do not link fertility rows to charts since we often don't have the underlying data.  Setting this to review, we can open a new ticket if/when we need to implement the fer chart page
