### ISSUE TITLE
Viability icon black but All Data Table shows via data

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#521]
**Issue:**
Icon in phenogrid is black but the All data table shows there is Viability data

**Requirement:**
Icon needs to be orange or blue when data is available.

(Note underlying data in All Data table not displaying at row click, ticket #522)

**Example:**
https://www.mousephenotype.org/data/genes/MGI:95764

![Screenshot 2021-01-22 at 15.55.24.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c0b99c32-ed19-4f88-b7d9-5a9d9d0e9788)

![Screenshot 2021-01-22 at 15.56.02.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/082b4bd1-b0d5-4db5-93cd-70b4a3bfd285)

**Comment by ficolo** [comment]
https://www.ebi.ac.uk/mi/impc/solr/statistical-result/select?q=marker_symbol:Lyst%20AND%20procedure_stable_id:*VIA_002*
https://www.ebi.ac.uk/mi/impc/solr/gene/select?q=marker_symbol:Lyst

**Comment by ficolo** [comment]
https://dev.mousephenotype.org/data/genes/MGI:95764

This has been fixed on DEV, it was an ETL issue:


https://github.com/mpi2/impc-etl/issues/112
