### ISSUE TITLE
All Data Table: viability data not displaying at row click

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#522]
**Isssue:**
Clicking on a row in the All Data should display the underlying data

Please fix.

(Note the phenogrid viability icon is black rather than blue or orange, reported in ticket #521)

Example:
https://www.mousephenotype.org/data/genes/MGI:95764

![Screenshot 2021-01-22 at 15.56.02.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/b7e8eab7-77b2-4285-b4ec-352b3dcf143c)

**Comment by viomunoz** [comment]
The data is not displaying:
![Screenshot 2021-03-02 at 13.38.02.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/0dab5ce0-89b1-492b-895f-9b5b36103d3a)

**Comment by viomunoz** [comment]
Measurement chart not loading:
![Screenshot 2021-03-02 at 13.45.51.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/45fca93a-01e0-4e5a-a21f-a65d9fad5714)

**Comment by jwgwarren** [comment]
Both the front end and back end code has changed for this and I don’t know how to fix this otherwise I would have.

**Comment by viomunoz** [comment]
This has been fixed in dev. 
Example: 
https://dev.mousephenotype.org/data/genes/MGI:95764?dataSearch=VIA 
When you go to all data table and hover over any of the viability rows, it highlights and user can then click on them and be broght to the viability charts, same place as when user clicks on "Viability Data" in top of the Gene page.
