### ISSUE TITLE
Charts page: button "PhenStat-reday raw experiment data" gives an error

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#523]
**To reproduce:**

1. Go here: https://www.mousephenotype.org/data/charts?accession=MGI:97576&parameter_stable_id=IMPC_VIA_001_001&parameter_stable_id=IMPC_VIA_063_001&parameter_stable_id=IMPC_VIA_064_001&parameter_stable_id=IMPC_VIA_065_001&parameter_stable_id=IMPC_VIA_066_001&parameter_stable_id=IMPC_VIA_067_001
2. Click button "PhenStat-reday raw experiment data" 

**Requiremetns:**
Please fix

**Screenshots:**

![Screenshot 2021-01-25 at 13.15.58.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/1a4b5c23-cf80-4c7d-9d02-ad08a5bf8ea5)

===

![Screenshot 2021-01-25 at 13.19.23.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/ae32eb91-986a-45c4-acc3-aa7b95b32f57)

**Comment by jwgwarren** [comment]
There is a null pointer occuring in this streaming bit of code in the method public List<ExperimentDTO> getExperimentDTO(String parameterStableId, String pipelineStableId,
                                                String phenotypingCenter, List<String> zygosities, String strain, String metaDataGroup,
                                                String alleleAccession):

allObservations.addAll(
                    observationService.inflateObservations(
                        Stream.of(dto.getMutants(), dto.getControls())
                                .flatMap(Collection::stream)
                                .filter(x -> !foundSamples.contains(x.getExternalSampleId()))
                                .map(ObservationDTOBase::getExternalSampleId)
                                .collect(Collectors.toList()),
                        parameterStableId,
                        phenotypingCenter
            ));

**Comment by jwgwarren** [comment]
the Set<ObservationDTO> allObservations = new HashSet<>(); is always going to be zero length as it's initialised and then used to generate a stream with nothing filling it with data first?

Passing back to Jeremy as not sure what is supposed to populate this? Maybe i'm being dense?? :)

**Comment by jwgwarren** [comment]
line 115 in ExperimentService

**Comment by jmason-ebi** [comment]
This doesn't appear to be a problem on charts that aren't viability.  Suggest we remove the link from the VIA chart pages since the data is not processed through PhenStat.

Do we need to make the VIA data available via some other method?

**Comment by jmason-ebi** [comment]
Decided to disable the "Phenstat ready" button and have a tool tip saying there is no data for that procedure.
Decided when there is no phenotype call, disable the "Genotype Phenotype raw XML" button and have a tool tip saying there is no data for that procedure.

**Comment by jmason-ebi** [comment]
Done and pushed to master branch
