### ISSUE TITLE
Meeting to discuss representation of HEM viability data in chart pages

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#524]
**Issues:**

- [x] 1. - On the Phka1 viability chart page there should be 41 hem males. The hemi counts are not included in the tables or pie charts:

https://www.mousephenotype.org/data/charts?accession=MGI:97576&parameter_stable_id=IMPC_VIA_001_001&parameter_stable_id=IMPC_VIA_063_001&parameter_stable_id=IMPC_VIA_064_001&parameter_stable_id=IMPC_VIA_065_001&parameter_stable_id=IMPC_VIA_066_001&parameter_stable_id=IMPC_VIA_067_001

See experimental numbers:
https://www.ebi.ac.uk/mi/impc/solr/experiment/select?q=parameter_stable_id:IMPC_VIA_055_001%20AND%20colony_id:TCPR0948_ADPV&rows=1000&wt=json

- [x] 2.- "Associated Phenotype" is missing

- [x] 3.- No entry for HEM genotypes in table

- [x] 4.- Counts not showing in "Statistical result raw XML" or "Genotype phenotype raw XML" (WON'T FIX- disabled button)

- [x] 5.- Clicking on "PhenStat-ready raw experiement data" reports an error (ticket #523)  (WON'T FIX- disabled button)

- [x] 6.- Gene Phka1 missing in Viability Report in FTP site. Fdg1  also missing. Closer inspection reveals all entries under "Total # Hem Males" are "No information available" or "0". (ticket #554)

**Requirements:**
We need to fix this. We need a meeting to agree how to fix this.

Please see other tickets on Viability.

![Screenshot 2021-01-25 at 15.59.47.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/6bcbe89d-e811-41af-9c6d-6a994352329e)

**Comment by viomunoz** [comment]
Harwell and EBI met to discuss issues https://docs.google.com/document/d/1gC_QAcIScc6xIQJ9tz5j6F6Z0xkiv8MoIJLFCTp4wTM/edit#

**Comment by jmason-ebi** [comment]
Need to schedule another meeting to discuss integration of VIA_001 and VIA_002 for consistent reporting in FTP viability report.  Invite Harwell representative.

**Comment by viomunoz** [comment]
Last meeting was March 12: https://docs.google.com/document/d/1gC_QAcIScc6xIQJ9tz5j6F6Z0xkiv8MoIJLFCTp4wTM/edit

**Comment by viomunoz** [comment]
Current display for Fgd1 (X-linked):

![Screenshot 2021-05-07 at 14.59.39.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/ff6fc673-7921-4fed-9141-d2e3df736141)

Current display for Cib2 (autosomal):

![Screenshot 2021-05-07 at 15.00.52.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/37336015-91aa-440d-a646-f8777962877b)

New ticket to reflect this.
