### ISSUE TITLE
Add 2 published pain papers to the pain landing page

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#526]
The pain WG identified that there are 2 publications from the pain WG that have been published.  They would like to see these publications on the landing page:

https://www.mousephenotype.org/understand/data-collections/pain/

URLS:
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/4d55684d-5f44-4366-91bf-47efe6295ded)

**Comment by jmason-ebi** [comment]
Links to the publications:
https://pubmed.ncbi.nlm.nih.gov/32955381/
https://pubmed.ncbi.nlm.nih.gov/33230005/

**Comment by viomunoz** [comment]
This has been done:
https://www.mousephenotype.org/understand/data-collections/pain/

**Comment by jmason-ebi** [comment]
The pain WG chair will also provide updated text for the landing page and we should time the release of the updated text so as to coincide with the publication of the 3rd manuscript.
