### ISSUE TITLE
 New page (or a modal) to display a list of the FCS files to download from the DCC servers

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#527]
The images section shows a missing images placeholder for FCS files and the link of those images is broken:

![Screenshot 2021-01-27 at 09.08.51.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/67eb5e04-f834-4e3b-959c-04965afee299)

At least one user has expressed interest on downloading the FCS for:

https://www.mousephenotype.org/data/genes/MGI:99779

Currently we do not support FCS files display on the web browser. The links on the images section corresponding to FCS files should open a new tab with a list of the FCS files available for download for the Gene-Parameter pair.

![Screenshot 2021-01-27 at 09.11.59.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/808a77e5-997a-47fd-a9dc-f34ea57a9605)

![Screenshot 2021-01-27 at 09.12.24.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/af422771-193a-4137-ab4b-654aa5764f28)

**Comment by viomunoz** [comment]
Thank you, this looks good!
