### ISSUE TITLE
Oligo page broken

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#529]
An external researcher reported a broken oligo design through the RT system. Would you be able to have a look?

Here are the details:
Hello, I am trying to access the oligo design link for the Acly vector found here: https://www.mousephenotype.org/data/designs/184180?accession=MGI:103251

But I am receiving an error that the page does not exist.

To reproduce:
1) Navigate to https://www.mousephenotype.org/data/genes/MGI:103251
2) Scroll to the Order section https://www.mousephenotype.org/data/genes/MGI:103251#order
3) Expand the Allele Acly tm184180(L1L2_Bact_P)
4) Click on any of the "oligo design" links

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/5b731263-4566-47b9-bb92-5a9d79f1755a)

**Comment by jwgwarren** [comment]
fixed - changed designId back to design_id. we could probably specify the parameter using spring explicitly - but this works and is probably less error prone - guess that is debatable.
