### ISSUE TITLE
About IMPC: provide NIH funding numbers

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#53]
Funding- we should give the current KOMP NIH funding numbers

**Comment by jmason-ebi** [comment]
Is this static content related?  We need to have a page on the wordpress site to detail the numbers.

**Comment by viomunoz** [comment]
Please can you provide URL?

**Comment by jmason-ebi** [comment]
Probably should go here:

https://www.mousephenotype.org/about-impc/funding/

**Comment by viomunoz** [comment]
Some grant numbers have been added, but it is recognized that it is difficult to keep track of this and obtain a complete list.
