### ISSUE TITLE
Automate build and deploy of product core

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#532]
As a user I want to see up-to-date information about the products available from the IMPC.

the general workflow for this is:
1) Centers update Imits with the product information available, and from where
2) Nightly, iMits produces a report that contains the complete set of products available from iMits (This will have to be expanded to gentar)
3) The product core is generated from the iMits report
4)  The product core is validated, and if passing, deployed to the staging and live servers

**Comment by mrelac-ebi** [comment]
Done. There are two one-click Jenkins jobs:

- One to build and deploy to DEV and STAGING: [IMPC_eg_build_pipeline](http://ves-ebi-d9.ebi.ac.uk:8080/jenkins/view/Essential%20Genes/job/IMPC_eg_build_pipeline/)
- One to build and deploy to DEV, STAGING, and LIVE: [IMPC_build_eg_solr](http://ves-ebi-d9.ebi.ac.uk:8080/jenkins/view/Solr%20EG/job/IMPC_build_eg_solr/)
