### ISSUE TITLE
Essential genes portal: column order

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#534]
Revision of tool: https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes 

**Requirements:**
Update from ticket #354
Order looking good, can we have these as it will be helpful for users:

- Input column
- Good to have achilles gene effect next to viability information (cavcategory) and fusil information (f columns), as these are directly related.
- As there is also the allele, let's have this order as it will be more logical to users: o_support_count, cav_allele_symbol, cav_category, achilles_mean_gene effect, f_bin, f_bin_code

**Comment by ficolo** [comment]
I've added the input_match column and it will be visible when there is some input. When the input box is empty and the table is showing all the data we have, the input_math column is not displayed.
