### ISSUE TITLE
Essential genes data portal: help page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#537]
Update from ticket #490.
User's documentation is here, section "User's documentation":
https://docs.google.com/document/d/1uveWn1H6nDv8hES0mgIOgelFVzHi2xwid3RljFvyHFE/edit#heading=h.og9a91szx8kf

**Comment by jmason-ebi** [comment]
This has been integrated onto the web portal help section here:
https://www.mousephenotype.org/help/data-integration/how-to-use-the-essential-genes-data-portal/
