### ISSUE TITLE
Essential genes data portal: output table

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#541]
Revision of tool: https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes 

**Requirements:**
Update from ticket #354

Order of rows to match gene order in input list - helpful for users

**Comment by ficolo** [comment]
I don't think this is gonna be possible for the mean time, the pagination is done on the server, and I don't see how do the sorting on the server side without getting all the results in one gone, which beats the whole purpose of the pagination. 


As an alternative I could sort the user input alphabetically and then sort the table alphabetically by the input_match column.

**Comment by viomunoz** [comment]
Sorting rows alphabetically by input names seems a very good solution to me, both for the display table in the website and the downloaded table. Makes it easier for users to locate particular genes quickly, including when using the pagination functionality in the website. Sometimes users may want to check output for specific genes to decide whether the app is useful for them. An aphabetic order is thus very useful to locate them.
What about columns? Can the column order in the downloaded table be matched to the one we have discussed for the display table?
Thanks!

**Comment by viomunoz** [comment]
Sorry, sorting is not working properly... not sure if I did not get the update...

I am working here to do the validations: https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes

See for example this list: 
MGI:101919
MGI:103287
MGI:106388
MGI:109241
MGI:1921357

I see:

- Order is not ascending or descending 
- Genes with same ID are not together

NOTE - some rows are duplicated it looks like, same output for both (writing a separate ticket for this, mentioning it here in case it has an influence)

![Screenshot 2021-02-09 at 13.50.49.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/04202ff9-098d-4d8e-a5a3-bf446a1dd71a)
