### ISSUE TITLE
Essential Genes Data Portal deployment setup

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#546]
The essential genes data portal will be deployed to Kubernetes using a Docker container to serve the Angular app via nginx

- [x] Create a Dockerfile packaging the app in a nginx server

- [x] Check that the routing strategy works fine inside the nginx server

- [x] Publish the project to GitLab

 - [ ] Validate the warnings are either innocuous, or fix them.

- [x] Solr URL needs to be configured to an externally available on the production k8s instance

**Comment by jmason-ebi** [comment]
Vulnerabilities in the build identified and fixed.  Some warnings remain which we will look into.

**Comment by jmason-ebi** [comment]
It is currently being deployed, there are still some warnings (do we need to address these?).

We are now up to the part where we need to have the loadbalancer routing added.
