### ISSUE TITLE
Viability data badge on Gene page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#547]
**Requirement:**

Remove the viability category badge/s (lethal/subviable/viable) on the Gene page (see screenshots below [1] and [2]) and replace with a single badge with 2 states:
   - Viability data available
   - Viability data not available

--------------------------------------
**Background information:**
- We currently present a viability category on the Gene page: see screenshots below [1] and [2] 
  - However, we do not clarify whether this is a HOM or sex specific call - it has been discussed whether this needs to be clarified
  - These are not MP terms
- Preference to *not* call things “viable” for VIA_002 
  - There is no MP term for “Viable”
  - The stats test doesn’t test that something is viable…. The test is testing if there are fewer pups than expected
- The DCC QC process will ensure that there are enough data (always) to determine the “no abnormal phenotype detected” MP term when testing for HOM viability
  - Need to differentiate between “not enough power to detect” and “not detected” when other categories tested e.g. female HOM viability or male HOM viability

**Note:**

The “Viability data available” will be a link to the charts page showing **_all_** viability charts / data for this gene
  - We will need to update the charts page to be more clear 
  - See ticket #531
  - Include a summary of the data available at the top - see ticket #548

**Drawbacks:**

- How do we ensure that the users draw a conclusion, how does the user know that the data leads to a specific phenotype call ?

  - The phenotype call can be found on the chart page and on MP table on Gene page (when significant) as currently implemented.

------------------------------------- 

**Screenshots:**

[1] Here’s what it looks like currently when a gene is “lethal” and/or “subviable”:

![Screenshot 2021-02-12 at 12.30.46.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/f9da63e9-b582-4e84-a0f4-1a3240ef0b1a)

[2] When a gene is not lethal or subviable, we report "viable":

![Screenshot 2021-01-28 at 18.38.35.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/d21b5a8a-03ad-4d22-a126-b0c8452eba2f)

**Comment by jwgwarren** [comment]
done and pushed. Viability links may not be sufficient as no ones for VIA_2 params?
