### ISSUE TITLE
Chart pages: explanatory text 

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#548]
**Issue:**
We want to link to all viability-related chart pages from the Gene page when badge “Viability data available” is presented.
This will be a link to the charts page showing **_all_** viability charts / data for this gene - see ticket #547.

**Requirement:**
- We will need to update the charts page to be more clear 
- We need to include a brief summary at the top to guide users about the results presented here
- See also ticket #531
- Can we make this text sufficiently generic to fit all cases in which we present more than one chart (e.g. same MP / phenotype call from different parameters) or should we have specific text tailored for different situations?

**Text could be presented in a green box and be something like this:**

> There are n charts below. 
> Please note:
> - data for different alleles measured in different centers correspond to different colonies and thus will be presented separately
> - phenotype calls are made for abnormal phenotypes

**Comment by viomunoz** [comment]
See ticket #172 on this topic, too.

Message clafriying the number of charts available should not be part of the title, but be placed below the title.

Looking throughout the website, it seems we use:
- grey boxes to give more information about experiments
- bluish boxes for navigation instructions
- green boxes for stats results
- yellow boxes for explanations / clarifications.

I am leaning towards a grey box, other opinions welcome.

Example with all type of boxes:
https://dev.mousephenotype.org/data/charts?accession=MGI:1929293&allele_accession_id=MGI:5548707&zygosity=homozygote&parameter_stable_id=IMPC_ACS_006_001&pipeline_stable_id=HRWL_001&procedure_stable_id=IMPC_ACS_003&parameter_stable_id=IMPC_ACS_006_001&phenotyping_center=MRC%20Harwell
Another example, on the "Measurements chart" tab, bluish box:
https://dev.mousephenotype.org/data/genes/MGI:2153589#phenotypesTab

**Comment by jwgwarren** [comment]
I've added a yellow box which by our web design is an alert-warning whereas the blue box is an alert-info whereas our badges have different colours for warnings and info :) One of these is probably a hangover from old design.

Anyway it's done now for each viability pie chart set on a page it will display that message - which I guess is ok as if you are scrolled down you can see it.

**Comment by viomunoz** [comment]
- Will need the summary on charts being presented, as in ticket #172. Assuming this will be one day in the chart pages.
- The message as it states now is not clear, as normal / abnormal phenotype calls has nothing to do with the number of charts.
- Better not to have an "IF" statement about whether there is more than one graph, because sometimes there is only one

Thus, suggestion to change:
= = =
If there are a number of charts below for viability data please note:

- data for different alleles measured in different centers correspond to different colonies and thus will be presented separately
- phenotype calls are made for abnormal phenotypes

= = =
to this:
= = =
Please note:

- data for different colonies will be presented separately (e.g. different alleles; same allele but different background strain; same allele but in different phenotyping centers)
- phenotype calls are made when a stastically signficant abonormal phenotype is observed (that is, preweaning lethality or absence of expected number of homozygote pups based on Mendelian ratios)

= = =
Do we want the clarification within the brackets or is this too much text for a yellow box?
= = = 


![Screenshot 2021-04-09 at 11.57.56.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/f6b51a2b-580f-4cc2-8a90-fc6a00e7876b)
