### ISSUE TITLE
Deploy the Essential Genes tool to production

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#549]
We need to deploy the essential genes portal to the live site.  This will be linked to from the essential genes portal ( https://www.mousephenotype.org/understand/data-collections/essential-genes-portal/ ).

- [x] Build gitlab pipeline to mirror the github code and build the project
- [x] Establish proper location on production kubernetes cluster
- [x] Set up routing rules to expose the EG query interface under https://www.mousephenotype.org/data/essential-genes-query
- [x] Link from the essential genes landing page
- [ ] Use the portal to power the graph on the essential genes landing page
- [x] Link from the advanced tools section of the menu

Currently the tools exists on dev at: https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes

**Comment by viomunoz** [comment]
See tickets #375 and #546 for further details on this.

**Comment by viomunoz** [comment]
For the time being, we are not going to use the portal to power the graph on the essential genes landing page. This will be implemented together with the new architecture of the web site.
