### ISSUE TITLE
Disable buttons on search page when data not available

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#550]
On the search page currently, the "Order Mice" and "View data" buttons are functional even when there is no data to support

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/d68ff6a9-3764-4d0f-b2c7-57d2aee8544c)

The user interface should indicate that there actually isn't data by disabling the button and greying it out.  With a hover that says "Data not available"

https://www.mousephenotype.org/data/search?term=gm29106&type=gene

**Comment by viomunoz** [comment]
This has been fixed in dev:
https://dev.mousephenotype.org/data/search?term=gm29106&type=gene
![Screenshot 2021-11-09 at 17.38.25.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/0289509b-f00e-4d85-abc5-5d422bdc74ec)
