### ISSUE TITLE
Batch query download breaks with Human gene symbols list

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#553]
User reports getting an error when they try to download a batch query. The preliminary return of 10 entries looks good but it fails when they click on download xls or tvs. They have 85 human gene symbols in my search list.

![Screen Shot 2021-02-25 at 9.58.09 AM.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/efd06108-b583-4780-8389-dc8a20276026)

This issue seems to be already solved on DEV by changes made after the latest web release.

We need to do a web release as soon as possible. Please beware that this web release has to go simultaneously with the new Gene Core schema described on [518](https://github.com/mpi2/PhenotypeData/issues/518).

**Comment by mrelac-ebi** [comment]
Fixed, tested, and deployed to LIVE.
