### ISSUE TITLE
Viability: data missing in FTP report

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#554]
**Problem:**

- Genes missing in Viability Report in FTP site but viability data is available in website. For example, 
  - Phka1 
https://www.mousephenotype.org/data/charts?accession=MGI:97576&parameter_stable_id=IMPC_VIA_001_001&parameter_stable_id=IMPC_VIA_063_001&parameter_stable_id=IMPC_VIA_064_001&parameter_stable_id=IMPC_VIA_065_001&parameter_stable_id=IMPC_VIA_066_001&parameter_stable_id=IMPC_VIA_067_001
  - Fdg1
https://www.mousephenotype.org/data/charts?accession=MGI:104566&parameter_stable_id=IMPC_VIA_001_001&parameter_stable_id=IMPC_VIA_063_001&parameter_stable_id=IMPC_VIA_064_001&parameter_stable_id=IMPC_VIA_065_001&parameter_stable_id=IMPC_VIA_066_001&parameter_stable_id=IMPC_VIA_067_001

- In case this helps to track the bug: these two genes also show no VIA data in the EG Data Portal.

**Requirement:** 
Report to contain the same information as the website.

**Comment by mrelac-ebi** [comment]
As of 05-Mar-2021, for IMPC_VIA_002, the experiment core has:
- 611 documents for IMPC_VIA_002::IMPC_VIA_055_001 ("Hemizygous male")
- 611 documents for IMPC_VIA_002::IMPC_VIA_056_001 ("Anzygous female")

Each of these genes has 2 HEMI and 2 ANZYGOUS documents:
- Ap4e1
- Dbn1
- Nxn
- Prkab1
- Satb2
- Tox3

This URL retrieves all HEMI and ANZYGOUS documents: http://ves-ebi-d0.ebi.ac.uk:8986/solr/experiment/select?facet.field=gene_symbol&facet=on&fl=gene_symbol,parameter_stable_id&q=(parameter_stable_id:IMPC_VIA_055_001%20OR%20parameter_stable_id:IMPC_VIA_056_001)AND%20procedure_stable_id:IMPC_VIA_002&rows=0

**Comment by mrelac-ebi** [comment]
As of 22-Apr-2021 (DR14), for IMPC_VIA_002, the experiment core has:
- 645 documents for IMPC_VIA_002::IMPC_VIA_055_001 ("Hemizygous male")
- 645 documents for IMPC_VIA_002::IMPC_VIA_056_001 ("Anzygous female")

Each of these genes has at least 2 HEMI and 2 ANZYGOUS documents:

- Ap4e1
- Dbn1
- Nxn
- Prkab1
- Satb2
- Tox3

**Comment by mrelac-ebi** [comment]
Closing this ticket, as we now have IMPC_VIA_002 hem male data.
