### ISSUE TITLE
Resolve problem with Jenkins running omero jobs

### ISSUE THREAD

**Issue by kbab** [mpi2/PhenotypeData#562]
Late last year / earlier this year (Dec 2020 - Feb 2021) Kola noticed Jenkins was unable failing to run some omero jobs that involved use of ICE (the communication protocol library) e.g. Uploading images to Omero ( http://ves-ebi-d9:8080/jenkins/job/temp_upload_images_to_omero/ ). However, manually running the job as mi_adm on ves-ebi-cf works.

This problem arose again on Friday/Saturday 19/02/2021 - 20/03/2021 when ves-pg-ca (one of the omero production servers) crashed and Jenkins was trying to restart it. The restart kept failing with an error about ICE. Kola manually logged into the server and ran the same restart script Jenkins was attempting to run and it worked fine.

It seems there is a problem with the environment when Jenkins is attempting to run some scripts. However, this problem was not apparent before December 2020. Did something change on the EBI IT infrastructure? Did we make a change to our config / Jenkins within mouseinformatics?

At any rate we need to fix the issue.

**Comment by jmason-ebi** [comment]
Ongoing.  @mrelac-ebi has suggested a permissions issue might be causing the issue.
