### ISSUE TITLE
Install latest Omero on Kubernetes

### ISSUE THREAD

**Issue by kbab** [mpi2/PhenotypeData#563]

**Comment by kbab** [comment]
We have been provisioned with a new VM (wp-np2-2d) of similar spec to the current omero dev server (ves-ebi-cf). We need to install the current latest version of Omero on this and get all the relevant scripts working with this version.

**Comment by jmason-ebi** [comment]
Postponed because we're trying to deploy OMERO on kubernetes.

**Comment by kbab** [comment]
We decided to prioritise deployment using Kubernetes.

**Comment by rwilson-ebi** [comment]
NFS mount is not available within the cluster yet - will chase systems next week.

RT ticket 
http://helpdesk.ebi.ac.uk/Ticket/Display.html?id=512721

**Comment by viomunoz** [comment]
Still in progress.
