### ISSUE TITLE
DR 14.0 - Web release 

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#564]
Need to have the multiple small fixes to the master branch deployed to the production servers.

Plan to have this complete by **March 31, 2021**
- [x] Merge all changes into the master branch that should be deployed
- [x] Collect release notes
- [x] Schedule meeting to pair program the release so Mike can demonstrate the process

**Comment by viomunoz** [comment]
is this done?

**Comment by mrelac-ebi** [comment]
Done. I created a confluence page entry with a Zoom video and written instructions under the title [General Web Release](https://www.ebi.ac.uk/seqdb/confluence/dosearchsite.action?searchQuery.queryString=ancestorIds%3A15110424+AND+general+web+release&searchQuery.spaceKey=MouseInformatics).
