### ISSUE TITLE
Data release 14.0 - image upload

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#568]
Hopefully this is the last data-release before we upgrade to the latest version of Omero (5.6). The media headstart allowed us to download over 100K images before we received the XMLs from the DCC. However, there were some last minute submissions mainly from UCD and ~40K images are to be uploaded into Omero.

The steps are:
1. Download images from DCC using csv provided by Federico
2. Verify integrity of images
3. Upload to Omero
4 Generate thumbnails (we may have to do this on production servers to meet the data-release launch date)
5. Move to Staging
6. Move to ves-oy-ca
7. Move to ves-pg-ca

**Comment by kbab** [comment]
Hopefully this is the last data-release before we upgrade to the latest version of Omero (5.6). The media headstart allowed us to download over 100K images before we received the XMLs from the DCC. However, there were some last minute submissions mainly from UCD and ~40K images are to be uploaded into Omero.

The steps are:
1. Download images from DCC using csv provided by Federico
2. Verify integrity of images
3. Upload to Omero
4 Generate thumbnails (we may have to do this on production servers to meet the data-release launch date)
5. Move to Staging
6. Move to ves-oy-ca
7. Move to ves-pg-ca

**Comment by jmason-ebi** [comment]
Ongoing
