### ISSUE TITLE
Data release 14.0 - Production Release

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#570]
Push the finalized data to production
- [x] Integrate Tomasz' disease core (must be done before next step)
- [x] Run the ftp build and deploy process to create reports, cores, and database
- [x] More to come ...

**Comment by jmason-ebi** [comment]
Need to generate the reports and FTP directory @mrelac-ebi

**Comment by mrelac-ebi** [comment]
DR14 is complete. Tomasz' new core is in place and the ftp reports, cores, and database are all installed.
