### ISSUE TITLE
Disease section in Gene page: Implementing new design

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#574]
Following meeting with User Expert today, we will implement the following design in the DEV or BETA section of the website.

![Screenshot 2021-04-08 at 16.31.10.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/47194da9-a838-4c7e-ab04-e62298dd60c3)

**Comment by viomunoz** [comment]
I think having "Matching phenotypes (HPO)" or "Matching phenotypes (HP terms)" will be clarifying for the experienced users as well as new users when digging deeper into the data,  as elsewhere in the Gene page we display MP terms.

**Comment by jmason-ebi** [comment]
Done.  Tomasz produced a version of the phenodigm core that includes the HPO terms and it is now deployed on beta
