### ISSUE TITLE
Bug in thumbnail generation

### ISSUE THREAD

**Issue by kbab** [mpi2/PhenotypeData#583]
For some reason, some thumbnails are not being displayed despite existing in Omero. The problem may be to do with the use of "render_birds_eye_view". e.g. see: [https://wwwdev.ebi.ac.uk/mi/media/omero/webgateway/render_birds_eye_view/943501/](https://wwwdev.ebi.ac.uk/mi/media/omero/webgateway/render_birds_eye_view/943501/) which gives an error. The link points to dev, but there are similar problems on prod (ves-pg-ca) which is stranger as the bird's eye view does not work, but the thumbnail does - [https://www.ebi.ac.uk/mi/media/omero/webgateway/render_thumbnail/943501/](https://www.ebi.ac.uk/mi/media/omero/webgateway/render_thumbnail/943501/) seems ok, but [https://www.ebi.ac.uk/mi/media/omero/webgateway/render_birds_eye_view/943501/](https://www.ebi.ac.uk/mi/media/omero/webgateway/render_birds_eye_view/943501/) does not!

**Comment by kbab** [comment]
Closed as same as #519

**Comment by kbab** [comment]
Reopened - NOT the same as #519 !

**Comment by rwilson-ebi** [comment]
Can you comment on whether this will be solved in the new version of OMERO

**Comment by kbab** [comment]
The issue seems to have been resolved with data-release 15. It was probably due to inconsistencies during the thumbnail generation stage of data-release 14. To speed things up the thumbnails were not generated on 'dev' as usual, but we generated them independently on each of the two production servers.

This should not be an issue with the new version of Omero
