### ISSUE TITLE
Legacy images not displaying on pg and wp-p1m-d6

### ISSUE THREAD

**Issue by kbab** [mpi2/PhenotypeData#586]
**Bug description**
Some legacy images on live are not being displayed when requested from ves-pg-d8 and wp-p1m-d6.

**Link**
[https://www.mousephenotype.org/data/images?gene_id=MGI:1914061&fq=expName:Xray](https://www.mousephenotype.org/data/images?gene_id=MGI:1914061&fq=expName:Xray)
[http://ves-pg-d8.ebi.ac.uk:8080/mi/impc/phenotype-archive/media/images/1617/I20150818100210_download_tn_large.jpg](http://ves-pg-d8.ebi.ac.uk:8080/mi/impc/phenotype-archive/media/images/1617/I20150818100210_download_tn_large.jpg)
[http://wp-p1m-d6.ebi.ac.uk/mi/impc/phenotype-archive/media/images/1617/I20150818100210_download_tn_large.jpg](http://wp-p1m-d6.ebi.ac.uk/mi/impc/phenotype-archive/media/images/1617/I20150818100210_download_tn_large.jpg)
 
**Screenshot(s)**
![Screenshot from 2021-04-27 16-50-29.png](https://images.zenhubusercontent.com/5e3bfc2576e5185cb9df2df4/61cb8d0f-84df-4ae5-904c-a70107b24578)

**Comment by kbab** [comment]
Emailed @jmason-ebi about possible solution. Agreed to rsync oy version of /nfs/public/ro/mousephenotype/images/ with pg version. However, before doing this I will do a manual comparison of the files in the following ways:

1. On oy compare rw and ro i.e. /nfs/public/ro/mousephenotype/images/ and /nfs/public/rw/mousephenotype/images/ and ensure the superset of all files are on both
2. on pg compare rw and ro as in [1]
3. Compare rw on oy and pg and copy missing from oy to pg - rsync
4. Copy missing from pg rw to pg ro
5. Ensure that wp-p1m-d6 is ok as well (I assume it shares the same mount as pg)

**Comment by rwilson-ebi** [comment]
Kola wrote to systems about the permissions issue
Jonathan thought there is a Jenkins job that carried out this task - talk to Jeremy about how Jenkins job is backed up

**Comment by rwilson-ebi** [comment]
Snapshot in read only directory in pg and oy - sync command updates oy but not pg
command produces non zero exit code
Kola email James Hayhurst - showed Kola link to the documentation
Doing the correct steps 

Next step - review with Jeremy and Robert and then contact systems

**Comment by kbab** [comment]
Systems have fixed the issue - they apparently 'updated our policy on source isilon'. The link for the ticket raised with IT is http://helpdesk.ebi.ac.uk/Ticket/Display.html?id=499689.

Verified that the images are being served from both ves-pg-d8 and wp-p1m-d6
