### ISSUE TITLE
Upgrade old hardware

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#591]
### Description
Systems has advised us that VM hosts ves-* should be upgraded to new VMs. This ticket captures that work.

The following mouseinformatics hosts need upgrading:
- [x] ves-ebi-d0 (need 1 VM to host mi-dev-apps)
- [x] vex-hx-d1 (need 1 VM to host mi-beta-apps)
- [x] ves-hx-d8 (need 2 VMs to host mi-staging-apps and mi-staging-solr)

Once these hosts are assigned, the applications and files on the old hosts need to be migrated to the new hosts.

**Comment by jmason-ebi** [comment]
@mrelac-ebi Can you please update the status of this?

**Comment by mrelac-ebi** [comment]
An authorised person (@rwilson-ebi @jmason-ebi?) needs to request these hosts.

**Comment by jmason-ebi** [comment]
@rwilson-ebi has requested all hosts and I have approved the requests.

**Comment by jmason-ebi** [comment]
All resource requests complete.

**Comment by rwilson-ebi** [comment]
Name: wp-np3-81 (mi-beta-apps)
Name: wp-np3-82 (mi-staging-apps)
Name: wp-np3-83 (mi-dev-apps)
Name: wp-np3-84 (mi-staging-solr)

**Comment by jmason-ebi** [comment]
Verified our virtual users can login to all hosts

**Comment by mrelac-ebi** [comment]
All hosts have been upgraded and applications ported: Jenkins, MI_DEV, MI_BETA, MI_STAGING, MI_STAGING_SOLR
