### ISSUE TITLE
Upgrade PhenotypeArchive web app

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#599]
### Description
1. Upgrade project compiler to jdk 11
1. Upgrade to latest Spring Boot 2.4.0. This requires upgrading all junit4
   tests to junit5 (Spring Boot requirement)

**Comment by rwilson-ebi** [comment]
H2 database sa user and blank password has changed
- issue with the configuration service has changed
- not wired into Spring Boot 2.4 as well
- changed the hierarchy of configuration - looking into moving to YAML configuration
- Need to be selective about what Spring components and Spring Cloud version.

Have a meeting to discuss removing the configuration server and using Kubernetes environment variables
- many fewer properties now.

**Comment by rwilson-ebi** [comment]
In the spring-boot-jsp branch we have an embedded tomcat server and the webapp can be built as a jar.
Requires Java 11 rather than Java 16.

Work on session cookies to integrate into the RI database.

Next step to remove the config server dependency.
