### ISSUE TITLE
Gene core has swapped Spag6 and Spag6l mgi accession ids

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#604]
The gene core is incorrectly swapping Spag6 and Spag6l MGI accession ids.
MGI defines these two genes as follows:
- Spag6   MGI:3040687
- Spag6l  MGI:1354388

but the gene core has swapped them:
- Spag6   MGI:1354388
- Spag6l  MGI:3040687

The gene core needs to map to the correct mgi accession id.
The daily gene core build was not correctly downloading the mgi reports to hadoop. That problem was fixed on 26-May-2021. However, the gene core is still mis-mapping these two genes. The fear is that the bad gene core data has propagated throughout the rest of the ETL core build.
- [x] [DEV gene core](http://wp-np2-e1.ebi.ac.uk:8986/solr/gene/select?q=mgi_accession_id:(%22MGI:1354388%22%20OR%20%22MGI:3040687%22)) shows correct mapping.

**Comment by rwilson-ebi** [comment]
The expectation is that this will be fixed in Data Release 15

**Comment by rwilson-ebi** [comment]
requires testing on the web site for DR15

**Comment by rwilson-ebi** [comment]
Checked this is fixed in DR15
