### ISSUE TITLE
Remove 'blah' from popups of control pdf annotations

### ISSUE THREAD

**Issue by kbab** [mpi2/PhenotypeData#610]
This is a minor but irritating issue where the phrase 'blah' appears in pop-ups when a user hovers over some wildtype annotation thumbnails. A similar issue was reported for some images by Ruairidh on 27/04/2021 @ 13:34, but it seems these have been fixed. This ticket aims to fix the issue for annotations and in other areas where it may occur by searching for the phrase 'blah' in the source code and updating it as necessary.![Screenshot from 2021-06-08 14-20-39.png](https://images.zenhubusercontent.com/5e3bfc2576e5185cb9df2df4/fe1c95f6-c1f1-4dc7-a62a-54c3be1d9f0b)

**Comment by rwilson-ebi** [comment]
Please add a link so we can reproduce and check this issue

**Comment by kbab** [comment]
Example link: [https://www.mousephenotype.org/data/imageComparator?&parameter_stable_id=IMPC_ABR_014_001&acc=MGI:1351343&mediaType=pdf](https://www.mousephenotype.org/data/imageComparator?&parameter_stable_id=IMPC_ABR_014_001&acc=MGI:1351343&mediaType=pdf)

**Comment by viomunoz** [comment]
Just tested this and you can see this in Firefox.

**Comment by viomunoz** [comment]
Image display has been changed, so this is no longer an issue.
