### ISSUE TITLE
UK Biobank: mappings between IMPC and UKB blood and cc parameters

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#616]
In March 2020, in a quick pass, the mappings between IMPC blood and CC parameters and those in the UK Biobank were done. These are here: 
https://drive.google.com/drive/folders/1ecoRbtV73YyzqQT9JxpZ7gu_cYGF23IF?usp=sharing

**Team met and agreed on the following steps:** 

1) Take the blood and clinical chemistry parameters collected by the IMPC (2 procedures) (download anew from IMPRESS)

2) Take the blood and biochemical parameters collected by the UKB (download anew from the UKB website)

See the “Resources” tab in the following data sections:

Category 100081
Blood count - Blood assays - Biological samples
https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=100081
Description
This category contains results of haematological assays that were performed on whole blood before further processing. This category includes data on acquisition time and number of freeze-thaw cycles and count for: basophils, Eosinophils, Monocytes, Neutrophils, Haematocrit, Haemoglobin, Red Blood Cells, Lymphocytes, White Blood Cells, Platelets, Reticulocytes, Mean Sphered Cells Volume and Mean Corpuscular Volume.

Category 17518
Blood biochemistry - Blood assays - Biological samples
https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=17518
Description
A range of key biochemistry markers were measured in the blood sample collected at recruitment (for all 500,000 participants) and at repeat assessment approx. 5 years later (for 20,000 participants). The biomarkers were selected for analysis because they represent established risk factors for disease, are established diagnostic measures, or characterised phenotypes not otherwise well assessed and are feasible to measure at scale.  

3) Compare names and definitions to see which ones are equivalent by collecting the following information. **The end product is an Excel table with potentially these columns**:
ukb_parameter    code    instances    sample_type    measuring_units    processing_method    equipment
impc_parameter    sample_type    measuring_units    processing_method    equipment

**Comment by rwilson-ebi** [comment]
Python scripts and CSV files created. Requires validation of the matches by the group.

**Comment by viomunoz** [comment]
We have mappings in place now to move forward.
