### ISSUE TITLE
Fertility data not visible

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#62]
FER does not display anything other than the submitted outcomes on the gene page  (and not even those on the data pages), even if we received supporting data in the XML: http://www.mousephenotype.org/data/experiments?geneAccession=MGI:3712553 

(Filter procedure = fertility, no raw data links etc)

Can we display values for both of IMPC_FER_001_001 and IMPC_FER_019_001? (both mandatory)

If we have additional numerical parameters would be nice to display them too, but they are often not submitted

**Comment by viomunoz** [comment]
Updated link: https://www.mousephenotype.org/data/genes/MGI:3712553

**Comment by viomunoz** [comment]
Clicking on the All Data table for the Fertility data, brings you the Measurements chart tab rather than displaying any data:

![Screenshot 2020-03-09 at 20.59.50.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/a97cbfcb-1af5-4bda-989e-8fb2744aadfd):

**Comment by viomunoz** [comment]
This behaviour is confusing. As a user I do not know what I should do next. I can think what it is that I need to find in the measurements chart. I filter for "Reproductive sytem", but fertility is not there. I filter for "Mortality/Aging" and I see the image below. 

**Probably we would like that the user can only click on a row on the table when underlying data is available.** 

![Screenshot 2020-05-04 at 11.08.50.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/15f22a7c-0152-4872-92c4-dfc9f1ed42cc)

**Comment by jmason-ebi** [comment]
After discussion, decided that the best solution here is to link from the all data table row to a charts page (just like every other data type) and the chart shows the data when it's available, otherwise says "no data".

**Comment by viomunoz** [comment]
Note it is Pramel15;  Synonyms: EG627009, Gm13125, Pramef2
http://www.informatics.jax.org/marker/MGI:3712553

**Comment by viomunoz** [comment]
Do we have any example of a gene with a chart page displaying fertility data?

**Comment by viomunoz** [comment]
This ticket has been replaced by ticket #406. Closing this ticket.
