### ISSUE TITLE
Essential Genes data portal: is there a limit on the number of genes it can handle?

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#629]
**Issue:**
I loaded from file 5,116 genes here:
https://www.ebi.ac.uk/mi/impc/essential-genes-search/
 and I got the message "No results found" (see attached screenshot, below).
Before this, I tried the 19,000+ protein coding genes, the same happened.

**Requirement:**

- If there is a limit on the number  of requests we can process, we need to explicitly mention it in the website.
- Ideally we may want the portal to be able to handle a request comprising 1,000 genes? (Bare in mind output file will likely have more than 1,000 rows when orthologues are requested.) 

![Screenshot 2021-07-15 at 16.41.06.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3ca05af9-9e60-4f18-900b-b4a4b29cfc38)

**Comment by rwilson-ebi** [comment]
We need to investigate the query string length and the number of results requested per request to the Solr endpoint.

**Comment by viomunoz** [comment]
We will check the maximum number of genes the app can handle and release with an indication in the portal about this.

**Comment by viomunoz** [comment]
The portal is returning the number of rows we expect for sets of 100 genes. However, there is an incosistency between the number of rows the portal reports and the number of rows in the file.
For 3 different sets of 100 HGNC genes that were submitted:
1. Message on portal is "Showing 1 to 10 of xxx" with xxx being 303, 125 and 193, respectively
2. After clicking Download, message on portal is "Downloading xxx rows" (xxx as above)
3. Resulting files has 328, 191 and 306 rows, matching our expectation (matching number of rows in a file generated using scripts for manually downloaded files from the different sources (HGNC, HCOP, etc.).
One option to be able to release the EG portal is to display a message requesting users to restrict their requests to 100 genes and that we are working on increasing this number.

**Comment by viomunoz** [comment]
Discussed internally, new ticket to address this issue.
