### ISSUE TITLE
UK Biobank project: download bulk data

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#635]
Now that we have folder encryption in place, we can download the bulk data.

**Comment by viomunoz** [comment]
Waiting for the new EBI infrastructure.

**Comment by viomunoz** [comment]
We need to check the new way in which UKB data is being shared.

**Comment by rwilson-ebi** [comment]
Should do this in the Noah cluster ASAP due to the requirement to login.

**Comment by viomunoz** [comment]
Team failed to download the bulk (exome) data due to access requirements, UKB has been contacted about this.

**Comment by viomunoz** [comment]
Still waiting for UKB to provide access.

**Comment by viomunoz** [comment]
UKB Access Management Team contacted yesterday again, asking for the status of this request in which we are asking for access to the data.

**Comment by viomunoz** [comment]
We were granted access to download this data this week, have arranged a meeting to deal with this.

**Comment by viomunoz** [comment]
We have now implemented a process to download bulk exome data.
