### ISSUE TITLE
Viability report: three lines showing viable need to show subviable in the FTP viability report

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#636]
**Description of issue:**

There are three lines that appear as "viable" in the vability report in the FTP site and as "preweaning lethality, incomplete penetrance" in the website.

DCC confirms the outcome is subviable (thus, as in the website). Their data shows these to have subviable calls submitted and exported (IMPC_VIA_001 Viability Outcome = Homozygous - Subviable and IMPC_VIA_002 Additional Outcome = Homozygous - Reduced Life Span).

Note that in the report "Supporting Data" shows "Homozygous - Reduced Life Span" but "Viability Phenotype" shows "viable" and should be "subviable".

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/b7086a48-612b-4358-b6d6-3f8da45462aa)

**Requirement:**
Please fix for DR 15.

**Comment by jmason-ebi** [comment]
Fixed to include Reduced Life span as subviable
