### ISSUE TITLE
Modify the FTP deployment

### ISSUE THREAD

**Issue by rwilson-ebi** [mpi2/PhenotypeData#649]
The TSC are changing the way the FTP site work. The filesystem mounted on ebb-cli will become read-only, and will only be available for writing in Harlow. 

- [ ] We need to modify the Jenkins job used in the data release to push out the data files and Solr Cores to the FTP site

**Comment by rwilson-ebi** [comment]
Written to IT-support for advice on the best way to move data to Harlow for the FTP site

**Comment by viomunoz** [comment]
This ticket can now be closed.
