### ISSUE TITLE
Investigate the EMMA links on the portal

### ISSUE THREAD

**Issue by rwilson-ebi** [mpi2/PhenotypeData#650]
A line produced by WTSI Slc5a2 carries a tm1a(KOMP) allele, but the ordering link now points to an EMMA web site rather than a KOMP repository.

The original products data coming from iMits provided an WTSI email address, but this must have been modified downstream to link to the EMMA site in preparation for the WTSI mouse house closure.

**Comment by viomunoz** [comment]
Will need to be checked for DR 16.0 to make sure this is fixed.

**Comment by viomunoz** [comment]
https://www.mousephenotype.org/data/genes/MGI:2181411

![Screenshot 2022-05-05 at 14.15.48.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/48222edc-33b0-42b1-923c-04da82e6b804)
