### ISSUE TITLE
Essential genes data portal: displays wrong number for rows in output

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#651]
This issue is potentially confusing for users.

The portal is returning the number of rows we expect for sets of 100 genes in the downloaded file. However, there is an incosistency between the number of rows the portal reports to have found and those in the file being downloaded. The user seems to be getting the correct number of rows in the downloaded file, despite the message on the portal, which indicates less rows than the file has.

Process:
For 3 different sets of 100 HGNC genes that were submitted:
1. Message on portal is "Showing 1 to 10 of xxx" with xxx being 303, 125 and 193, respectively
2. After clicking Download, message on portal is "Downloading xxx rows" (xxx as above)
3. Resulting files has 328, 191 and 306 rows, matching our expectation (matching number of rows in a file generated using scripts for manually downloaded files from the different sources (HGNC, HCOP, etc.).

Requirement:
Need to fix, the numbers need to match.

**Comment by ficolo** [comment]
I need the lists of genes used to replicate this bug.

**Comment by viomunoz** [comment]
Any list of genes would cause the same issue, i.e. the app does not report the number of rows in the file. The downloadable file had the expected number of genes and orhtologues.

**Comment by ficolo** [comment]
When I try with: MGI:1929293, HGNC:11424. 

It works as expected, so not any list of genes causes the issue.

Could you please provide me with a list of genes that I can use to reproduce the problem?

If you already have three lists of 100 genes I don't see why I have to build a new, but do let me know if you don't have it. I can just put this on the backlog until I have the time to gather 100 genes to test.

**Comment by viomunoz** [comment]
I have tried several sets of of 100 HGNC or MGI IDs and the number of rows reported on the website interface and the number of rows in the downloadable file are matching. This issue has been solved and the ticket can be closed now.
