### ISSUE TITLE
ABR data: hits have changed

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#698]
One of our users has raised the issue that the ABR hits have been changing. We need to understand what is the cause for this.

**Comment by rwilson-ebi** [comment]
There are 56 genes that were originally called as significantly abnormal for ABR (mostly tested at BCM, which I presume is Baylor) that are now missing. Others sites include Efhb, Ist1, Rcor3, Zfp652, Zmat4 which were tested at JAX, and Zdhhc5 at HMGU. There are also 37 no longer considered significant. There's nothing that stands out about where or when these 37 were tested that might explain why their significance has changed. As well as these 93 genes, there are 45 new ones annotated with "abnormal auditory brainstem response".
 
Examples of genes where the ABR data has disappeared are Zmat4 and Zscan21.  A gene which looks like there is a significant difference but is not marked as significant is Usp32 (see attached). An example of the opposite is Rffl (also attached). Other examples of genes which were marked as significant and aren’t any more are Coq4, Myo10 and Nxn. They are not as clear as Usp32, but in all 3 cases there’s a bigger difference between wildtypes and mutants than for Rffl.
 
The link to view data from Ocm mutants (a gene we are working on which certainly shows raised ABR thresholds) is broken.

**Comment by Hamedhm** [comment]
HAMED:

There is no data in DR15.1 (and probably DR15) for BCM ABR.
For the gene Efhb, I cannot find the colony JR33945 in DR15.1
The same for Ist1, Rcor3. Could it be an issue with GenTar?
For Zdhhc5, the pvalue has changed from 8.4e-5 to 2.5e-4 . The reason to change the pvalue is an increase in the number of data points
Zscan21 is BCM and it is not on DR15.1. 
Coq4 and Myo10 are WTSI genes and should not be changed at all. I do not see any difference between the Live and Beta site for these. **Piia is following this up.**
Nxn: the pvalue on the beta site is 0.000411 (6kzh) and does not meet our threshold. so it could be a bug in the annotation pipeline or the way we select the pvalues from the statspackets to present on the web portal.
About Usp32 (30khz), pvalue is pretty small and borderline 1.21e-4 to our threshold of 1e-4.

**Comment by rwilson-ebi** [comment]
Hamed has checked and the data has not passed QC at the DCC

**Comment by Hamedhm** [comment]
Hamed followed up on the genes in the DR16. We still do not have the BCM data and for JAX, the genes are still labelled as QC not_resolved.
