### ISSUE TITLE
Check the FTP data against the genotype-phenotype core

### ISSUE THREAD

**Issue by rwilson-ebi** [mpi2/PhenotypeData#707]
Check this data for DR16

A website user has reported that there are differences between what is in the DR15.1 FTP release and the website: 

e.g. Trp53: https://www.mousephenotype.org/data/genes/MGI:98834
The website displays a phenotype 'decreased circulating creatine kinase level' which is not present in the FTP, but is present in the API:
https://www.ebi.ac.uk/mi/impc/solr/genotype-phenotype/select?q=marker_symbol:Trp53%20AND%20mp_term_id:%22MP:0010091%22

And the FTP (http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-15.1/results/genotype-phenotype-assertions-ALL.csv) holds a hit for 'MP:0005565 - increased blood urea nitrogen level" p value = 1.19809828724726E-10
but this is not visible on the website or API.

**Comment by viomunoz** [comment]
**Trp53 comparisons for DR16.0**

**Data compared:**

1. Phenotype table on website https://dev.mousephenotype.org/data/genes/MGI:98834
2. File downloaded from Phenotype table section on website https://dev.mousephenotype.org/data/genes/MGI:98834
3. FTP site - genotype-phenotype-assertions-IMPC.csv http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/latest/results/genotype-phenotype-assertions-IMPC.csv.gz
4. All Data table in website - desirable, but not possible as it does not display; get message "A moment please while we gather the data…" https://dev.mousephenotype.org/data/genes/MGI:98834

**Outcome of the comparison:**

1. Full match between significant phenotypes as donwloaded from website (Phenotype table) and CSV file from FTP site									
2. One potential mismatch that needs to be investigated - for "persistence of hyaloid vascular system" phenotype table on website shows "female male", while the two files indicate "female" for the most extreme p-value. For the other cases, when "female male" symbols are displayed on the website, they correspond with "not_considered" in the files. For this reason, this requires further investigation.

![Screenshot 2022-04-13 at 18.21.08.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c13fb119-dadd-4a7b-9d93-0948ec38b059)

File here with lines extracted from CSV and TSV from website:
[https://app.zenhub.com/files/37316577/d1f36643-26a4-484b-8e85-76687efccb9f/download](https://app.zenhub.com/files/37316577/d1f36643-26a4-484b-8e85-76687efccb9f/download)

**Comment by viomunoz** [comment]
In summary, based on the data in the TSV and CSV files, the Phenotype table in the website for phenotype "persistence of hyaloid vascular system" for the most extreme p-value shoud show the symbol for female, and not the symbols for male and female.

**Comment by ficolo** [comment]
I've just fixed the bug with the All data table not loading on DEV

**Comment by viomunoz** [comment]
I remember being involved in this decision.
The problem I see is that the way the results are displayed is ambiguous.
1.- In that particular example, when "female male" symbols are displayed on the website, they correspond with "not_considered" in the files. 
2.- In the "persistence of hyaloid vascular system" phenotype in which the p-value 1.63 x 10-6 is displayed (because it is the lowest - this is how the display was designed, I think it makes sense), the association is only with females, so I am not sure if it was intended to display males and females even if an additional (greater) p-value shows males signficant.
Let's discuss internally, then decide.

**Comment by viomunoz** [comment]
I will move to the backlog as this is not a priority right now.

**Comment by viomunoz** [comment]
Discussed internally, agreed to document to check against in the context of a new ETL epic.
This ticket will be closed.
