### ISSUE TITLE
UKB project: sexual dimorphism analyses for mice need a process to combine data from different centers

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#724]

**Comment by viomunoz** [comment]
We had a meeting on Wed this week to revise a scoring system and a flow chart to accomplish this task.

**Comment by viomunoz** [comment]
Testing some new approaches. Ongoing.

**Comment by viomunoz** [comment]
The score and flow chart is allowing us a method to find agreement or disagreement on sexual dimorphism and its direction across centers.
We are working on whether it is possible to identify a method to find agreement or disagreement on the non significance of sexual dimorphism across the centers.

**Comment by rwilson-ebi** [comment]
Do a comparison of the score vs the outcome of the figures. Add three columns to compare scores to charts.

**Comment by rwilson-ebi** [comment]
Do a comparison of the score vs the outcome of the figures. Add three columns to compare scores to charts.

**Comment by viomunoz** [comment]
This has been done. We include also a few fixes to the flow chart for the paper.
