### ISSUE TITLE
The parameter pages in IMPReSS that are linked from the Charts Page are difficult to read

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#75]
Put a plain language summary in a pop-up so you can see this information in context.

![Slide83 (1)](https://user-images.githubusercontent.com/2343039/57388021-52919980-71af-11e9-80c3-05e4d937233d.png)

**Comment by viomunoz** [comment]
This information provided. 
See example: https://www.mousephenotype.org/data/charts?accession=MGI:109331&parameter_stable_id=IMPC_ABR_010_001&allele_accession=MGI:5548389&zygosity=heterozygote&phenotyping_center=TCP&bare=true
