### ISSUE TITLE
IMPRESS - Ontology search - can we have some changes

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#752]
There is some behaviour in this papge that could confuse users. 

1. The same row appears three times (see [1] https://www.mousephenotype.org/impress/ontologysearch?ontoTerm=MP%3A0005178; you can use Search: "impc" to see it clearly) -- can we have only unique rows?

2. There is a column "Option" that is blank [1] -- can we have this removed?

3. The Parameter is better linking to the Parameter ontolgy page https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=682#30292 instead of the Procedure page. (Currently, clicking on the parameter displays the Procedure page filtered for the parameter -- if you would  miss that the list is filtered, appears that the procedure has only one parameter, which is confusing.) An alternative would be that the table behaviour is that clicking on one row brings the user to the Procedure page -- as we did for the main website, seemed preferred based on the UX sessions -- but that may require more work and the gain may not be so high.

(Note. - I see apparently the same page with a different URL: https://www.mousephenotype.org/impress/OntologyInfo?action=list&procID=782#37392, to which I got by clicking on Total Cholesterol here: https://www.mousephenotype.org/impress/ProcedureInfo?action=list&procID=782&pipeID=7) 

----------------------------------------------------
[1] Screenshot https://www.mousephenotype.org/impress/ontologysearch?ontoTerm=MP%3A0005178

![image.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/b05ec1de-9bc5-49d7-98fc-1244e708d1d0)

**Comment by viomunoz** [comment]
Thank you for looking into this.
1.- Agree, thanks! that would be great.
2.- Ok, thanks! I wonder whether we would want to present less information to users at once, on this table? I see the "Option" information is also displayed in the ontology info pages and procedure pages. But ok to leave if you think this is better.
3.- Thanks!

**Comment by viomunoz** [comment]
Closing this ticket as the redirection issue was resolved. We will discuss internally the option to display procedure IDs as a column in the search results table.

**Comment by antfrost** [comment]
>We will discuss internally the option to display procedure IDs as a column in the search results table.

Dev call?

**Comment by viomunoz** [comment]
Sure!
