### ISSUE TITLE
Search ignores "-"

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#77]
Sign “-“ is ignored by search engine. 

**Example** 

Gene “Aldh3a2” has synonyms: FALDH, Aldh4-r, Ahd-3r, Aldh4, Ahd3-r, Ahd3, Ahd-3. 

“FALDH” is found as expected, but not “Aldh4-r” or “Ahd-3r” as search looks for “Aldh4r” or “Ahd3r”, respectively.

Problem: when entering "Ahd-3r" search looks for "Ahd3r" and "Aldh3a2" is not returned.

![Screenshot 2019-05-16 at 11 42 02](https://user-images.githubusercontent.com/29598654/57847974-ae6faa00-77cf-11e9-9cf2-23f8b1adf29a.png)

**Comment by jmason-ebi** [comment]
Fixed in commit 0730a655
