### ISSUE TITLE
Documentation: "how to cite IMPC" section update

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#780]
Suggestion from one of our users to include more papers, so users can select most appropriate.

**Current:**

To cite the IMPC please mention our website www.mousephenotype.org and the following publication:

Dickinson et al. (2016). 'High-throughput discovery of novel developmental phenotypes', Nature, 537: 508-14.

**After disuccsing internaly, we agreed on the following text:**

To cite the IMPC, please mention our website www.mousephenotype.org and cite one or more the following publications, as appropriate.

Initial paper:
* Dickinson et al. (2016). High-throughput discovery of novel developmental phenotypes, Nature 537: 508-514

IMPC production papers:
* Lines produced from the ES cell resource -- Birling et al. (2021) 'A resource of targeted mutant mouse lines for 5,061 genes', Nat Genet, 53:416-19. https://pubmed.ncbi.nlm.nih.gov/33833456/
* Lines produced with Cas endonucleases -- Elrick et al. (2021) 'The production of 4,182 mouse lines identifies experimental and biological variables impacting Cas9-mediated mutant mouse line production', bioRxiv https://www.biorxiv.org/content/biorxiv/early/2021/10/06/2021.10.06.463037.full.pdf

IMPC domain-specific articles (in chronological order):
* Disease models - https://pubmed.ncbi.nlm.nih.gov/28650483/
* Hearing loss - https://www.ncbi.nlm.nih.gov/pubmed/29026089
* Cardiadiovascular - https://www.nature.com/articles/s44161-022-00018-8
* Bone - https://www.ncbi.nlm.nih.gov/pubmed/33370286
* Gene essentiality - https://www.ncbi.nlm.nih.gov/pubmed/32005800
* Metabolism - https://www.ncbi.nlm.nih.gov/pubmed/29348434
* Eye - https://www.ncbi.nlm.nih.gov/pubmed/30588515
* Circadian rhythm - https://www.ncbi.nlm.nih.gov/pubmed/31929527
* Pain - https://www.ncbi.nlm.nih.gov/pubmed/35552317

**Comment by viomunoz** [comment]
This has been done.
Added the sexual dimorphism paper and a link to the Publications section of the website, which seems pertinent.
https://www.mousephenotype.org/help/faqs/how-do-i-cite-the-impc/
Screenshot here:
![Screenshot 2022-06-17 at 12.54.26.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/100f691d-2599-4411-942f-545c627f9fd2)

**Comment by viomunoz** [comment]
I have re-opened this ticket as this page now looks as in the screenshot below (which is different from how it originally looked).

The publication date on this page is June 10th. The comments above are from June 17th. It seems a snapshot of the live IMPC for the new infrastructure was taken. Changes were happening to the site that did not get transferred to the new site.

Thus, this page will be regenerated again. 

![Screenshot 2022-08-02 at 14.16.25.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/cd23d776-b499-4159-bb7a-eec2a820e9e5).

**Comment by viomunoz** [comment]
**This page has been regenerated again.**


**Screenshot of the page:**


![Screenshot 2022-08-02 at 14.33.56.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/1d46e797-76f1-4db7-8a22-1226bdca007b)


**A copy of the content in text format is here:**

If you use data or images generated by the IMPC in a publication or grant application, please do cite us!

To cite the IMPC, please mention our website www.mousephenotype.org and cite one or more the following publications, as appropriate.

Initial paper:

- Dickinson et al. (2016). High-throughput discovery of novel developmental phenotypes, Nature 537: 508-514

IMPC production papers:

- Lines produced from the ES cell resource -- Birling et al. (2021) 'A resource of targeted mutant mouse lines for 5,061 genes', Nat Genet, 53:416-19. https://pubmed.ncbi.nlm.nih.gov/33833456/
- Lines produced with Cas endonucleases -- Elrick et al. (2021) 'The production of 4,182 mouse lines identifies experimental and biological variables impacting Cas9-mediated mutant mouse line production', bioRxiv https://www.biorxiv.org/content/biorxiv/early/2021/10/06/2021.10.06.463037.full.pdf

IMPC domain-specific articles (in chronological order):

- Sexual dimorphism – https://www.nature.com/articles/ncomms15475
- Hearing loss - https://www.ncbi.nlm.nih.gov/pubmed/29026089
- Disease models - https://pubmed.ncbi.nlm.nih.gov/28650483/
- Metabolism - https://www.ncbi.nlm.nih.gov/pubmed/29348434
- Eye - https://www.ncbi.nlm.nih.gov/pubmed/30588515
- Gene essentiality - https://www.ncbi.nlm.nih.gov/pubmed/32005800
- Bone - https://www.ncbi.nlm.nih.gov/pubmed/33370286
- Circadian rhythm - https://www.ncbi.nlm.nih.gov/pubmed/31929527
- Cardiadiovascular - https://www.nature.com/articles/s44161-022-00018-8
- Pain - https://www.ncbi.nlm.nih.gov/pubmed/35552317

Please visit the Publications section of the website for summaries on the main findings of some of these papers.

The IMPC makes this dataset publicly available under the Creative Commons Attribution 4.0 International license (CC-BY 4.0). See our FAQ “Is IMPC data freely available?” for more information about this.

**Comment by Hamedhm** [comment]
@viomunoz  I suggest adding OpenStats to the list for the analysis methodology because I see quite some users still citing PhenStat

**Comment by viomunoz** [comment]
@Hamedhm Thanks for the suggestion! I will add OpenSats and the soft windowing paper. Any Bioconductor packages you think are worth citing or not needed as they should be referenced in those two papers?

**Comment by viomunoz** [comment]
The documentation has been updated.
