### ISSUE TITLE
Search results: "Mice produced" does not show in Search results for gene Aasdhppt

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#797]
**Issue:**
"Mice produced" does not show in Search results for gene Aasdhppt, but mice have been produced as can be seen from the Order allele section.

**To reproduce:**
https://www.mousephenotype.org/data/search?term=aasdhppt&type=gene

**Screenshots:**
![Screenshot 2022-07-15 at 10.27.17.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3ddedffb-cdf5-4a5b-b986-ab460bdbb67e)

![Screenshot 2022-07-15 at 10.29.45.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/b4f4d030-6764-4e5f-8dd0-88c988e9dce8)

**Comment by rwilson-ebi** [comment]
The GenTaR gene_interest report has following information

Gene Symbol	MGI ID	Assignment Status	ES Null Production Status	ES Conditional Production Status	Crispr Production Status	Early Adult Phenotyping Status

Aasdhppt	MGI:1914868	Assigned	Mouse Allele Modification Genotype Confirmed		Plan Abandoned	Phenotyping Started

Missing the "Mouse Allele Modification Genotype Confirmed" status when processing the report?

**Comment by ficolo** [comment]
Just released a new version of the products / gene core that fixes this issue on DEV: https://dev.mousephenotype.org/data/search?term=Aasdhppt&type=gene
