### ISSUE TITLE
Discrepancies in colony IDs between procedeureCompletenessReport and gene-phenotype assertion reports

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#799]
A discrepancy in the the colony IDs reported in the procedecureCompletenessReport and gene-phenotype assertion reports in the FTP site seems to have been found.

This has been found for the reports for DR15.1.
http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-15.1/results/

Colony IDs obtained from:
- genotype-phenotype assertions IMPC
- genotype-phenotype assertions EUROPHENOME
- genotype-phenotype assertions MGP

The last two should contain legacy data, while the IMPC does not.

The other file that was used to look for colony IDs was the procedureCompletenes report.

These initial findings, reported below, need to be investigated further to confirm this is an issue, or whether there is a reason for the non overlap.

**Findings:**
1. Some overlap in colony IDs was found across the genotype-phenotype assertion reports. (An analysis for the overlap was replicated excluding and including zygosity as part of the colony ID and the number of colonies that overlapped was the same; the analysis involved keeping unique colony IDs from each file and doing the overlap between colony IDs in the IMPC report and the colony IDs in the other two reports.)

Colony IDs that overlap:
- between IMPC and MGP = 51 colonies
- between IMPC and EUROPHENOM = 11 colonies

The overlaps seems to be due to legacy and not legacy procedures applied to the same colony - but this will require further investigation to confirm whether this is the situation in all cases. This is probably not an issue.

2. Further, the colony IDs in the procedureCompletenes report were cross checked with those found in the genotype-phenotype assertion reports. The results indicate that there are colony IDs in the procedureCompletenes report that are NOT found in the genotype-phenotype assertion reports  and viceversa. (Note that 3i and ALL reports were not included in this analysis; also note that at least some colonies in the procedureCompletenes report that were not found in the genotype-phenotype assertion reports have been investigated for procedures other than 3i procedures, e.g. ABR).

- Colony IDs found only in procedureCompleteness report = 1,520 (268 have phenotype hits)
- Colony IDs found only in genotype-phenotype assertion reports (these were all in the IMPC report) = 69

List of colonies in the attached file:

[https://app.zenhub.com/files/37316577/a67f4953-7105-416c-ba97-a56bd4194d31/download](https://app.zenhub.com/files/37316577/a67f4953-7105-416c-ba97-a56bd4194d31/download)

**Comment by Hamedhm** [comment]
IMPC EUROPHENOME MGP overlaps
[Uploading... IMPC_EUROPHENOME_MGP_overlap.csv]

**Comment by viomunoz** [comment]
One such colony is BL1129:
- present in procedure completenes report dr15.1 with 6 hits in the hematological system http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-15.1/results/procedureCompletenessAndPhenotypeHits.csv.gz
- absent from genotype-phenotype assertions IMPC http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-15.1/results/genotype-phenotype-assertions-IMPC.csv.gz

In DR17:
- present in procedure completenes report dr17, but now 4 hits instead of 6 (2 in the hematological system, 1 behaviour, 1 CBC) http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-17.0/results/procedureCompletenessAndPhenotypeHits.csv.gz
- present in genotype-phenotype assertions IMPC http://ftp.ebi.ac.uk/pub/databases/impc/all-data-releases/release-17.0/results/genotype-phenotype-assertions-IMPC.csv.gz
- present in the website gene Klf14 with the same phenotype hits https://www.mousephenotype.org/data/genes/MGI:3577024

Need to check for DR17

**Comment by viomunoz** [comment]
Same checks performed for DR17 and things look better there and the findings make sense.
