### ISSUE TITLE
Mettl5 and other genes - phenotypes for males and females

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#804]
Problem reporting significant phenotypes for only males or females for some parameters: 
Mettl5 https://www.mousephenotype.org/data/charts?accession=MGI:1922672&allele_accession_id=MGI:6273953&zygosity=homozygote&parameter_stable_id=IMPC_OFD_007_001&parameter_stable_id=IMPC_OFD_011_001&pipeline_stable_id=HMGU_001&procedure_stable_id=IMPC_OFD_001&parameter_stable_id=IMPC_OFD_007_001&parameter_stable_id=IMPC_OFD_011_001&phenotyping_center=HMGU

- Gene page indicates significant phenotype for both males and females
- Description of the experiment: males and females reported 
- Graphs and summary stats only show males

**Comment by viomunoz** [comment]
![Screenshot 2022-11-11 at 16.00.16.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/67a86ce2-508c-44c6-aca9-4635bb2cf495)

**Comment by viomunoz** [comment]
Behaviour phenotypes appear as signficant in Significant Phenotypes table and No significant in chart pages

**Comment by viomunoz** [comment]
![Screenshot 2022-11-11 at 16.09.34.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/4b63c5ae-da58-4a79-8139-4a1545a5715f)

**Comment by viomunoz** [comment]
More examples in dev (it is DR18)

See a phenotype I chose at random:

https://dev.mousephenotype.org/data/phenotypes/MP:0001586

Il2ra:
https://dev.mousephenotype.org/data/charts?accession=MGI:96549&allele_accession_id=MGI:5766766&zygosity=homozygote&parameter_stable_id=IMPC_HEM_002_001&pipeline_stable_id=ICS_001&procedure_stable_id=IMPC_HEM_002&parameter_stable_id=IMPC_HEM_002_001&phenotyping_center=ICS

Associated Phenotype :	No significant association
Male signficant, no p-values reported

Msn:
https://dev.mousephenotype.org/data/charts?accession=MGI:97167&allele_accession_id=MGI:5632533&zygosity=homozygote&parameter_stable_id=IMPC_HEM_002_001&pipeline_stable_id=JAX_001&procedure_stable_id=IMPC_HEM_002&parameter_stable_id=IMPC_HEM_002_001&phenotyping_center=JAX

Associated Phenotype :	No significant association
Females signficant, no p-value reported

Ercc5:
https://dev.mousephenotype.org/data/charts?accession=MGI:103582&allele_accession_id=MGI:5636892&zygosity=heterozygote&parameter_stable_id=IMPC_HEM_002_001&pipeline_stable_id=BCM_001&procedure_stable_id=IMPC_HEM_002&parameter_stable_id=IMPC_HEM_002_001&phenotyping_center=BCM

Associated Phenotype :	decreased erythrocyte cell number
Males and females signficant

Atp13a3:
https://dev.mousephenotype.org/data/charts?accession=MGI:2685387&allele_accession_id=MGI:6314147&zygosity=homozygote&parameter_stable_id=IMPC_HEM_002_001&pipeline_stable_id=JAX_001&procedure_stable_id=IMPC_HEM_002&parameter_stable_id=IMPC_HEM_002_001&phenotyping_center=JAX

Associated Phenotype : increased erythrocyte cell number
Males and females significant

**Comment by viomunoz** [comment]
![Screenshot 2022-11-24 at 19.39.02.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/1bb0b662-d5a2-473c-8545-e70567d045a7)

**Comment by viomunoz** [comment]
Phenotype page should normally only have the symbol for the signficant sex, but this is less relevant

**Comment by viomunoz** [comment]
![Screenshot 2022-11-30 at 17.01.10.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/d8e361b0-f5c7-4417-8384-3137455b4069)

**Comment by rwilson-ebi** [comment]
Two separate problems 
- Hamed has fixed the data labelling issue
- Web frontend issue to be addressed 
Plan to address with DR 19

Main issue
Tag used to assign GP calls 
- not just free text on the website
