### ISSUE TITLE
Comms - newsletter for IMPC

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#810]
Assessing options for having a functional Newsletter for IMPC again. We have not had one since Comms Officer left March 2021.

**Comment by viomunoz** [comment]
Four services were assessed, having a meeting later today 4th November 2022.

**Comment by viomunoz** [comment]
Several options investigated, most adequate seems to be MailChimp.

**Comment by rwilson-ebi** [comment]
Best option identified - implementation requires discussion
