### ISSUE TITLE
Three genes are missing pain sensitivity phenotypes in Gene page

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#824]
In the Pain Sensitivity page, there is a list of genes with pain sensitivity significant phenotypes.
However, three genes are not displaying the pain sensitiviy phenotypes in the "Phenotypes" section on the gene page.

- Abhd13
- Cgnl1
- Cnrip1

**To reproduce:**
From the Pain Sensitivity page:
https://www.mousephenotype.org/publications/data-supporting-impc-papers/pain/
click on the genes listed above (see first screenshot below).
In the gene page, no pain sensitivity phenotype is displayed (second screenshot below).
Please compare with the other genes in that list - they do show pain sensitivity phenotypes.

![Screenshot 2022-12-02 at 12.04.19.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/1d3cbf26-87ff-4dc6-b6f1-9ac74c5cdc4d)

![Screenshot 2022-12-02 at 12.04.42.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/1179735e-fd9d-4d6e-beb4-8debf9adb350)

**Comment by tudorgroza** [comment]
I'll look into this.
