### ISSUE TITLE
Tables and figures for UKB SD ms

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#828]
Several iterations over tables and figures for the ms

**Comment by rwilson-ebi** [comment]
Some charts outstanding for preparation of the UKKBB paper - detailed in the UKBB rolling notes

**Comment by viomunoz** [comment]
Progress has been made on this. We have a final collection of figures and tables for the main text and supp material. Some charts outstanding for generation as detailed in UKB rolling notes.

**Comment by viomunoz** [comment]
Another iteration - final checks, new figures as per UKB rolling notes.

**Comment by rwilson-ebi** [comment]
Work ongoing

**Comment by rwilson-ebi** [comment]
Discussed on Wednesday 22nd - some changes required to layout of the charts

**Comment by rwilson-ebi** [comment]
Created some new charts. Will need to recreate some due to age range split. Going well.

**Comment by rwilson-ebi** [comment]
Figures should be done - will check on the status

**Comment by rwilson-ebi** [comment]
Done
