### ISSUE TITLE
static menu is not static

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#88]
Menu needs to be fixed on our side (EBI), as what we see under "DATA" when we are on a Gene page or the Publications page is different from how it should look like.

Three screenshots follow.

-----------------------------------------
This is how it should look like:
-----------------------------------------
![Screenshot 2019-05-24 at 20 44 09](https://user-images.githubusercontent.com/29598654/58352982-20e22900-7e65-11e9-8f7d-a53a202b6ca5.png)

-----------------------------------------
Compare with this:
-----------------------------------------
![Screenshot 2019-05-24 at 20 42 47](https://user-images.githubusercontent.com/29598654/58353014-3c4d3400-7e65-11e9-9672-d17ca0e733fe.png)

-----------------------------------------
Or this:
-----------------------------------------
![Screenshot 2019-05-24 at 20 44 50](https://user-images.githubusercontent.com/29598654/58353078-6ef72c80-7e65-11e9-8c40-84fd65dfc4a4.png)

**Comment by ficolo** [comment]
@jmason-ebi Was gonna talk this to you this afternoon, I think this a WP issue:

https://www.mousephenotypetest.org/jsonmenu/


The structure is coming incomplete.

**Comment by jmason-ebi** [comment]
Sure enough.We will need to pass this to Aaron.On May 24, 2019 11:12 PM, Federico López Gómez <notifications@github.com> wrote:@jmason-ebi Was gonna talk this to you this afternoon, I think this a WP issue:
https://www.mousephenotypetest.org/jsonmenu/
The structure is coming incomplete.
